### ISSUE TITLE
[Smoke Test] bukalapak.com carousel stops working

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1008]
Download the carousel images multiple times when they're moving will make them freeze.
Focus has the same issue.

Build: 1374
DuT: Samsung, Advan

**Comment by dakaizou** [comment]
See [recording](https://drive.google.com/file/d/0B0uVZlaHN366Q2c5cmNJVFdFb2c/view?usp=sharing) for detail

**Comment by chianger** [comment]
Edge use case.

**Comment by dakaizou** [comment]
Remove QAwanted, since the recording is clear

**Comment by NashTung** [comment]
Work for me.
Video:
https://drive.google.com/open?id=1w4caJoojFMY7Hej1Nb_xXoDpkPxJ4P7A

Device: Advan i5C
Rocket: 2.0.0(4168).nightly
Android: 5.1
Android Webview: 51.0.2704.81
