### ISSUE TITLE
Missing screenshots can still be shared but can't be edited

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1024]
STR:
1. Enter viewer
2. Delete the screenshot with other app (or detach sdcard)
3. Tap on the edit button
4. Tap on the share button

P2/P3 suggested

Build: 1412 RC 1
DuT: Samsung

**Comment by chianger** [comment]
So the step2 from the STR is actually "delete from file browser or gallery app, NOT using Rocket".
I would say P2 as enhancement to deal with this case.

**Comment by chianger** [comment]
WORKSFORME
