### ISSUE TITLE
Setup Dashboard 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1031]
- Track MAU/DAU
- Understand top features the users use
- Track Turbo mode usage
--Track block image usage
-- Track screenshot usage 
-- Track clear cache usage
- Track default browser usage

**Comment by chianger** [comment]
Eddie

**Comment by elin-moco** [comment]
MAUs
https://sql.telemetry.mozilla.org/queries/47233
MAU by locale
https://sql.telemetry.mozilla.org/queries/47234
DAUs
https://sql.telemetry.mozilla.org/queries/47232#127936

Events (to identify top features):
https://sql.telemetry.mozilla.org/queries/47388#128314
Settings (including default browser):
https://sql.telemetry.mozilla.org/queries/47412#128378

**Comment by chianger** [comment]
then i think this item is done.
