### ISSUE TITLE
Multiple download entries on Oppo devices storing to internal storage

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1061]
STR:

1. Switch to download to internal storage in settings.
2. Download the same file for multiple times.
3. Multiple items is added to the list, while they all points to the same instance of the file.
Expected-result-3. Only one entry is listed. 

Root cause:

In BrowserFragment.java:

    DownloadInfoManager.getInstance().delete(downloadId, null);
should actually be:

    DownloadInfoManager.getInstance().delete(info.getRowId(), null);

**Comment by dakaizou** [comment]
verified in build 1641
