### ISSUE TITLE
Url is sometimes the last last visited url rather than current

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1064]
STR:
1. Visit youtube
2. Take screenshot
3. Tap on any video down below
4. Check the url

Note: only happened on youtube

Build: 1455
DuT: Samsung, Advan

**Comment by chianger** [comment]
QAWanted to address the reproduce rate.

**Comment by dakaizou** [comment]
Reproduce rate is around 20%

DuT: Samsung, Advan, Redmi
Build: 1455

**Comment by chianger** [comment]
20% is high so let's fix this.

**Comment by mTwTm** [comment]
A very obvious example would be: yahoo.com, try swiping left or right to change the focused tab (熱門 新聞 TV 娛樂...etc)

**Comment by mTwTm** [comment]
Fixed in #1150

**Comment by dakaizou** [comment]
I think it is still valid issue.
Notice the url of the following screenshot
![screenshot](https://lh3.googleusercontent.com/-Es1NloolTgU/We_v_X6Y6-I/AAAAAAAABwM/SmNzUVH_hdkhf23oTPsh7e_FRBU4eBkTQCL0BGAYYCw/h1920/5533739214542617817%253Faccount_id%253D3)

Build: 1593
DuT: Samsung

@mTwTm Shall we reopen this?

**Comment by dakaizou** [comment]
fixed in build 1626 verified
