### ISSUE TITLE
Open links from external apps won't reset the menu status

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#1066]
STR:

1. Launch Zerda and tap on Menu
2. Press System Home and use other app to open a link w/ Zerda
3. Observe the page

Expected Result:

3. Page is open and no menu

Actual Result:

3. Menu is over the page linked from external app

**Comment by harly21** [comment]
Same thing happens when long tap to open context menu

**Comment by mTwTm** [comment]
possible fix: in onStop close the menu.

**Comment by chianger** [comment]
note: menu and context menu both can reproduce.

**Comment by Jacklin-ux** [comment]
The expected behavior:
1. Rocket opens a link from external apps, close the menu/context menu then open the link
2. Switch between apps by task manager, keep the menu/context menu on the screen

About above, possible?
