### ISSUE TITLE
Downloaded image with uppercase extension cannot be opened correctly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#1067]
Visit https://goo.gl/2CYmiQ and attempt to download the image. Zerda shows download completed but file cannot be opened by apps.  It forces to use Download manager to observe the file. From System Download manager, users can tap on the downloaded file and open with image viewer apps.

DuT: Samsung J7, Advan
Build: 1455

**Comment by mTwTm** [comment]
Root cause:
Download manager failed to provide the mime type of this file. Maybe we should guess through the extension.

**Comment by WeiWW** [comment]
@mTwTm I tried. It's no matter mime type or file extension are same situation.

**Comment by mTwTm** [comment]
@WeiWW for that case, we know the extension is jpg, and we can guess the MimeType and fill it in the intent.
