### ISSUE TITLE
Turbo Mode makes the content of m.tokopedia.com disappear on Mito

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Rocket#1072]
Zerda:

![2251589575286413960 account_id 0](https://user-images.githubusercontent.com/8446577/31264795-e812c964-aa9d-11e7-8f48-3b56c1350f23.png)

Fennic with Do Not Track and Tracking Protection on:

![290771903854291247 account_id 0](https://user-images.githubusercontent.com/8446577/31264775-d66384f6-aa9d-11e7-8d1a-2fdf96fdb294.png)

Turbo Mode only does this on Mito.

**Build:** 1455

**Comment by walkingice** [comment]
the web-page tries to get resource with url 'blob:https%3A//m.tokopedia.com/c3b845fd-c6d8-4846-9f73-ced5758e0d3d' which is blocked by our tracking protection[1]

[1] https://github.com/mozilla-tw/Rocket/blob/0.9-Beta/app/src/webkit/java/org/mozilla/focus/webkit/TrackingProtectionWebViewClient.java#L80

**Comment by chianger** [comment]
We'll include this fix in RC1

**Comment by dakaizou** [comment]
verified in build 1647
