### ISSUE TITLE
Integrate Firebase [for Nightly channel, closed alpha testing]

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1084]

**Comment by joechengla** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1411911

**Comment by chianger** [comment]
moved to sprint 1.0.5 since this is not blocking 1.0.4 release. also, the backend config is still in flight.

**Comment by weslyhuang** [comment]
IN for May 12.
