### ISSUE TITLE
Consider adding ABPindo into the blocklist

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-tw/Rocket#1087]
ABPindo (https://github.com/ABPindo/indonesianadblockrules) an actively maintained blocklist for Indonesian websites. Adopting this list might help solve some of our site compatibility issues and make our Turbo Mode even better – but keep in mind that we may need to clear things with Legal before we do this.

**Comment by weslyhuang** [comment]
next step on ENG to implement.

**Comment by weslyhuang** [comment]
only partially support. agreed can go first with what we can do then see.

**Comment by chianger** [comment]
close since #2051 was merged
