### ISSUE TITLE
Change preset topsite's default count  (magic number)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#1091]
relevant to #1090

**Comment by chianger** [comment]
need UX to define the actual magic number.

**Comment by Jacklin-ux** [comment]
UX suggest,
Before: 14 12 10 8 6 5 4 3
Magic number: 20 18 16 14 12 10 8 6 

This suggestion is for current beta version. But we still need fix the wrong counting of opening same webpage from top sites, and consider using Tori's magic number's proposal in the future.

**Comment by dakaizou** [comment]
verified in build 1563
