### ISSUE TITLE
In-App promotion string correction

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1096]
- [ ] Change the string to the correct one (#950)
> #### _7-9. Home | Menu | Settings | Share with friends (P 1.5)_
> - [ ] _"Share Firefox Rocket with friends!"_
> - [ ] _"Fast and lightweight"_
> - [ ] _"Helps save data"_
> - [ ] _"Powerful screenshots"_
> - [ ] _"SHARE"_
- [ ] Text should be left aligned
- [ ] List bullets should be rockets

![screenshot](https://lh3.googleusercontent.com/-wkVb8QZuBkk/Wd7grZl93GI/AAAAAAAABlI/BQeFIzTo0Ck2laGZsTks7ASJhskfbbaLwCL0BGAYYCw/h1920/3190703157783292087%253Faccount_id%253D3)
![screenshot](https://lh3.googleusercontent.com/-KEVtmgmbBSM/Wd7gqljhLOI/AAAAAAAABk4/_osRNPd07ngaSugTQL8z7USi4tT5crrrACL0BGAYYCw/h1920/4786204433946525770%253Faccount_id%253D3)

Build: 1490
DuT: Samsung

**Comment by FlyTori** [comment]
The strings on the screenshots are correct and reviewed by copy writer. I will update the UX spec to match the correct one.

**Comment by dakaizou** [comment]
close as invalid, remove NeedTriage and add UX&VD for UX spec

**Comment by FlyTori** [comment]
Sped updated: [Zerda] Menu,Panel,Download,History_v.2.2.pdf
https://drive.google.com/open?id=0B4dMhI4hp32OenhfZGRTc0tVWVk
