### ISSUE TITLE
In-App promotion close button and text color

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1097]
- [ ] Close button on the top right corner
- [ ] Title color should be #272727
- [ ] Body color should be #737373 

![screenshot](https://lh3.googleusercontent.com/-wkVb8QZuBkk/Wd7grZl93GI/AAAAAAAABlI/BQeFIzTo0Ck2laGZsTks7ASJhskfbbaLwCL0BGAYYCw/h1920/3190703157783292087%253Faccount_id%253D3)

Build: 1490
DuT: Samsung

**Comment by carol-mozilla** [comment]
Visual spec:https://drive.google.com/open?id=0B1V1eo-I8g3dc0E2MktGa2xSaWs

**Comment by mTwTm** [comment]
Some color text is incorrect too, let's fix this in this issue too.

**Comment by dakaizou** [comment]
verified in build 1512
