### ISSUE TITLE
Bookmark support

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1104]

**Comment by weslyhuang** [comment]
UX spec ready, pending on Visual one's (measures, ...)

**Comment by weslyhuang** [comment]
Visual work is complete and the only left work is the color selection, per today's standup update. @Jacklin-ux please feel free to remove the "UX&VD Wanted" label once the selection is done : )

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1R3QzuAM80-IaXLRMopYTupee2hjHQRWD/view?usp=sharing

**Comment by mTwTm** [comment]
Should be closed with current integrations.
