### ISSUE TITLE
Telemetry for new P1.5 features

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1105]

**Comment by chianger** [comment]
Inproduct feedback;
inproduct sharing;
screenshot contextual hint;
exit button;
app update

**Comment by chianger** [comment]
@idiotmax can review?

**Comment by chianger** [comment]
@joechengla please update https://docs.google.com/spreadsheets/d/1ey5vAjAvwKgzWud0-Rr9GpKWJfETpkuuljNYyMz-rVg/edit#gid=0

@Ben-YPLai @idiotmax will you update https://github.com/mozilla-tw/Rocket/wiki/Telemetry once this is done?
