### ISSUE TITLE
kompas.com does not work for some users

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1108]

**Comment by joechengla** [comment]
[https://drive.google.com/file/d/0By2sNBDNKma0YS1wbE5qRlJUR00/view?usp=sharing](url)
Trouble with visiting kompas.com (either from topsites or typed manually) 
Using Firefox Beta for Android works
Got the same error when using firefox focus

sub domains work http://tekno.kompas.com/
or if type www.kompas.com into Rocket, it works
This user is using Telkomsel (mobile carrier)

Another user using XL (mobile carrier) works fine without problems

**Comment by chianger** [comment]
adding 'needtriage' label. probably we'll need to take care of this since Kompas is in the preset top site list.

**Comment by joechengla** [comment]
another user on tri (3), tri.co.id

**Comment by chianger** [comment]
considering user agent whitelist if that's the root cause

**Comment by chianger** [comment]
investigation shows this not relevant to user agent.

**Comment by chianger** [comment]
action: add ID community telegram group to clarify whether "clear cookie" is a valid workaround.

**Comment by kelimuttu** [comment]
Worked for me in Fx Rocket, Fx Focus, or Chrome using Telkomsel.

**Comment by chianger** [comment]
Downgrade to P2 as we don't have actions from eng side.
Keep monitoring.

**Comment by chianger** [comment]
WORKSFORUS
