### ISSUE TITLE
Menu is still accessible for brief while after taking screenshot

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1110]
STR:
1. Visit any page
2. Double tap on the screenshot button
3. Menu pops out

Build: 1455
DuT: Advan, Mito

**Comment by dakaizou** [comment]
Crashes when taping on exit in that moment

**Comment by chianger** [comment]
P1 for it's user reproducible crash.

**Comment by mTwTm** [comment]
Simple fix: show ui blocking mask earlier

**Comment by NashTung** [comment]
Work for me.
Video:
https://drive.google.com/open?id=1YXnYB2ruvlGunb2dyd82WRWQBocYdfdg

Device: Advan i5C
Rocket: 2.0.0(4168).nightly
Android: 5.1
Android Webview: 51.0.2704.81

**Comment by cynthiatang** [comment]
Hi @NashTung 
Could you please try the second commend "Crashes when taping on exit at that moment" and provide the result? Thanks

**Comment by mTwTm** [comment]
@cynthiatang I think this is not possible anymore since from 1.0 -> 2.0 we've moved screenshot button from layer 2 (inside menu) to layer 1 so the original STR is sort of invalid now.

**Comment by cynthiatang** [comment]
@mTwTm, thanks for your answer. I would like to close this issue. :)
