### ISSUE TITLE
Can't load anything, empty webview.

### ISSUE THREAD

**Issue by WeiWW** [mozilla-tw/Rocket#1121]
STR:
1.When open too much apps and pause then in background.
2.Open rocket, can't load anything even on about page. It's a blank webview.
3.Close all apps in the background, then open rocket again, it is normal.

Device: Sony Xperia
Build:1456
*It's hard to reproduce.

**Comment by dakaizou** [comment]
Another MTBF device had this bug too, but there were only less than 10 apps in background.
We'll check the devices tomorrow.

**Comment by chianger** [comment]
P2 for tracking

**Comment by dakaizou** [comment]
Happened again on one out of six MTBF devices

**Comment by mTwTm** [comment]
@dakaizou can you dump the MTBF logs when this happen again? It sounds like a webview bug and I'd like to see if anything could be done.

**Comment by dakaizou** [comment]
[Here](https://drive.google.com/open?id=0B0uVZlaHN366MW93TlM5eUs3QWc) is the MTBF logs.
This happened on XB2 and XBC

**Comment by mTwTm** [comment]
May I also have the time when that happens? (Also, are the logs synched in Taipei time?) Let's try the next incident if we didn't already have these.

**Comment by dakaizou** [comment]
@mTwTm I don't know when it happened, but since the history will stop recording anything, I guess we can get the time with the last recorded history? And it's synced in Taipei time

**Comment by mTwTm** [comment]
Haven't have much findings yet, but on device #XG2, from the Download history 
it is certain that the symptom begins after 10.19 08:24:
![device-2017-10-19-184554](https://user-images.githubusercontent.com/6755074/31767491-e1ca0bd4-b4fd-11e7-9eab-00b2272267be.png)
![device-2017-10-19-184604](https://user-images.githubusercontent.com/6755074/31767493-e1fcfb2a-b4fd-11e7-9d36-9ccfdfe9daec.png)

the last few items in history tells the same story, with the last url intent sent at 08:53:46.337 :

![device-2017-10-19-184635](https://user-images.githubusercontent.com/6755074/31767494-e2229420-b4fd-11e7-8c1d-07733a3c3d9f.png)

**Comment by mTwTm** [comment]
![device-2017-10-19-185558](https://user-images.githubusercontent.com/6755074/31767814-346af60e-b4ff-11e7-84e7-acfd3f8c3f05.png)
Top site at the moment, suggesting the last visit may actually come from top site so the symptom starts around 08:24

**Comment by mTwTm** [comment]
Nothing particularly fishy found between 08:23 - 08:25

**Comment by dakaizou** [comment]
MTBF [reports](https://drive.google.com/open?id=0B0uVZlaHN366X2xwdWZoTzEzcW8) yesterday
#### Happened on
N0X: 1456
XYE: 1585
WZF: 1585
XBC: 1585

#### Not happened on
XG2: 1456
MYT: 1585

**Comment by mTwTm** [comment]
Is it happening on an older version? It would be helpful if we can find the regression window.

**Comment by dakaizou** [comment]
I would've noticed that, so I don't think it did. At least not that frequent.

**Comment by dakaizou** [comment]
Build 1641 seems working fine

**Comment by chianger** [comment]
Not seeing this for a period of time.
