### ISSUE TITLE
[Smoke Test] Download triggers screenshot onboarding if moved to sdcard and last entry is screenshot

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1133]
STR:
1. Clear data or reinstall rocket
2. Grant storage permission (download any picture)
3. Tap on system Home
4. Tap on system screenshot
5. Go back to rocket
6. Download any picture

Build: 1541
DuT: Samsung

**Comment by dakaizou** [comment]
related to #247

**Comment by mTwTm** [comment]
In the STR I can't see when the screensho hint pops up, after step 6?
I tried the whole STR and failed to see the hint, is this 100% reproducable?

**Comment by dakaizou** [comment]
It's weird. Sometimes the hint pops up after step 2, sometimes after steps 6. It's pretty frequent though. I'd say the reproduce rate is over 80%

**Comment by dakaizou** [comment]
[Recording](https://drive.google.com/file/d/0B0uVZlaHN366MldRN0J4NUJxUWc/view?usp=sharing) here

**Comment by mTwTm** [comment]
Ah with the new recording I guess I know what's happening. We're sorting with the added date so if the added date of the screenshot is greater then the downloaded one false alarm is fired. This sounds like a system bug for particular device but I guess we can work around this by sorting by ID.

**Comment by dakaizou** [comment]
So I assume the hint pops up after step 6 is expected? 
[Recording](https://drive.google.com/file/d/0B0uVZlaHN366bHdTSlhDMVNRcHc/view?usp=sharing)

**Comment by mTwTm** [comment]
It sounds pretty random on Samsung, let's see if my latest patch fixes this.

**Comment by mTwTm** [comment]
STR:

1. Take a Screenshot (Not necessary in Rocket) without triggering onboarding
2. Download item in rocket with move to sdcard enabled
3. See Screenshot onboarding
4. Expected: nothing

**Comment by mTwTm** [comment]
Some random log of what's happening log the last 5 records everytime a onChange event fires:

10-18 19:10:13.019 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: ========
10-18 19:10:13.020 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1572 | 1508324925|1508324928 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-08-44-693_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.021 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1554 | 1508324734|1508324247 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/photo.jpg
10-18 19:10:13.021 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1569 | 1508324412|1508324415 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-00-11-918_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.021 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1567 | 1508324323|1508324323 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/7-photo.jpg
10-18 19:10:13.021 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1565 | 1508324312|1508324312 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/6-photo.jpg
10-18 19:10:13.145 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: ========
10-18 19:10:13.145 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1573 | 1508325012|1508325013 | /storage/emulated/0/Download/photo.jpg
10-18 19:10:13.145 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1572 | 1508324925|1508324928 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-08-44-693_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.145 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1554 | 1508324734|1508324247 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/photo.jpg
10-18 19:10:13.145 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1569 | 1508324412|1508324415 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-00-11-918_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.145 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1567 | 1508324323|1508324323 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/7-photo.jpg
10-18 19:10:13.519 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: ========
10-18 19:10:13.519 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1573 | 1508325012|1508325013 | /storage/emulated/0/Download/photo.jpg
10-18 19:10:13.519 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1572 | 1508324925|1508324928 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-08-44-693_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.520 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1554 | 1508324734|1508324247 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/photo.jpg
10-18 19:10:13.520 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1569 | 1508324412|1508324415 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-00-11-918_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.520 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1567 | 1508324323|1508324323 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/7-photo.jpg
10-18 19:10:13.535 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: ========
10-18 19:10:13.535 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1572 | 1508324925|1508324928 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-08-44-693_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.536 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1554 | 1508324734|1508324247 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/photo.jpg
10-18 19:10:13.536 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1569 | 1508324412|1508324415 | /storage/emulated/0/DCIM/Screenshots/Screenshot_2017-10-18-19-00-11-918_org.mozilla.rocket.debug.tyu.png
10-18 19:10:13.536 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1567 | 1508324323|1508324323 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/7-photo.jpg
10-18 19:10:13.536 25912-26104/org.mozilla.rocket.debug.tyu E/mTwTm: 1565 | 1508324312|1508324312 | /storage/9016-4EF8/Android/media/org.mozilla.rocket.debug.tyu/downloads/pictures/6-photo.jpg

**Comment by dakaizou** [comment]
verified in build 1551
