### ISSUE TITLE
App thumbnail in background after tapping exit button stays in website

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1135]
STR:
1. Visit any page
2. Tap on exit button
3. Tap on system list to check running app

Note: not sure if this is expected.

Build: 1541
DuT: Oppo

**Comment by chianger** [comment]
UC Browser and Opera both work similarly.

**Comment by chianger** [comment]
Having the thumbnail in the background task switcher doens't mean the system has the app still running.

**Comment by chianger** [comment]
WON'T FIX
