### ISSUE TITLE
Opening deleted screenshot will also show the buffering circle

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1138]
STR:
1. Take a screenshot
2. Delete the screenshot from outside rocket
3. Open the screenshot in screenshot viewer

![Screenshot](https://lh3.googleusercontent.com/-z5ZsqfvHRII/WecN77JH8lI/AAAAAAAABos/7Ae2l_z4DtUFKzW5Gw3C4bdyNTddMaxjwCL0BGAYYCw/h1280/770926733117228549%253Faccount_id%253D2)

Build: 1541
DuT: Redmi

**Comment by mTwTm** [comment]
Put into Sprint 13 since that is the last sprint.
