### ISSUE TITLE
"Open with..." in Focus does not show Rocket when user has default browser

### ISSUE THREAD

**Issue by mcomella** [mozilla-tw/Rocket#1149]
STR
1) Open a page in focus
2) 3-dot menu -> open with...

Expected: Rocket is shown
Actual: Rocket is not shown

I assume we're using a generic browser intent in Focus so I think Rocket may not be correctly receiving browser intents. If I'm incorrect, feel free to file this against Focus. :)

I'm using the Focus Beta and the Rocket Beta from google play with automatic updates so they should be fairly up to date.

Some code references:
- [Clicked on "Open with..." menu item](https://github.com/mozilla-mobile/focus-android/blob/b10f55f18c6ad959d43efec81c1b9c9c14d725d1/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L826)
- [Where we get the installed browsers](https://github.com/mozilla-mobile/focus-android/blob/e528e0fa90f74a1388984d89627d5cdfeea0d914/app/src/main/java/org/mozilla/focus/utils/Browsers.java#L105)

**Comment by chianger** [comment]
Seems non reproducible from our testing. Keep tracking this in P2.

**Comment by mcomella** [comment]
Perhaps my build is not up-to-date? I'm using Rocket 0.9.1585, according to About.

**Comment by mTwTm** [comment]
0.9.1585 is the version that Joe is checking already, I guess there should be something to do with default browser settings (My guess: we won't show correctly when focus is default or when Rocket is not default, while on Joe's device Rocket is default) I'll check this when I am available.

**Comment by mTwTm** [comment]
With a clean install of Focus/FocusWebViewDebug and Rocket/FocusWebViewDebug, I cannot reproduce this issue.

**Comment by mTwTm** [comment]
Can't reproduce with 2.2(Build 12861529) and Rocket latest build, too.

**Comment by mTwTm** [comment]
There you go, when focus is default browser, I can reproduce this.

**Comment by mTwTm** [comment]
It's a known Focus limitation so it's won't fix here. I'll find a proper issue to raise this in focus-android

**Comment by mTwTm** [comment]
Didn't find an existing bug to raise this. At second thought, I'll check with @joechengla if we want to be recognized by Focus.

Here's the brief:

1. If no default browser is set, we can easily identify all browsers that can handle this open intent.
2. However, when a default browser is set, this does not work anymore, Focus try to send intent to all those `known browsers` which is hardcoded to try find if these exist on user's environment. Firefox Rocket is not listed (yet) in this hardcoded `known browsers`.

**Comment by joechengla** [comment]
why not? Rocket should be recognized by any browser right?

**Comment by mTwTm** [comment]
Oh this would be a `Focus` bug, it's about if we want to add `Rocket` into the `Known Browsers` list of `Focus`.

**Comment by mcomella** [comment]
> Oh this would be a Focus bug, it's about if we want to add Rocket into the Known Browsers list of Focus.

I filed https://github.com/mozilla-mobile/focus-android/issues/1656 against Focus. Thanks for the research and sorry it ended up being a Focus issue!
