### ISSUE TITLE
Consider removing Detik again

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1165]

**Comment by joechengla** [comment]
please wait for my further investigation

**Comment by chianger** [comment]
@Ben-YPLai please wait a bit until @joechengla confirms we'll replace this top site.

**Comment by joechengla** [comment]
please remove detik

**Comment by joechengla** [comment]
latest list, in order 
https://m.youtube.com/
http://m.tribunnews.com/
https://m.tokopedia.com/
https://m.facebook.com/
https://m.bukalapak.com/
http://m.liputan6.com/
http://www.kompas.com/
https://m.merdeka.com/
