### ISSUE TITLE
[Smoke Test] Instagram OAuth redirection failed

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1173]
STR:
1. Clear data
2. Visit [instagram.com](https://www.instagram.com)
3. Log in with facebook

Note: The authentication itself did work, only redirection failed. Re-enter the instagram.com in url to check.
related to #120, #841 

Build: 1593
DuT: Samsung

**Comment by dakaizou** [comment]
Also failed on [udemy.com](https://www.udemy.com) with Google

**Comment by walkingice** [comment]
I gave some test on Lightning browser. If we turn off multi-tab in Lightning, oauth login on Instagram won't work. It only work if we turn on multi-tab.

**Comment by chianger** [comment]
so it's a limitation for now.
action item: 
1. run web compatibility to check ID top sites and revisit again.
2. consider adding SUMO support article

**Comment by chianger** [comment]
nothing we can do at this moment as it requires multi-tab.
ran top100 sites and didn't see relevant issues so i'm putting this to P2.

**Comment by chianger** [comment]
before we have multi-tab feature, there should be a workaround specifically for instagram.com

**Comment by cynthiatang** [comment]
It works for me. The behavior is the same as Lightning browser now. 

Devices: Pixel2
