### ISSUE TITLE
[Smoke Test] Rocket crashes when open downloaded image from google search

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1174]
STR:
1. Download a picture follow #677  (The picture should be named as "image.jpg")
2. Open Downloads panel
3. Tap on the downloaded picture

Build: 1626
DuT: Samsung

**Comment by mTwTm** [comment]
Not happening on my Sony XA 7.0 Is it. Might have something to do with the SDcard

**Comment by chianger** [comment]
@dakaizou  can you dump adblog?

**Comment by dakaizou** [comment]
@mTwTm @chianger [crash_log](https://drive.google.com/file/d/0B0uVZlaHN366YmowaHRXYkZnbEU/view?usp=sharing) here

**Comment by mTwTm** [comment]
Confirmed dut is with sdcard

**Comment by dakaizou** [comment]
Working fine after removing sdcard

**Comment by mTwTm** [comment]
Fixed in #1178
