### ISSUE TITLE
[Smoke Test] Rocket crashes when undoing deleting the only downloaded file

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#1179]
STR:
1. Clear data
2. Download one file
3. Delete file from Rocket's Downloads panel
4. Tap on Undo

Build: 1641
DuT: Samsung, Oppo

**Comment by mTwTm** [comment]
Regression windows: 0.9 is affected.

**Comment by mTwTm** [comment]
Regression windows: 0.8 not affected.

**Comment by chianger** [comment]
NOT affected on 0.8.1455
Affected on 0.9.1585

**Comment by chianger** [comment]
does #1183 get this fixed?

**Comment by chianger** [comment]
per discussion this was fixed by #1183 so I'm closing this and let QA verify.
