### ISSUE TITLE
Media playback in full screen should avoid system from going to sleep mode

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#1188]
STR:
1. Go to youtube.com and begin to play a video
2. Make it full screen
3. Watch the video play until system sleeps

Actual result:
media playback stops and get black screen
Expected result:
media playback should go on

Affected on Android 8/7/6/5

**Comment by chianger** [comment]
somehow only Mito keeps the media playback going.

**Comment by chianger** [comment]
opera works fine.

**Comment by mTwTm** [comment]
I would actually expect media playback stops and get black screen, for the good sake of battery. We have a health check on Google Play reports for not leaving the system continue to drain battery after screen off. I've tested some behaviors on Rocket current findings suggest all videos (not youtube only) will suspend after screen off while audio lasts.

**Comment by chianger** [comment]
Chrome, Opera, Fennec all keep the playback going.

**Comment by joechengla** [comment]
What about other mini browsers? Keep playback going is the expected UX

**Comment by joechengla** [comment]
What does it take to fix it for release?
How big is the change and the associated risks?
Thanks
