### ISSUE TITLE
Won't see refresh button on the menu when back to previous site without showing loading bar

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#1192]
Reproduce,
1. Go to Mozilla.org page from Home
2. Press home button on the bottom bar then open Home
3. Press system back key to back to Mozilla.org page (but there is no loading bar when back to Mozilla.org)

Expected,
Refresh button will be on the menu instead of X button

Actual,
X button is on the menu and will not be changed to Refresh button

**Comment by chianger** [comment]
triage: non-blocking so P2.

**Comment by mTwTm** [comment]
For some reason, this only happens when we browse via url bar, but not happening when we click top-site, interesting.

**Comment by mTwTm** [comment]
This is back since we've backed out the patch

**Comment by chianger** [comment]
I believe #1432 fixed this?

**Comment by cynthiatang** [comment]
Hi @idiotmax ,
I just verified this issue. It works. Thank you :) . 

Samsung J7
Rocket: 1.0.4 (2109).nightly
Android: 7.0
WebView: 64.0.3282.137
