### ISSUE TITLE
merdeka icon doesn't look right

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1196]

**Comment by carol-mozilla** [comment]
@joechengla do you have the screenshot for the issue?

**Comment by chianger** [comment]
![screenshot_20171101-100151](https://user-images.githubusercontent.com/9859809/32257148-605eb23e-beee-11e7-9129-42649a86d793.png)

**Comment by chianger** [comment]
YouTube icon here on the screen is not ideal as well.

**Comment by chianger** [comment]
confirmed fixed by replacing with kapalangi.com
