### ISSUE TITLE
Difficult to scroll video progress bar and sometimes lag while dragging progress bar

### ISSUE THREAD

**Issue by vanceyen** [mozilla-tw/Rocket#1214]
STR :
1. Connect to vidio.com
2. Play a video
3. Drag progress bar during playback

Expected:
    The response is sensitive enough
Actual:
    No response (maybe not scroll successfully) or the response sometimes has a ~1 sec delay

HW model: SAMSUNG J610F
Build : 1.0 - 1692

**Comment by chianger** [comment]
Chrome has the same issue so it's likely the website issue. WONTFIX
