### ISSUE TITLE
Type in “blogspot.co.id” doesn’t take me to the website directly

### ISSUE THREAD

**Issue by vanceyen** [mozilla-tw/Rocket#1215]
STR:

1. Tap on "Search" button
2. On the search bar, type in “blogspot.co.id”, and then tap ->

Expected result:
    Rocket will take me to blogpost.co.id.

Actual result:
   Rocket take me to Google

Chrome has the same issue

DUT:Pixel XL
Build: 1.0 - 1692

**Comment by chianger** [comment]
WON'T_FIX as it's likely the website's issue.
