### ISSUE TITLE
sometimes rocket will not show loading bar when it has started loading

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1232]

**Comment by chianger** [comment]
Chrome shows at least some progress to improve "perceived" performance.

**Comment by chianger** [comment]
can reproduce using m.tokopedia.com pretty easily

**Comment by chianger** [comment]
It's not really fixed. The progress bar sometimes gets stuck at 10% and never finishes.

**Comment by chianger** [comment]
it's a critical bug that we need to take care of immediately.

**Comment by chianger** [comment]
#1192 also happens stills
