### ISSUE TITLE
Remove button should not be in the upper-left corner

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1250]
Step:
 1. Launch Rocket
 2. Touch and hold any top site to bring up "Remove" button 
 3. Tap Android's Home Key
 4. Go back to Rocket

Actual Result:
 - The Remove button is in the upper-left corner
 - Video: https://youtu.be/BLLXkOj9PUk
 - This issue can be reproduced on Redmi 4A and Sony Z3C.
 - This issue cannot be reproduced on Google Pixel.

Expected Result:
 - The Remove button is not in the upper-left corner

Reproduction rate: 10/10
Rocket version:  1.0.1710

======================================
Device name: Redmi 4A
Android version: 6.0.1 MMB29M

Device name: Sony Z3C
Android version: 5.0.2 MMB29M

**Comment by mTwTm** [comment]
Dupicate to #368, I'll copy-paste the very informative descriptions.
