### ISSUE TITLE
handle situations where one or many permissions have been denied by the user

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1260]
The app must be prepared to handle situations where one or many permissions have been denied by the user. Educate the user on why the permission is needed and allow the user to trigger the prompt again either immediately or when they have the related action.  
For more info:
https://material.io/guidelines/patterns/permissions.html#permissions-denied-permissions

**Comment by Jacklin-ux** [comment]
Please refer to the UX spec (Use case from 6-1~6-3-1)
https://drive.google.com/open?id=1936ixcg6RqUyHp3_Ixcpf2iKjxKc_lon

I have used PDF editor to comment the updated pages, please let me know if any questions.
Thanks

**Comment by Jacklin-ux** [comment]
Michelle has reviewed all the strings of permissions. I have updated the spec, and the link as below,
https://drive.google.com/a/mozilla.com/file/d/1P51dOgzKSvNh1okGpG3hU5gv_0kdov9I/view?usp=sharing

Please use PDF editor to see the comments and the updated strings.
Thanks.

**Comment by Jacklin-ux** [comment]
Have discussed with Joe, the refined strings are as below,

(For Location permission)
Location not available. Give permission to access your location.

(For Storage permission)
Storage not available. Give permission to store photos and files on your device.

Currently, we are waiting for copy review by Michelle.

**Comment by mTwTm** [comment]
Close this issue in favor of #1365
