### ISSUE TITLE
In the event of a user selecting “Don’t ask again” for a permission tied to a particular function, the app should let the user know why they cannot proceed with the desired function

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1261]
- In the event of a user selecting “Don’t ask again” for a permission tied to a particular function, the app should let the user know why they cannot proceed with the desired function. Instruct the user on what actions they must take to re-enable the desired function (e.g direct user to app settings and what to do at the app settings view).  
For more info: https://material.io/guidelines/patterns/permissions.html#permissions-denied-permissions

**Comment by Jacklin-ux** [comment]
Please refer to the UX spec (Use case from 6-1~6-3-1)
https://drive.google.com/open?id=1936ixcg6RqUyHp3_Ixcpf2iKjxKc_lon

I have used PDF editor to comment the updated pages, please let me know if any questions.
Thanks

**Comment by Jacklin-ux** [comment]
Michelle has reviewed all the strings of permissions. I have updated the spec, and the link as below,
https://drive.google.com/a/mozilla.com/file/d/1P51dOgzKSvNh1okGpG3hU5gv_0kdov9I/view?usp=sharing

Please use PDF editor to see the comments and the updated strings.
Thanks.
