### ISSUE TITLE
Always shows a popup window "https://www.google.com.tw wants to use your device's location" when enter "taipei 101" in search bar

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1262]
STR:
 1. Launch Rocket
 2. Enter "taipei 101" in search field 
 3. Wait for 3 seconds
 4. Tap search button to close the popup window
 5. Tap search button again

Rocket’s Result:
 - After step3, it always shows a popup window "https://www.google.com.tw wants to use your device's location"
 - After step4, user can close the popup window
 - After step5, it always shows a popup window
 - Video: https://youtu.be/St6-I12cBCw

Chrome’s Result:
 - After step5, it won't show a popup window again

Reproduction rate: 10/10
Rocket version: 1.0.1 Build 1777  
Device name: Sony Z3C 
Android version: 5.0.2

**Comment by weslyhuang** [comment]
dup to #1654
