### ISSUE TITLE
"anysoft keyboard" not working well with URL/Search input field 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1267]
Google Play feedback
when entering the web address / searching using the keyboard "anysoft keyboard" better yet because I can not type correctly when not using the default keyboard. - why if i'm using other keyboards to enter web adress / search something (not using google keyboard, it's not working correctly ?.

**Comment by chianger** [comment]
QAWanted to dig into more details. What's the actual result and expected result in comparison.

**Comment by dakaizou** [comment]
Samsung S7 edge (android 7.0) with AnySoftKeyboard 1.8.1333
Redmi 4A (android 6.0) with AnySoftKeyboard 1.8.1333
Both working fine

**Comment by chianger** [comment]
Per above comment it's non-reproducible.
