### ISSUE TITLE
backout #1254 which fixed #1192 but seems introducing #1064

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#1286]

**Comment by mTwTm** [comment]
Per QA's test it's not happening on Android 5.0.2? Interesting.

**Comment by cynthiatang** [comment]
Hi Joe, Max and Teng-Pao,  
Thanks for your help. I would like to update some information here. Then QA can verify bugs. 

This issue can not be reproduced on:
    Sony Z3C    Android 5.0.x   Webview 62.xxxxx
    Redmi          Android 6.0.x   Webview 62.xxxxx  

This issue can be reproduced on: 
    Sony Z3C    Android 5.0.x   Webview 63.xxxxx
    Sony Z3C    Android 6.0.x   Webview 63.xxxxx   
    Pixel             Android 7.0.x   Webview 63.xxxxx
