### ISSUE TITLE
Failed to visit https://bukalapak.com (Top 10)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1301]
STR:
1. Close Rocket
2. Launch Rocket
3. Tap "bukalapak"

Expected Result:
 - User can visit the website

Actual Result:
 - Sony Z3C and Nexus5 (Android 6.0 *WebView 63)
     - Url bar: bukalapak://www.bukalapak.com/?link_click_id=479200499199747083
    - Error page: The address wasn't understood
    - Note: This issue cannot be reproduced on the same device with Build 1792 

 - Sony Z3C (Android 5.0.2*WebView 63)
    - Url bar: https://m.bukalapak.com/ 
    - Error page: The address wasn't understood

**Comment by chianger** [comment]
triage: S1 as it's user facing regression. top site.

**Comment by joechengla** [comment]
seem like site behavior changed and it works now

**Comment by chianger** [comment]
This is relevant to not being able to handle the specific app link.
UX suggestion: don't redirect. And Rocket is not going to show any toast message given it's not much helpful.

**Comment by chianger** [comment]
@idiotmax seems like https://github.com/mozilla-tw/Rocket/pull/1440 can handle this but per discussion with UX let's skip the 'toast' or any sort of messages.

**Comment by chianger** [comment]
#1548 #1549 fixed this issue. 
Ready to be verified.

**Comment by cynthiatang** [comment]
Verified: Fixed.
Thanks. :)

Device: Redmi Note4
Rocket nightly: 1.1 (2949).debug.bitrise
Android version: 7.0
WebView version 65.0.3325.109
