### ISSUE TITLE
Not registered on Advan i5C text search tool

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#1304]
This is related to test case navi_012. Be noted that this is a device-specific issue. Advan i5C has a customized sub menu. We might not be included on the list for some reasons.

STR

1. Launch Zerda and visit a website with contexts
2. Long press on texts
3. Tap on sub menu

Expected Result

2. A popup menu is displayed with following options
  - Copy
  - Share
  - Select All
3. A pop up menu is displayed with following options
  - Back
  - Private search (there might be some other options. it depends on the browsers/apps on the device)

Actual Result

3. We are not on the private search list

Advan i5C
Android 5.1
WebView 62
Build 1803

**Comment by Conjuror** [comment]
![Uploading Screenshot_2018-01-10-14-42-41.png…](Customized submenu)

![Uploading Screenshot_2018-01-10-14-42-50.png…](Browsers on the list w/o Rocket)

**Comment by Conjuror** [comment]
![screenshot_customized submenu](https://user-images.githubusercontent.com/1625148/34759104-f0d6ce20-f614-11e7-8353-40acadf6d548.png)
![screenshot_search_engine_w/o_rocket](https://user-images.githubusercontent.com/1625148/34759129-063c300c-f615-11e7-87fc-79b2d45f991a.png)

**Comment by mTwTm** [comment]
Possible duplicate to #807 ?

**Comment by Conjuror** [comment]
exactly. Closed as dup.
