### ISSUE TITLE
Permission - Back key doesn't work when there is a popup window "Allow Firefox Rocket to access this device's location" 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1316]
Prerequisite
 1. Location Permission in system is Disabled
 2. First time to use the location permission

STR:
 1. Launch Rocket
 2. Navigate to youtube.com
 3. Navigate to maps.google.com
 4. Tap system Back key 

Expected result:
 - Back to the previous page

Actual result: 
 - Back key doesn't work

Device: Sony Z3C 
Rocket nightly: 1834
Android version: 6.0.1
WebView version: 63.0.3239

**Comment by mTwTm** [comment]
It's a system popup which works that way by design :)

**Comment by cynthiatang** [comment]
Hi~ we should have a meeting tomorrow. I would like to know the expected results. For example,
 Case 1: System popup > Tap Home -> Tap Rocket from Home screen
 Case 2: System popup > Switch to other app -> Switch to Rocket again 
 Case 3: System popup > Tap DENY or other area out of the popup window
 Case 4: System popup > Tap DENY -> Tap menu -> Tap Reload page button
 Case 5: System popup > Tap DENY -> Switch to other app -> Switch to Rocket again 
 Case 6: System popup > Tap DENY -> Tap Circle icon in the webpage to update your location
Thanks :)

**Comment by mTwTm** [comment]
The basic rule is: System dialog is not cancelble but if the App/(Activity to be exact) got killed it should act as nothing happens.

**Comment by cynthiatang** [comment]
Jack and I just discussed this top. We will follow the system behaviour. So it's work for me now. Thanks.
