### ISSUE TITLE
Permission - The popup window "Allow Firefox Rocket to access this device's location" disappeared after tapping Home and opening Rocket from Home screen 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1319]
Prerequisite
 1. Location Permission in system is Disabled
 2. First time to use the location permission

STR:
 1. Add Rocket to Home screen
 2. Launch Rocket
 3. Navigate to maps.google.com
 4. Tap Home key
 5. Tap Rocket from Home screen 

Expected result:
 - There is a popup window "Allow Firefox Rocket to access this device's location"

Actual result: 
 - The popup window disappeared
 - It will not disappear any more. It means Never ask again
 - Video: https://goo.gl/etz9S8 
   ( Please use Firefox browser if you cannot play the video via Chrome.)  

Device: Nexus 5
Rocket nightly: 1834
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by mTwTm** [comment]
Propose S2 (But I'll work on it now.)
