### ISSUE TITLE
Permission - In order to close to popup window, user have to tap BLOCK three times

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1323]
Prerequisite
 1. Location Permission in system is Disabled
 2. First time to use the location permission

STR:
 1. Add Rocket to Home screen
 2. Launch Rocket
 3. Navigate to maps.google.com
 4. Tap ALLOW
 5. Tap System Home key
 6. Tap Rocket from Home screen
 7. Tap BLOCK  

Expected result:
 - User can tap BLOCK to close the popup window

Actual result: 
 - In order to close to popup window, user have to tap BLOCK three times.
 - Video: https://goo.gl/cFG3WB

Device: Nexus 5
Rocket nightly: 1834
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by cynthiatang** [comment]
Actual result on Nexus 5 with Rocket 1.0.2: 
 - In order to close to popup window, user have to tap BLOCK 2 times, not 3 times
 - Video: https://drive.google.com/open?id=1sYvRxTFT8H9hZSvMYqLegFmvnJnfiud_

Device: Nexus 5
Rocket nightly: 1816
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by chianger** [comment]
With Pixel XL, I can reproduce on Rocket 1.0.2. 
If you repeat doing "tap system home" --> "tap Rocket icon to Rocket" --> "tap system home" -->...
you'll get more popup dialogs.

**Comment by chianger** [comment]
not a regression, non-blocking.

**Comment by mTwTm** [comment]
Fixes in #1333
