### ISSUE TITLE
Customized feature request: Change the background theme of Firefox Rocket

### ISSUE THREAD

**Issue by annie101101046** [mozilla-tw/Rocket#1327]
It would be nice to add more customized features like changing the background color of Firefox Rocket.

**Comment by carol-mozilla** [comment]
Here's the spec and asset: https://drive.google.com/open?id=1vAzGI1d-7ujjnIAYzv_gM7O3lV8qDFnu

**Comment by carol-mozilla** [comment]
Please update the color for the tab tray background too! thank you!!

**Comment by mTwTm** [comment]
Fixed in #2069
