### ISSUE TITLE
Permission - should not flicker the popup window after tapping ALLOW to access the device location

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1330]
Prerequisite
 1. Location Permission in system is Disabled
 2. First time to use the storage permission

STR:
 1. Launch Rocket
 2. Navigate to https://permisssion.site
 3. Tap Location
 4. Tap ALLOW

Expected result:
 - A popup window appears. Rocket should not flicker the popup window

Actual result: 
 - Rocket flickered the popup window
 - Video: https://goo.gl/mH3Wh4

Device: Nexus 5
Rocket nightly: 1853
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by mTwTm** [comment]
I can reproduce this

**Comment by cynthiatang** [comment]
This issue only happened when user use location permission first time or reset the permission. 
But it cannot reproduced on Rocket 1.0.2 (1816). 

Device: Nexus 5
Rocket nightly: 1816
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by chianger** [comment]
Happened before in older versions per several people's memory. 
This should not block after discussed with the team.

**Comment by cynthiatang** [comment]
Hi Teng-Pao, 
Thanks for your help to fix this issue. It works now. 

Verified on 
Device: Nexus 5
Rocket nightly: 1915
Android version: 6.0.1
WebView version: 63.0.3239.1111
