### ISSUE TITLE
Image viewing permission didn't be disabled on Redmi

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#1351]
Prerequisite
 1. Download an image with Rocket
2. Turn off storage permission for Rocket

STR:
 1. Launch Rocket
 2. Tap Menu -> Download
 3. Tap on the downloaded image
 
Expected result:
 - Cannot view the image and ask for permission

Actual result: 
 - Image is still viewable
 - Video: https://drive.google.com/open?id=1GlYSgxEwDn1RAUTWfGinegvfYpu-Tyej

Device: Redmi
Rocket 1.0.3rc: 1895
Android version: 6.0.1
WebView version: 63.0.3239.111/64.0.3282.116

**Comment by Jacklin-ux** [comment]
Hi, in the video, the image viewer's (View photos) Storage permission is still enabled, so users can open and view the image. I think it's Android behavior.

Please let me know if I am wrong, thank you :)

**Comment by mTwTm** [comment]
That's what I guessed too, I'll try to confirm tomorrow.

**Comment by mTwTm** [comment]
Confirmed this is a bug, but from my point of view should be described reversely.

To comply with Android 8 policies, #1081 is merged and with that we will need storage permission to pass other apps file. Maybe we should try to work around that and be able to pass others the file.

**Comment by chianger** [comment]
On Pixel XL (android 8) it's also buggy but with a different symptom.
When storage permission gets turned off, user is still allowed to bring up photo viewer by tapping on the item from "download panel". The viewer isn't actually able to display the picture, but only the waiting cursor.

**Comment by chianger** [comment]
Triage: going to setting and turn off storage permission is consider "3rd level menu or beyond" so S2.

**Comment by cynthiatang** [comment]
Hi mTwTmT,
This bug should be closed, right? As our discussed, the actual result is correct on Android 6 and Android 7. RedMi's OS is Android 6. And we should create another bug for Android 8, right? 

Expected result on Android 6 and Android 7: 
 - Image is still viewable

**Comment by mTwTm** [comment]
I should have made this clear earlier, sorry!
I've discussed this with Max and he believe we can simply treat this as:
8 is the expected behavior of Android design while in 7 and 6 there were some deprecated design / bug.

I'll close this bug and file another bug to apply Jack's solution.

**Comment by cynthiatang** [comment]
Hi Al,
Could please revise the test case to apply Jack's solution? Thanks. :)
