### ISSUE TITLE
Permission - The popup window "Allow Firefox Rocket to access this device's location" and Snack Bar disappeared after tapping Home and opening Rocket from Home screen

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1352]
Prerequisite
 1. Location Permission in system is Disabled
 2. First time to use the location permission

STR:
 1. Add Rocket to Home screen
 2. Launch Rocket
 3. Navigate to maps.google.com
 4. Tap Home key
 5. Tap Rocket from Home screen 

Expected result:
 - There is a popup window "Allow Firefox Rocket to access this device's location"

Actual result: 
 - The popup window disappeared
 - It will not disappear any more. It means Never ask again
 - The snack bar also disappeared anymore. 
 - Note: 
     - If user close Rocket -> relaunch Rocket, it works again
     - But it will disappear if user repeat step3 -step4
 - Video: https://goo.gl/rwQVkx 
   ( Please use Firefox browser if you cannot play the video via Chrome.)  

Device: Nexus 5
Rocket nightly: 1895
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by cynthiatang** [comment]
Similar bug is https://github.com/mozilla-tw/Rocket/issues/1319

**Comment by mTwTm** [comment]
It's intended. The webpage is totally reloaded and this should happen.

**Comment by mTwTm** [comment]
Oh I misunderstood the problem, I'll check now.

**Comment by mTwTm** [comment]
Severity:
1. It only happens when user cancel this dialog via this Home trick
2. It will be recovered after the Activity is closed.

**Comment by mTwTm** [comment]
Fixed in #1353
