### ISSUE TITLE
cannot trigger system location request again, if I accidentially deny for once the first time (not always deny)

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1356]
1. goto Google Maps
2. Deny system location permission request once (not always)
3. tap "locate" button on Google maps
4. only see snackbar from Rocket about location not given

expected result:
Rocket will trigger system location permission request

**Comment by cynthiatang** [comment]
Verified - Fixed 

Device: Nexus5 
Rocket version: 1915
Android version:  6.0.1 
WebView Version: 64.0.3282.116
