### ISSUE TITLE
Permission - System storage-permission dialog disappeared after tapping Home and opening Rocket from Home screen

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1360]
Prerequisite
 1. Storage Permission in system is Disabled
 2. First time to use the Storage permission

STR:
 1. Add Rocket to Home screen
 2. Launch Rocket
 3. Navigate to xcal1.vodafone.co.uk
 4. Tap Home key
 5. Tap Rocket from Home screen 

Expected result:
 - System storage-permission dialog saying "Allow Firefox Rocket to access photos, media, and files on your device" should be displayed

Actual result: 
 - System storage-permission dialog disappeared 
 - Video: https://goo.gl/Gif8yy
   ( Please use Firefox browser if you cannot play the video via Chrome.)  

Device: Nexus 5
Rocket nightly: 1915
Android version: 6.0.1
WebView version: 63.0.3239.1111

**Comment by mTwTm** [comment]
This is aligning the expected behavior after #1066 though we did not particularly did anything to enable this. Let's have UX to confirm and if we don't want this we can try to change it. (Not sure if it is possible, though)

**Comment by mTwTm** [comment]
I'd also like to add that this will happen if you Tap Rocket from Home screen but will not happen if you switch via task bar.

**Comment by cynthiatang** [comment]
Thanks for your information. It works for me now. I will revise this test case. :)

**Comment by Jacklin-ux** [comment]
My expected behavior is no matter users do switching apps from task manager or tapping Rocket from Home, the permission dialog is still kept and displayed on the screen. But if open Rocket from other apps, the dialog should be closed. 

For this issue, it is fine and acceptable.
