### ISSUE TITLE
Shorter string for permission snackbars

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1365]
Originally in #1260:

Have discussed with Joe, the refined strings are as below,

(For Location permission)
Location not available. Give permission to access your location.

(For Storage permission)
Storage not available. Give permission to store photos and files on your device.

Currently, we are waiting for copy review by Michelle. The deadline I set is next Monday 1/22.

**Comment by Jacklin-ux** [comment]
Done, Michelle has reviewed the strings, so we can use them.
