### ISSUE TITLE
Please remove 中文(中囯) from Language page

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1394]
Please remove 中文（中囯）from Language page. Thank you. :)

![screenshot_20180207-175507](https://user-images.githubusercontent.com/12458450/35911549-1497e156-0c35-11e8-80a7-40e8b1e8ee58.png)

Rocket: 1990

**Comment by chianger** [comment]
P2 as this setting is in deeper level menu.
@mTwTm has fixed in #1395

**Comment by cynthiatang** [comment]
Verified Fixed

Samsung J7
Rocket: 1.0.4 (2109)
Android: 7.0
WebView: 64.0.3282.137
