### ISSUE TITLE
 Wrong string in Give feedback

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1409]
STR:
 1. Launch Rocket
 2. Go to Menu -> Settings -> Give feedback
 
Expected result:
 - Rocket version: 1915 (1.0.3)
![1466682834730251581](https://user-images.githubusercontent.com/12458450/36016006-044d51dc-0dac-11e8-9c03-7cc26606f924.png)

Actual result: 
 - Rocket version: 2920 (nightly)
![5424219168027340997](https://user-images.githubusercontent.com/12458450/36016003-fe5a50b8-0dab-11e8-84c0-045ae0980232.png)

Device: Nexus 5
Android version: 6.0.1
WebView version: 64.0.3282.137

**Comment by mTwTm** [comment]
Possible result of Gradle plugin upgrade (#1303) Propose P1 S1

**Comment by chianger** [comment]
Not happening on v.1.0.3(1990). This is critical and should be P1 so that we won't ship this bug to release.

**Comment by cynthiatang** [comment]
Verified: Fixed.
Thanks. :)

Device: Redmi Note4
Rocket nightly: 1.1 (2949).debug.bitrise
Android version: 7.0
WebView version 65.0.3325.109
