### ISSUE TITLE
Updated Privacy Policy when Firebase is integrated

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1410]

**Comment by joechengla** [comment]
We need to update Privacy Policy in 2 places in settings
- In About page
- Learn More on Send Usage Data

**Comment by chianger** [comment]
corresponding bugzilla issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1449873

**Comment by weslyhuang** [comment]
action on server side update

**Comment by chianger** [comment]
up and running
