### ISSUE TITLE
'Delete' icon on the menu panel need to be update

### ISSUE THREAD

**Issue by carol-mozilla** [mozilla-tw/Rocket#1453]
The trash bin icon, the line weights are different on the sides.

![screenshot_20180301-104516](https://user-images.githubusercontent.com/6700296/36825527-08b91ed0-1d43-11e8-8982-347949fc79a7.png)

New assets: https://drive.google.com/open?id=1UNsB9bKc_Fp-StaGOcY7dMHNB36NLWZT

**Comment by mTwTm** [comment]
Fixed in #1456
