### ISSUE TITLE
Open a link with target _blank doesn't open a link in new tab

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#1471]
You can use the sample of #1307 to reproduce.

Or, use the [link](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_a_target)
The expected result of `<a href="https://www.w3schools.com" target="_blank">Visit W3Schools</a>` is to open a new tab for the link.

Build: 1.0.4(2383)
Device: All devices

**Comment by walkingice** [comment]
This issue should be fixed

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks. :)

Device: Pixel 2
Android: 8.1
Rocket: 2.0.0(3236)
WebView: 65.0.3325.109
