### ISSUE TITLE
HOME -> URL BAR -> new page is not opened in a new tab

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1480]
STR:
1. Tap Home
2. Tap url bar
3. Enter address and tap enter

Expected behavior:
New page opened in new tab

Actual behavior:
New page replaced old page

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks. :)

Device: Pixel 2
Android: 8.1
Rocket: 2.0.0(3236)
WebView: 65.0.3325.109
