### ISSUE TITLE
Crash when enter full screen on YouTube

### ISSUE THREAD

**Issue by idiotmax** [mozilla-tw/Rocket#1486]
03-06 13:51:10.573  5155  5155 W System.err: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
03-06 13:51:10.574  5155  5155 W System.err:    at android.view.ViewGroup.addViewInner(ViewGroup.java:4937)
03-06 13:51:10.575  5155  5155 W System.err:    at android.view.ViewGroup.addView(ViewGroup.java:4768)
03-06 13:51:10.575  5155  5155 W System.err:    at android.view.ViewGroup.addView(ViewGroup.java:4740)
03-06 13:51:10.575  5155  5155 W System.err:    at org.mozilla.focus.fragment.BrowserFragment$TabsContentListener.onEnterFullScreen(BrowserFragment.java:1180)
03-06 13:51:10.575  5155  5155 W System.err:    at org.mozilla.focus.tabs.TabsSession$TabChromeClientImpl.onEnterFullScreen(TabsSession.java:469)
03-06 13:51:10.576  5155  5155 W System.err:    at org.mozilla.focus.webkit.WebkitView$FocusWebChromeClient.onShowCustomView(WebkitView.java:275)
03-06 13:51:10.576  5155  5155 W System.err:    at com.android.webview.chromium.Ap.onShowCustomView(WebViewContentsClientAdapter.java:539)
03-06 13:51:10.576  5155  5155 W System.err:    at org.chromium.android_webview.AwWebContentsDelegateAdapter.toggleFullscreenModeForTab(AwWebContentsDelegateAdapter.java:122)
03-06 13:51:10.576  5155  5155 W System.err:    at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
03-06 13:51:10.577  5155  5155 W System.err:    at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
03-06 13:51:10.577  5155  5155 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
03-06 13:51:10.577  5155  5155 W System.err:    at android.os.Looper.loop(Looper.java:164)
03-06 13:51:10.577  5155  5155 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6494)
03-06 13:51:10.577  5155  5155 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
03-06 13:51:10.578  5155  5155 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-06 13:51:10.578  5155  5155 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks.

Device: Redmi Note4
Rocket nightly: 1.0.4 (3049).nightly
Android version: 7.0
WebView version 65.0.3325.109
