### ISSUE TITLE
Top Sites layout is closer to the bottom (than current Rocket version)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1488]
(Issued by Joe)

STR:
 1. Launch Rocket
 2. Check the Top sites layout

Expected result:
 - Top Sites layout is not closer to the bottom

Actual result: 
 - Top Sites layout is closer to the bottom (than current Rocket version)

Device: Sony Z3C
Rocket nightly: 2.0.0 (2383)
Android version: 6.0

**Comment by chianger** [comment]
i can't see the difference (on Pixel XL) now but can try latest build on z3c

**Comment by mTwTm** [comment]
Duplicate to #1691
