### ISSUE TITLE
Should be able to share home activity and refresh it

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1491]
(Issued by Al)

Expected result:
 - Should be able to share home activity and refresh it

Device: Oppo
Rocket nightly: 2.0.0 (2383)
Android version: 6.0
WebView version 64

**Comment by chianger** [comment]
@Conjuror can you provide more info? not sure what home activity means here.

**Comment by joechengla** [comment]
Don't need to block 1.1 if we cant figure out what this bug is

**Comment by mTwTm** [comment]
Can anyone provide some more details?

**Comment by chianger** [comment]
We don't know what this is so close it.
