### ISSUE TITLE
Open a link with target _blank doesn't open a link in new tab

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1492]
(Issued by Al)

Actual result: 
 - Open a link with target _blank doesn't open a link in new tab

Device: Oppo
Rocket nightly: 2.0.0 (2383)
Android version: 6.0
WebView version 64

**Comment by walkingice** [comment]
this should be fixed in #1638 as well

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Test page: http://test.julianchu.net/open_link/

Device: Pixel 2
Android: 8.1.0
Rocket: 2.0.0(3236)
WebView: 65.0.3325.109
