### ISSUE TITLE
Bottom Bar does not have border

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1493]
(Issued by Joe)

Bottom Bar does not have border

Device: Sony Z3C
Rocket nightly: 2.0.0 (2383)
Android version: 6.0

**Comment by carol-mozilla** [comment]
Hi @idiotmax ! Could you help fixing this issue!! Thank you!!!!!

**Comment by chianger** [comment]
We didn't tag a clear priority yet. needtriage.
