### ISSUE TITLE
Tab count misaligned if didn't use default font size (I used the largest font)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1494]
(Issued by Wesly)

Tab count misaligned if didn't use default font size (I used the largest font)

Device: Pixel XL
Rocket nightly: 2.0.0 (2383)
Android version: Android 8.1.0

**Comment by carol-mozilla** [comment]
I'll suggest to lock the font size of the tab count, so it won't be affected by the system settings.
