### ISSUE TITLE
The focus state on tab tray is shifted when one of the tab was deleted

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1495]
(Issued by Helen)

The focus state on tab tray is shifted when one of the tab was deleted

Device: Samsung
Rocket nightly: 2.0.0 (2383)
Android version: Android 6.0.1

**Comment by chianger** [comment]
sounds similar to #1529
QAWanted to see if this is reproducible. I can't reproduce with Pixel XL.

**Comment by cynthiatang** [comment]
Verified: Fixed (work for me)

Device: Pixel2
Android: 8.1.0
Rocket: 1.0.4 (3080).nightly
