### ISSUE TITLE
Tab View does not have Favicon

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1496]
(Issued by Joe)

STR:
 1. Launch Rocket
 2. Add a tab 
 3. Open the Tab Tray

Expected result:
 - There is a Favicon

Actual result: 
 - Tab View does not have Favicon

Device: Sony Z3C
Rocket nightly: 2.0.0 (2383)
Android version: 6.0

**Comment by chianger** [comment]
I wonder if this is still reproducible? QAWanted to check.

**Comment by cynthiatang** [comment]
Verified: Fixed (work for me)

Device: Pixel2
Android: 8.1.0
Rocket: 1.0.4 (3080).nightly
