### ISSUE TITLE
It would be great to add transition animation when clicking '+' and showing 'Home'

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1500]
(Issued by Eddie)

When clicking '+' and showing "Home", it would be great to 
  1. Add transition animation to indicate that the "Home" page is coming from the '+' button, 
  2. Increase the tabs number
  3. Show "Rocket Home" in the tab list each time the '+' button being clicked
otherwise it doesn't feel like a working new tab button

Device: HTC U Ultra

**Comment by chianger** [comment]
now there's a fade-in transition.
