### ISSUE TITLE
There's a flash shows up on the web page, when you enter a website

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1501]
(Issued by Carol)

There's a flash shows up on the web page, when you enter a website.

Device: GooglePixel
Rocket nightly: 2.0.0 (2383)
Android version: 8.1.0

**Comment by pharspher** [comment]
Fixed in #1526

**Comment by chianger** [comment]
likely non-reproducible. ready to be verified.

**Comment by cynthiatang** [comment]
Device: Pixel 2
Android: 8.1
Rocket: 2.0.0(3236)
WebView: 65.0.3325.109
