### ISSUE TITLE
The clickable area of 'tab tray' icon on home feels too small

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1502]
(Issued by Carol)

The clickable area of 'tab tray' icon on home feels too small

Device: GooglePixel
Rocket nightly: 2.0.0 (2383)
Android version: 8.1.0

**Comment by weslyhuang** [comment]
UX will update spec, then ENG to implement.

**Comment by carol-mozilla** [comment]
Here's the spec:https://drive.google.com/open?id=1xPKPXWtL02DynIaAaGjQiZ2282ilj0k2
Please check p.1
For tabtray and menu icon, change clickable area to 48dpx 48dp! Thanks

**Comment by weslyhuang** [comment]
in May 12.
