### ISSUE TITLE
Address bar remains the same despite you switch between different tabs

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1503]
(Issued by Vance)

Step:
 1. Launch Rocket. 
 2. Select Top site to create a tab
 3. Press + to go back to home page. 
 4. Select next top site to create another tab
 5. Repeat steps 2 to 4 to create 8 tabs.
 6. In the tab-tray, rapidly switch between tabs, the address bar will just remains the same

Address bar remains the same despite you switch between different tabs

Device: Samsung S7
Rocket nightly: 2.0.0 (2383)
Android version: 7.0

**Comment by chianger** [comment]
should be fixed in latest nightly

**Comment by pharspher** [comment]
fixed in #1564
