### ISSUE TITLE
Rocket 2.0 UX spec lockdown

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#1507]
latest spec version is v0.3
https://drive.google.com/file/d/1y5imcx2UEPjSmxNAOwn9w0TAYxpbbDdY/view

The spec will likely be updated once the design of #1483 is done.

**Comment by chianger** [comment]
Current materials are good enough for dev to work on. 
Detailed documents can be ready by end of mar-30 when 2.0 hits CC.

**Comment by Jacklin-ux** [comment]
Spec link:
https://drive.google.com/file/d/1AtRFvlOve71p8sg6qULXnSyItEOK8amu/view?usp=sharing
