### ISSUE TITLE
Failed to new a tab 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1514]
STR:
 1. Launch 
 2. Tap youtube and play any video 
 3. Tap '+'
 4. Tap search bar 
 5. Enter mozilla.org

Expected result:
 - User can visit mozilla.org in a new tab 
 - Tab icon shows '2' 

Actual result: 
 - User cannot visit mozilla.org in a new tab 
 - Tab icon shows '1' 

Device: Samsung J7
Rocket nightly: 2.0.0 (2441). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by chianger** [comment]
not reproducible on Pixel XL with nightly build.

**Comment by cynthiatang** [comment]
It works for me now. Thanks. :)

Device: Redmi Note4
Rocket nightly: 1.0.4 (2910). nightly
Android version: 7.0
WebView version 65.0.3325.109
