### ISSUE TITLE
Failed to show an alternative copy string "Firefox Rocket" when website name isn't loaded 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1527]
STR:
1. Launch Rocket
2. Tap the top site Bukalapak 
3. Tap the tab tray when the page is loading

Expected result:
 - There are 4 elements: 
    - Close Tab Button 
    - Favicon: Show a placeholder
    - Website Name: Firefox Rocket
    - Website URL: Show URL without "https://www"

Actual result:

Device: Samsung J7
Rocket nightly: 2.0.0 (2441). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by chianger** [comment]
QAWanted to clarify actual result and current status

**Comment by chianger** [comment]
to be verified.

**Comment by cynthiatang** [comment]
It works for me. thanks :)

Device: Pixel 2
Android: 8.0
Rocket: 2.0.0(3180).nightly
WebView: 65.0.3325.109
