### ISSUE TITLE
Wrong URL when navigating to an invalid url

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1528]
STR:
1. Launch Rocket
2. Navigating to an invalid url. For example: mozilla.org.tw
3. Tap the tab tray 
4. Check website URL
5. Close Rocket
6. Relaunch Rocket
7. Tap the tab tray

Expected result:
 - After step4:
    - Website Name: Webpage not available (404)
    - Website URL: Show URL without "https://www"

Actual result: 
 - Video: https://drive.google.com/open?id=1dB9zGtfnvFX9DGRUXzqKhi3Xkk0_Y1h3
 - After step 4: 
    - Website Name: Webpage not available (404)
    - Website URL is data:txt/html;charset=utf-8;base64,
 - After step 6: 
    - URL is empty. There is no content.  
 - After step 7: 
    - Website Name is data:txt/html;charset=utf-8;base64,
    - Website URL is data:txt/html;charset=utf-8;base64,

Device: Samsung J7
Rocket nightly: 2.0.0 (2533). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by weslyhuang** [comment]
next step on Roger to further check (problem after refresh)

**Comment by weslyhuang** [comment]
roger fixed it already.

**Comment by cynthiatang** [comment]
Verify: Fixed

Reproduced rate: 3/3

Device: Pixel 2
Rocket: 2.0.0(4168).night
Android version: 8.1.0
WebView version 66.0.3359.158
