### ISSUE TITLE
It should not change the focused tab when removing an unfocused tab

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1529]
STR:
1. Launch Rocket
2. Add 20 tabs
3. Open the tab tray
4. Remove an unfocused tab

Expected result:
 - The focused ring is still on the same tab
 - Please refer Rocket1.5_v0.3, page 28, 29, 30  (4.1 Remove an unfocused tab)

Actual result: 
 - It would change the focused tab
 - Video: https://drive.google.com/open?id=1xGbzV6pQtHINdxAtEAu1raCO8h57Ofvk

Device: Redmi Note4
Rocket nightly: 1.0.4 (2533). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by chianger** [comment]
QAWanted to see if this is reproducible.

**Comment by cynthiatang** [comment]
It works for me now. Thanks. :)

Device: Redmi Note4
Rocket nightly: 1.0.4 (2910). nightly
Android version: 7.0
WebView version 65.0.3325.109
