### ISSUE TITLE
It should close the tab tray and go back to Rocket home page after removing all tabs

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1530]
STR:
1. Launch Rocket
2. Add 20 tabs
3. Open the tab tray
4. Remove all tabs

Expected result:
 - Close the tab tray and go back to Rocket home page 
 - Please refer Rocket1.5_v0.3, page 30  (4.3 Remove the last tab)

Actual result: 
 - It doesn't close the tab tray

Device: Redmi Note4
Rocket nightly: 1.0.4 (2533). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by pharspher** [comment]
fixed in #1517

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks.

Device: Redmi Note4
Rocket nightly: 1.0.4 (3049).nightly
Android version: 7.0
WebView version 65.0.3325.109
