### ISSUE TITLE
Failed to open a link in a new tab 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1537]
STR:
1. Launch Rocket
2. Go to goo.gl/EQupVj  
3. Tap the link "W3Schools.com!"

Expected result:
 - The link will open in a new browser window or a new tab

Actual result: 
 - Failed to open the the link in a new tab 
 - Chrome: the link will open in a new tab

Device: Redmi Note4
Rocket nightly: 1.0.4 (2557). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by chianger** [comment]
Not reproducible on my Pixel XL and Max's A one.

**Comment by cynthiatang** [comment]
This issue can be reproduced. It is opened in the same tab, not in a new tab. 

Video: https://drive.google.com/open?id=1D9iewRRZ_aJZuz4H3ZFpLciTUV0qpKXa

Rocket:  2703.nightly
Device: Redmin 4X
Android OS: 7.0
WebView: 65.03325.109

**Comment by pharspher** [comment]
1. should call settings.setSupportMultipleWindows(true) in WebViewProvider#configureDefaultSettings() so onCreateWindow() will be called

2. In TabsSession$FocusWebChromeClientImpl#onCreateWindow(), the webView below will be null due to the implementation of TabsSession#addTabInternal().
```
    final WebView webView = (WebView) tab.getTabView();
    final WebView.WebViewTransport transport = (WebView.WebViewTransport) msg.obj;
    transport.setWebView(webView);
    msg.sendToTarget();
```

**Comment by walkingice** [comment]
FYI: I have a page to test open-new-window in different situations.
http://test.julianchu.net/open_link/

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Redmi Note4
Rocket nightly: 1.0.4 (3049).nightly
Android version: 7.0
WebView version 65.0.3325.109
