### ISSUE TITLE
Failed to visit https://bukalapak.com (Top 10) 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1538]
STR:
1. Close Rocket
2. Launch Rocket
3. Tap "bukalapak"

Expected Result:
 - User can visit the website

Actual Result:
 - Show the error page
 - This issue cannot be reproduced in Rocket 1.0.4 (2333)

Device: Redmi Note4
Rocket nightly: 1.0.4 (2557). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by chianger** [comment]
I guess this was fixed. To be confirmed during the pre-FC checkin.

**Comment by chianger** [comment]
#1548 #1549

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Redmi Note4
Rocket nightly: 1.0.4 (3049).nightly
Android version: 7.0
WebView version 65.0.3325.109
