### ISSUE TITLE
set version number to 1.1

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1539]
if Add to Homescreen is available

**Comment by chianger** [comment]
depends on #56

**Comment by chianger** [comment]
#1563 in flight

**Comment by cynthiatang** [comment]
Verified: Fixed.
Thanks. :)

Device: Redmi Note4
Rocket nightly: 1.1 (2949).debug.bitrise
Android version: 7.0
WebView version 65.0.3325.109
