### ISSUE TITLE
Failed to add new tabs from an external apps when Rocket is closed

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1541]
STR:
1. Launch Rocket
2. Add 2 tabs 
3. Close Rocket 
4. Launch external app, ex Gmail
5. Open a link via Rocket, ex a link in an email

Expected result:
 - User can add new tab from an external app

Actual result: 
 - There is only url. The context is empty
 - Video: https://drive.google.com/open?id=1c_X5Whx-23NyvKSVwctxBCAWKTp4oRec
 - Image: https://drive.google.com/open?id=1SoKhNbWKi8qB1Fmdrm9eqdiYKZVTfUWa

Device: Redmi Note4
Rocket nightly: 1.0.4 (2557). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by cnevinc** [comment]
I had the similar issue

**Comment by mTwTm** [comment]
I think this may be fixed after #1590, or somewhere else. Add label: qawanted

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Pixel2
Android: 8.1.0
Rocket: 1.0.4 (3080).nightly
