### ISSUE TITLE
Disable contextual feature hint on Screenshot

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1547]
Now that the screenshot feature is surfaced as a main feature. I suggest to disable the contextual hint for now

**Comment by mTwTm** [comment]
@benjamin-cheng I can review this when it's done :)

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks. :)

Device: Pixel 2
Rocket nightly: 2.0.0(3236)
Android version: 8.1.0
WebView version 65.0.3325.109
