### ISSUE TITLE
It should not have a popup window for asking the permission in the tray view after unlock screen

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1550]
STR:
1. Launch Rocket
2. Visit https://www.mapquest.com 
3. Tap ALLOW to allow the permission
4. Open the tab tray
5. Press the Sleep/Wake button to turn off screen
6. Press the Sleep/Wake to turn on screen 
7. Drag the slider.

Expected result:
 - No popup window for asking the permission 

Actual result: 
 - There is a popup window for asking the permission.  
    https://www.mapquest.com/wants to access your location 
                         BLOCK         ALLOW

Device: Redmi Note4
Rocket nightly: 1.0.4 (2557). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by pharspher** [comment]
similar issue happens when new tab button is clicked immediately after entering https://www.mapquest.com.

BrowserFragment should check whether it's visible to the user before calling permissionHandler.tryAction() or any other method that will attach window to the screen.

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Redmi Note4
Rocket nightly: 1.0.4 (3049).nightly
Android version: 7.0
WebView version 65.0.3325.109
