### ISSUE TITLE
Wrong behavior when user switches to other tabs before getting back to the external app

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1551]
STR:
1. Launch Rocket 
2. Add to 2 tabs ---> tab#1, tab#2
3. Launch an external app. For example:  Gmail 
4. Open a link via Rocket. For example:  a link in an email
5. Open the tab tray
6. Tap an unfocused tab ---> tab#1 or tab#2
7. Tab system Back key
8. Tab system Back key again
9. Switch to Rocket app. Check the tap tray

Expected result:
 - After step 7, go back to Rocket Home page
 - After step 8, go back to external app
 - After step 9, there are 3 tabs

Actual result: 
 - After step 7, go back to external app
 - After step 8, go back to System Home
 - After step 9, there are 4 tabs. one is empty 
 - Video: https://drive.google.com/open?id=1yaHPjZyR3sTZxz4yCbJjxYQ2PY0bBVYU

Device: Redmi Note4
Rocket nightly: 1.0.4 (2557). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by mTwTm** [comment]
Closed by #1694

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.1.0
Rocket: 2.0.0(3236)
WebView: 65.0.3325.109
