### ISSUE TITLE
Site identity is evaluated as secure even if the certificate is invalid

### ISSUE THREAD

**Issue by pharspher** [mozilla-tw/Rocket#1562]
Currently Rocket evaluates site identity only by checking whether there's a certificate presented. However, certificates that are expired, self-signed, revoked, etc should also be considered insecure.

```
public class WebkitView extends NestedWebView implements TabView {
    @Override
    public @SiteIdentity.SecurityState int getSecurityState() {
        return getCertificate() == null ? SiteIdentity.INSECURE : SiteIdentity.SECURE;
    }
}
```

**Comment by chianger** [comment]
badssl.com is a easy tool to verify if Rocket is acting well. It seems Rocket would reject 'expired', and 'self-signed'. But some issues around 'revoked'. Let's triage.

**Comment by pharspher** [comment]
@chianger Sorry, I should label this as 2.0 issue. On v2.0, even web site of type "expired" and "self-signed" will be considered secure. I've already found the root cause, and will fix it in another PR.

For revoked type, I found Google Chrome for Desktop can correctly recognize it as insecure, while Chrome for Android can not.

**Comment by chianger** [comment]
I see. I'm adding that to CodeComplete milestone so that we can make sure this get verified before shipping.

**Comment by chianger** [comment]
to be verified. So far the behavior should be the same as Firefox Focus.

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks :)

[Uploading Rock_Bad_Ssl.pdf…]()


Device: Pixel 2
Android: 8.1.0
Rocket: 2.0.0
(3180).nightly
WebView: 65.0.3325.109
