### ISSUE TITLE
google.com unable to get location

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1585]
build 2703

**Comment by chianger** [comment]
something to do with https

**Comment by chianger** [comment]
needtriage to determine priority

**Comment by joechengla** [comment]
It's ok to not block 1.1. But let's continue to look j to this

**Comment by chianger** [comment]
somehow the 2.0 nightly connects with "http" instead of "https" to google.com.

**Comment by weslyhuang** [comment]
google.com behavior. close.
