### ISSUE TITLE
Video&Audio should be stop after opening the tab tray and tapping '+'

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1586]
STR:
1. Launch Rocket 
2. Visit youtube.com 
3. Play any video
4. Tap '+' or open the tab tray

Expected result:
 - The video should be stopped

Actual result: 
 - User can hear the video

Device: Redmi Note4
Rocket nightly: 1.0.4 (2703). nightly
Android version: 7.0
WebView version 64.0.3282.137

**Comment by cynthiatang** [comment]
Verified: Failed

STR:
1. Launch Rocket
2. Visit youtube.com
3. Play any video
4. Open the tab tray

Actual result
 - A user can hear the video

Device Pixel2
Rocket: 2.0.0(3236)
Android:8.1.0
WebView 65.0.3225.109

**Comment by cynthiatang** [comment]
Hi @Jacklin-ux 
Does Rocket allow to keep playing Video&Audio after opening the tab tray?

**Comment by walkingice** [comment]
Per my understanding, the video/audio playback is kept until we press '+' button

**Comment by cynthiatang** [comment]
New update from Jack: Rocket would keep playing Video&Audio when the tab tray is opened. He will modify UX spec. 

It works for me now. Thanks
