### ISSUE TITLE
Rocket crashes when trying to reload the home panel after closing all tabs

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1589]
1. Close all tabs in tab view
2. Now at home panel with zero tabs
3. Tap menu and tap reload or X
4. Rocket crashes

**Comment by chianger** [comment]
I'm using build 2703 and it actually crashes while i'm trying to close all tabs one by one.

**Comment by mTwTm** [comment]
The reload button should not be enabled.

**Comment by mTwTm** [comment]
Actually, should we keep those three navigating icons? Maybe we should hide them? @Jacklin-ux

**Comment by Jacklin-ux** [comment]
Can we disable "reload/X" and "share" buttons when the home page is opened? (Same as in Rocket 1.0)

**Comment by cynthiatang** [comment]
Verified - Fixed

Device: Redmi Note4
Rocket nightly: 1.0.4(3049).nightly
Android version: 7.0
WebView version 65.0.3325.109
