### ISSUE TITLE
1.1 Missing string in the "Make default browser" notification 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1616]
STR:
 1. Launch Rocket 
 2. Press settings 2ed time

Expected result:
 - Show "Make default browser" notification 

Actual result: 
 - Failed to show "Make default browser" notification . 
 - User have to swipe down the notification list to read the notification
 - Missing string is "Make Firefox Rocket as your default browser for fast browsing!"
![0-1](https://user-images.githubusercontent.com/12458450/37647661-bc67e410-2c67-11e8-91c3-b660f35184fc.png)

Device: Redmi Note4
Rocket nightly: 1.1 (2862).debug.bitrise
Android version: 7.0
WebView version 64.0.3325.109

**Comment by cnevinc** [comment]
https://github.com/mozilla-l10n/zerda-android-l10n/pull/13

**Comment by chianger** [comment]
l10n needed, depending on https://github.com/mozilla-l10n/zerda-android-l10n/pull/13
triage decision: not to block v1.1 shipping with this. let's leave the ID translation empty for now

**Comment by chianger** [comment]
So maybe this newly added string can ride on next release which is 2.0.
(next pull request is by Mar-23rd, and expect to code complete by Mar-30 PST)

**Comment by cnevinc** [comment]
I'll remove the string and the commit in PR #1621 now. After we have a new string (which can fit into the notification width), I'll add it again.

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly and Rocket 1.1
WebView: 65.0.3325.109
