### ISSUE TITLE
2.0: Rocket crashes 100% when trying to set default browser from Settings 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1624]
build 2829

**Comment by cnevinc** [comment]
PR #1594 should have fixed this. Let's check later

**Comment by chianger** [comment]
#1594 is merged so close this to be verified.

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Redmi Note4
Rocket nightly: 1.0.4 (3049).nightly
Android version: 7.0
WebView version 65.0.3325.109
