### ISSUE TITLE
When a first-level page is closed, user can't switch tab

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1631]
STR:

1. Open several pages via Top Site
2. press back to go back to home from BrowserFragment
3. Open Tab tray
4. Click tab

Expected result:
switch to tab

Actual result:
still in tab tray

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109
