### ISSUE TITLE
1.1 Failed to show "Make default browser" notification after users press settings 2ed time (Redmi)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1644]
STR:
 1. Launch Rocket 
 2. Tap menu
 3. Tap Settings
 4. Tap menu
 5. Tap system Back
 6. Tap Settings 

Expected result:
 - Show "Make default browser" notification after users press settings 2ed time

Actual result: 
 - Failed to show "Make default browser" notification after users press settings 2ed time
 - Video: https://drive.google.com/open?id=1qo__k3Abt8BavMGPmbd_QaADqJbgcHp5

Reproduced rate: 10/10

Device: Redmi Note4
Rocket nightly: 1.1 (3010)
Android version: 7.0
WebView version 65.0.3325.109

This issue cannot be reproduced in Pixel2 and Sony Z3C
Device: Sony Z3C
Rocket nightly: 1.1 (3010)
Android version: 6.0.1
WebView version 64.0.3282.137

Device: Pixel2
Rocket nightly: 1.1 (3010)
Android version: 8
WebView version 65.0.3325.109

**Comment by cnevinc** [comment]
You need to go to their setting page for Firefox Rocket.
https://www.youtube.com/watch?v=H7WrhCAlWrw

**Comment by joechengla** [comment]
What happens if you tap on it?

**Comment by cnevinc** [comment]
Go to the system settings page

**Comment by chianger** [comment]
"floating notification", and "priority" under system setting>>install apps>> firefox rocket need to be turned on to have this show up. This is probably because of MIUI.

**Comment by weslyhuang** [comment]
more like RedMi's design, close per discusssion.
