### ISSUE TITLE
Google permission does not work

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1653]
Please refer the spec for Rocket 1.0.3 

STR:
 1. Uninstall Rocket and 
 2. Re-install Rocket 
 3. Launch Rocket 
 4. Visit https://permission.site
 5. Tap "Location"

Expected result:
 - There is popup window to ask user "Allow Firefox Rocket to access this device's location"

Actual result: 
 - There is no popup window. 
 - This issue cannot be reproduced in Rocket 1.1 (3010)

Reproduced Rate: 10/10

Device: Pixel 2
Rocket nightly: 1.0.4 (3003). nightly
Android version: 8
WebView version 65.0.3325.109

**Comment by mTwTm** [comment]
Not happening on my
1.0.4(3049).nightly
WebView version: 65.0.3325.109

**Comment by cynthiatang** [comment]
I'd like to close this issue. Because it works for me on Rocket1.0.4(3049).nightly. Thanks.
