### ISSUE TITLE
Show "... wants to access your location" message too many times when searching

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#1654]
STR:
 1. Launch Rocket
 2. Input keyword then search
 3. Show "https://www.google.com.tw/ wants to access your location." on the search page
 4. Press ALLOW
 5. Press search button then search again

Expected result:
 - No need to show the message again

Actual result:
 - Show "https://www.google.com.tw/ wants to access your location." again

Device: Pixel 2
Rocket nightly: 1.1 (2979).debug.bitrise
Android version: 8
WebView version 64.0.3282.137

**Comment by mTwTm** [comment]
Duplicate to #1653

**Comment by cynthiatang** [comment]
I'd like to reopen this issue because it's not the same #1653.

**Comment by chianger** [comment]
When this is fixed, it also fixes #1697

**Comment by weslyhuang** [comment]
next step on UX: propose a possible design.

**Comment by Jacklin-ux** [comment]
<img width="314" alt="screen shot 2018-08-09 at 5 43 18 pm" src="https://user-images.githubusercontent.com/22672569/43891490-fd759002-9bfb-11e8-8e4a-76d9ea7090a4.png">

**Comment by Jacklin-ux** [comment]
![image](https://user-images.githubusercontent.com/22672569/44070744-34168408-9fb8-11e8-8dd2-4c08f7be8ecc.png)

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/13Sqza_2WR0nmuNXGLD22-fh3DfJEJ5ts/view?usp=sharing

**Comment by chianger** [comment]
Last piece of string change landed 8 hours ago.
https://github.com/mozilla-tw/Rocket/commit/d78c03389e8f4fafd2feb89b76a85f2c59f5deb4
Should be ready to be verified with RC build.
