### ISSUE TITLE
Wrong tab number after tapping Back key twice and relaunch Rocket again

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1664]
STR:
 1. Launch Rocket
 2. Add 6 tabs 
 3. Tap system Back key twice 
 4. Relaunch Rocket again

Expected result:
 - The tab number should be 5

Actual result: 
 - The tab number is 0
 - Video: https://drive.google.com/open?id=1AnF71etRDol2c_Z1-gAlajzDfIVw0H_M

Reproduced rate: 5/5

Device: Redmi Note4
Rocket nightly: 1.0.4(3049)
Android version: 7.0
WebView version 65.0.3325.109

**Comment by chianger** [comment]
To be verified.

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.1.0
Rocket: 2.0.0(3236)
WebView: 65.0.3325.109
