### ISSUE TITLE
1.1 Failed to play audio from http://indeks.kompas.com/radio/sonora (Top website) 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1666]
STR:
 1. Launch Rocket
 2. Play audio from http://indeks.kompas.com/radio/sonora

Expected result:
 - A user can play audio 

Actual result:
 - A user cannot play audio in Rocket 1.1 and Rocket 2.0 
 - This issue cannot be reproduced in Chrome
 - This issue cannot be reproduced in Rocket 1.0.1 Build 1777 
    (https://github.com/mozilla-tw/Rocket/issues/1279)

Reproduced rate: 5/5

Device: Redmi Note4
Rocket nightly: 1.0.4(3049)
Android version: 7.0
WebView version 65.0.3325.109

Device: Redmi Note4
Rocket nightly: 1.1(3010)
Android version: 7.0
WebView version 65.0.3325.109

**Comment by chianger** [comment]
Regression. let's look into this before 2.0 ship to production

**Comment by idiotmax** [comment]
Mixed Content: The page at 'https://indeks.kompas.com/radio/sonora' was loaded over HTTPS, but requested an insecure video 'http://kompas.rastream.com/kompas-sonorajakarta?awparams=companionads%3Afalse%3Btags%3Aradioactive%3Bstationid%3Akompas-sonorajakarta&playerid=Sonora_web&authtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvaWQiOiJsYXlsaW8iLCJpYXQiOjE1MjI2Mzk3MDgsImV4cCI6MTUyMjcyNjEwOH0.7AkD_vFIoNmvzhHXMq2hYYafpAItcVNLIYJnMR4CTbk&listenerid=e16aa872d3a25cb1b168ae1f45a43887'. This request has been blocked; the content must be served over HTTPS.

**Comment by mTwTm** [comment]
Closing this and add this to meta: mixed contents (#954 )
