### ISSUE TITLE
Tab list and the count got reset.  [data loss]

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#1687]
STR:
1. Launch Rocket via a link from Gmail, 
2. press back key to go back to Gmail, 
3. Press system home, 
4. Tap on Rocket app icon

Expected result: existing tabs still there

Actual result: the whole tab list is gone. count got reset to zero

Device/config: Z3C, Android 6.0; also on Pixel, Android 8.

Note: but if you launch Rocket again via a link from Gmail, your previous tabs will be back

**Comment by mTwTm** [comment]
It seems to be just tab count display problem?

**Comment by cynthiatang** [comment]
@mTwTm  There is another similar issue. https://github.com/mozilla-tw/Rocket/issues/1664

STR:
 1. Launch Rocket
 2. Add some tabs
 3. Tap system Back key twice
 4. Relaunch Rocket again

Actual result:
 - Tab number is zero. But the tab number would be right after visiting any website

**Comment by chianger** [comment]
Cool. Feel free to mark any of it duplicate if confirmed to be the same one.

**Comment by chianger** [comment]
Replied to @mTwTm , at the Rocket homescreen, the tab count icon displays '0', and tapping on it doesn't work to bring up the tab list.  For that moment it's a data loss to users, regardless of easy or tricky workarounds.

**Comment by benjamin-cheng** [comment]
It has the same root cause as #1664.

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.0
Rocket: 2.0.0(3180).nightly
WebView: 65.0.3325.109
