### ISSUE TITLE
Glide carshing when manipulating recycled bitmap

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1693]
(Issued by Eddie)

Crashed - once when add to homescreen, once when close tab 

STR:
 - Try to add to Home screen, or try to close tab

Device: HTC U Ultra
Rocket: 1.0.4 (3132).nightly

**Comment by cynthiatang** [comment]
--------- beginning of crash
03-27 11:41:59.710 32708 32708 E AndroidRuntime: FATAL EXCEPTION: main
03-27 11:41:59.710 32708 32708 E AndroidRuntime: Process: gro.allizom.zelda.beta, PID: 32708
03-27 11:41:59.710 32708 32708 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.view.View$DeclaredOnClickListener.onClick(View.java:4710)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22399)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6464)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.view.View$DeclaredOnClickListener.onClick(View.java:4705)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	... 9 more
03-27 11:41:59.710 32708 32708 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Can't call getPixels() on a recycled bitmap
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.graphics.Bitmap.checkRecycled(Bitmap.java:383)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at android.graphics.Bitmap.getPixels(Bitmap.java:1429)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.utils.FavIconUtils.getDominantColor(FavIconUtils.java:85)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.utils.FavIconUtils.getDominantColor(FavIconUtils.java:59)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.utils.FavIconUtils.getInitialBitmap(FavIconUtils.java:40)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.utils.FavIconUtils.getRefinedShortcutIcon(FavIconUtils.java:189)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.utils.ShortcutUtils.requestPinShortcut(ShortcutUtils.java:44)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.activity.MainActivity.onAddToHomeClicked(MainActivity.java:706)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.activity.MainActivity.onMenuBrowsingItemClicked(MainActivity.java:574)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	at org.mozilla.focus.activity.MainActivity.onMenuItemClicked(MainActivity.java:504)
03-27 11:41:59.710 32708 32708 E AndroidRuntime: 	... 11 more
03-27 11:56:04.442  5215  5215 E AndroidRuntime: FATAL EXCEPTION: main
03-27 11:56:04.442  5215  5215 E AndroidRuntime: Process: gro.allizom.zelda.beta, PID: 5215
03-27 11:56:04.442  5215  5215 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:413)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at org.mozilla.focus.tabs.tabtray.TabTrayPresenter.tabCloseClicked(TabTrayPresenter.java:39)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at org.mozilla.focus.tabs.tabtray.TabTrayFragment.onTabCloseClick(TabTrayFragment.java:203)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at org.mozilla.focus.tabs.tabtray.TabTrayAdapter$InternalTabClickListener.dispatchOnClick(TabTrayAdapter.java:212)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at org.mozilla.focus.tabs.tabtray.TabTrayAdapter$InternalTabClickListener.onClick(TabTrayAdapter.java:201)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22399)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:173)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6464)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
03-27 11:56:04.442  5215  5215 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
03-28 15:48:58.473  1486 21536 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x18 in tid 21536 (Binder:1486_18)
03-28 15:48:58.855 18476 18476 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-28 15:48:58.856 18476 18476 F DEBUG   : Build fingerprint: 'htc/ocedugl_00709/htc_ocedugl:7.0/NRD90M/946680.12:user/release-keys'
03-28 15:48:58.856 18476 18476 F DEBUG   : Revision: '0'
03-28 15:48:58.856 18476 18476 F DEBUG   : ABI: 'arm64'
03-28 15:48:58.857 18476 18476 F DEBUG   : pid: 1486, tid: 21536, name: Binder:1486_18  >>> system_server <<<
03-28 15:48:58.857 18476 18476 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
03-28 15:48:58.857 18476 18476 F DEBUG   :     x0   0000007f7fd04480  x1   0000007f7585ebe4  x2   000000000000000a  x3   0000000000003832
03-28 15:48:58.858 18476 18476 F DEBUG   :     x4   0000007f7585ebe4  x5   0000007f9dfbe18c  x6   0000000000000000  x7   0000000000000000
03-28 15:48:58.858 18476 18476 F DEBUG   :     x8   0000000000000000  x9   000000000000000a  x10  0000000000430000  x11  0000007f7585ebe4
03-28 15:48:58.858 18476 18476 F DEBUG   :     x12  0000007f7685eb68  x13  0000007f9b7121f0  x14  0000007f9b712250  x15  0000000000000000
03-28 15:48:58.858 18476 18476 F DEBUG   :     x16  0000007f9bc617b8  x17  0000007f9db2f2c0  x18  0000000000000001  x19  0000007f6b1ece80
03-28 15:48:58.858 18476 18476 F DEBUG   :     x20  0000007f9dfbe18c  x21  000000000000000a  x22  0000000000000000  x23  0000007f7fd04480
03-28 15:48:58.858 18476 18476 F DEBUG   :     x24  0000007f7585ebe4  x25  0000007f7585ebd8  x26  8c65a569d2ad56c4  x27  0000007f7585ebc8
03-28 15:48:58.858 18476 18476 F DEBUG   :     x28  0000000000000002  x29  0000007f7585ebb0  x30  0000007f8ef0d43c
03-28 15:48:58.859 18476 18476 F DEBUG   :     sp   0000007f7585ebb0  pc   0000007f9dfbe198  pstate 0000000060000000
03-28 15:48:59.434 18476 18476 F DEBUG   : 
03-28 15:48:59.434 18476 18476 F DEBUG   : backtrace:
03-28 15:48:59.434 18476 18476 F DEBUG   :     #00 pc 000000000007d198  /system/lib64/libcrypto.so (EVP_DigestUpdate+12)
03-28 15:48:59.434 18476 18476 F DEBUG   :     #01 pc 000000000001f438  /system/lib64/libjavacrypto.so
03-28 15:48:59.435 18476 18476 F DEBUG   :     #02 pc 000000000007f984  /system/framework/arm64/boot-conscrypt.oat (offset 0x70000) (com.android.org.conscrypt.NativeCrypto.EVP_DigestUpdate+192)
03-28 15:48:59.435 18476 18476 F DEBUG   :     #03 pc 000000000009c670  /system/framework/arm64/boot-conscrypt.oat (offset 0x70000) (com.android.org.conscrypt.OpenSSLMessageDigestJDK.engineUpdate+108)
03-28 15:48:59.435 18476 18476 F DEBUG   :     #04 pc 0000000000700e28  /system/framework/arm64/boot.oat (offset 0x5a2000) (java.security.MessageDigest$Delegate.engineUpdate+68)
03-28 15:48:59.435 18476 18476 F DEBUG   :     #05 pc 00000000007006c8  /system/framework/arm64/boot.oat (offset 0x5a2000) (java.security.MessageDigest.update+68)
03-28 15:48:59.435 18476 18476 F DEBUG   :     #06 pc 00000000000d22b4  /system/lib64/libart.so (art_quick_invoke_stub+580)
03-28 15:48:59.436 18476 18476 F DEBUG   :     #07 pc 00000000000def80  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+204)
03-28 15:48:59.436 18476 18476 F DEBUG   :     #08 pc 00000000002908dc  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+312)
03-28 15:48:59.436 18476 18476 F DEBUG   :     #09 pc 00000000002898b8  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
03-28 15:48:59.436 18476 18476 F DEBUG   :     #10 pc 000000000055b804  /system/lib64/libart.so (MterpInvokeVirtualQuick+452)
03-28 15:48:59.436 18476 18476 F DEBUG   :     #11 pc 00000000000c8a14  /system/lib64/libart.so (ExecuteMterpImpl+29972)
03-28 15:49:08.986  2005  2005 E AndroidRuntime: FATAL EXCEPTION: main
03-28 15:49:08.986  2005  2005 E AndroidRuntime: Process: com.android.phone, PID: 2005
03-28 15:49:08.986  2005  2005 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
03-28 15:49:09.140 21637 18177 E AndroidRuntime: FATAL EXCEPTION: [LINE] #65 FWorker caq
03-28 15:49:09.140 21637 18177 E AndroidRuntime: Process: jp.naver.line.android, PID: 21637
03-28 15:49:09.140 21637 18177 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
--------- beginning of system

**Comment by pharspher** [comment]
crash after closing tab is fixed in #1684

**Comment by mTwTm** [comment]
Move back to 2.0

**Comment by weslyhuang** [comment]
TBD for Apr. 13 open beta 2.
