### ISSUE TITLE
When trying to cancel Search on a webpage, it will keep going "back" until tab closed

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1696]
(Issued by Eddie)
STR:
 1. Launch Rocket
 2. Visit any webpage
 3. Tap the Url field 
 4. Tap the gray area to close the keyboard

Expect result
 - Keep staying on the same webpage

Actual result
 - Close the tab and back to Home
 - Video: https://drive.google.com/open?id=1W9YRgAXGp5ebUkBSwCNvNtTPcKTqiHmT

Device: HTC U Ultra

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3132).nightly
WebView: 65.0.3325.109

**Comment by pharspher** [comment]
fixed in #1681

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109
