### ISSUE TITLE
Often see tab number showing 1 and then jump to the correct number when opening link from gmail (sometimes the lag is long)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1699]
(Issued by Joe)

STR:
 1. Launch Rocket without any tab
 2. Add a new tab 
 3. Open a new link from an external app (Gmail)
 4. See tab number

Actual result:
 - Often see tab number showing 1 and then jump to the correct number when opening a link from Gmail (sometimes the lag is long)

Device: Sony Z3C
Android: 6.0
Rocket: 1.0.4(3132).nightly

**Comment by chianger** [comment]
it might be better to leave empty instead of showing "1"

**Comment by carol-mozilla** [comment]
Let's show ":)" before showing the correct tab count#. Thanks!

**Comment by chianger** [comment]
per discussion during the standup meeting on Mar30, it's feasible to show ":)", so I'm putting this to 2.0 grand release milestone.

**Comment by cynthiatang** [comment]
Verified: fixed. Thanks :-)

Sony Z3C
Rocket2.0.0(3564)
Android 6.0.1
WebView:66.0.3359.82
