### ISSUE TITLE
It should not show the notification "Make default browser"  if user already set Rocket as a default browser

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1703]
STR:
1. Uninstall Rocket
2. Reinstall Rocket
3. Launch Rocket 
4. Tap menu -> Tap Settings -> Set Rocket as a default browser
5. Go back to Rocket Home page
6. Tap menu -> Tap Settings

Expeceted result:
 - Don't show the notification "Make default browser"

Actual result: 
 - It would still show the notification "Make default browser"
 - Video: https://drive.google.com/open?id=1MqoNQPGOPWlDjQhWYjBESJIrWcmGfuCp

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109

**Comment by walkingice** [comment]
I would like to move `MaincActivity.driveDefaultBrowser()` to **SettingsActivity**

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks :)

Redmi Note4
Android 7.0
Rocket 2.0.0(3502).nightly
WebView: 66.0.3359.82
