### ISSUE TITLE
When opening a site or search from Rocket home page, press system back key should keep the opened tab (not remove it)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1706]
(Issued by Jack)

STR:
1. Launch Rocket
2. Add 3 tabs
3. Tap system Back key

Actual Result:
 - the opened tab is removed
 - Video: https://drive.google.com/open?id=1fCavDw-jelxtQgNaVX99msVMTE_6qCVd

Expected Result:
 - keep the opened tab (not remove it)

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109

**Comment by pharspher** [comment]
This issue seems to be fixed in #1694, however, if we press back once again to leave Rocket and relaunch, the tab will be restored instead of showing home.

**Comment by chianger** [comment]
Close and to be verified.

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.1.0
Rocket: 2.0.0(3180).nightly
WebView: 65.0.3325.109
