### ISSUE TITLE
Open a site->open tab tray->press add button then switch to home page, the current transition: tab tray -> a site -> home (too complicated). Can the transition be: tab tray -> home?

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1710]
(Issued by Jack)

Open a site->open tab tray->press add button then switch to home page, the current transition: tab tray -> a site -> home (too complicated). Can the transition be: tab tray -> home?

GooglePixel2, Android 8.1.0

**Comment by cynthiatang** [comment]
Need UX's help

**Comment by pharspher** [comment]
This is an old issue provided by Jack last time we run bug bash and is already fixed.

**Comment by cynthiatang** [comment]
Verified: Fixed. thanks :)

Device: Pixel 2
Android: 8.0
Rocket: 2.0.0(3180).nightly
WebView: 65.0.3325.109
