### ISSUE TITLE
Long press photo then show "Open link in new tab", but when switch to that tab, show the photo not show the page (link) 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1716]
(Issued by Jack)

STR:
1. Launch Rocket
2. Tap the top site Tokopeida
3. Long press any photo under Midweek Electronic Fest
4. Tap Open link in new tab -> Tap Switch  -------------> Result 1
5. Tap system Back key
6. Tap the same photo under Midweek Electronic Fest ------> Result 2

Expected result:
 - Result 1 = Result 2

Actual result:
 - <img width="480" alt="screen shot 2018-03-28 at 4 50 52" src="https://user-images.githubusercontent.com/12458450/38018724-4e86fba6-32a8-11e8-9c01-b17e73ba4baa.png">

Device: Pixel 2
Android: 8.0
Rocket: 1.0.4(3162).nightly
WebView: 65.0.3325.109

**Comment by pharspher** [comment]
WebView only provides image url if it recognizes the click target as an image. I also test on google chrome, which has exactly the same behavior.

As discussed with UX, we will use another string "Open image in new tab" if the target is of image type.

**Comment by cynthiatang** [comment]
Verified: Fixed

Device Redmi Note 4
Rocket 2.0.0(3502).nightly
Webview: 66.0.3359.82
Android: 7.0
