### ISSUE TITLE
Facebook Multitab experience finetune

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1734]
1. Tap an article on Facebook
2. Article is in New tab is opened 
3. Finish reading and press back key
4. Now I see Rocket Home (not expected. I expect to be taken back to Facebook and Chrome does this)
5. Press back again will exit Rocket

**Comment by mTwTm** [comment]
Should be fixed in #1729

**Comment by mTwTm** [comment]
Close this to be verified.

**Comment by cynthiatang** [comment]
Verified: Fixed

Samsung J7
Android 7.0
Rocket 2.0.0(3408)
WebView 65.0.3325.109
