### ISSUE TITLE
Check if there's a timestamp / sequence id in Telemetry

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#1747]

**Comment by cnevinc** [comment]
timestamp: times in millisecond from the app start to the time that event happens
SEQ: a batch ID increased when a ping is built.

**Comment by cnevinc** [comment]
If we want to track the sequence of events for a user, SEQ maybe a good choice.

**Comment by elin-moco** [comment]
After discussion, I tried using the JSON Array's element order,
and the sunburst chart looks good now, all first_run events are first event.
https://sql.telemetry.mozilla.org/queries/50777#137020
