### ISSUE TITLE
Design the feature for side-load and OEM

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#1749]

**Comment by weslyhuang** [comment]
1. need to be able to track the distribution for any side-load case.
2. experimental so no need for a long-term solid method.

**Comment by chianger** [comment]
it's happening now so it's not P2.

**Comment by chianger** [comment]
QAWanted to follow up QA validation process.

**Comment by Daisy-pliu** [comment]
Verify : ✅
Test device : Samsung Galzxy S7 Edge (8.0.0)
Test Step:
1. reset Google Ads ID
2. install build [#9033 Bitrise](https://slack-redir.net/link?url=https%3A%2F%2Fapp.bitrise.io%2Fbuild%2Fec51d5ae00f47a43&v=3)
3. check [adjust track for Gmobi](https://next.adjust.com/#/statistics/overview/default/fngm2fg6tssg/zkq09za?from=2018-12-28&to=2018-12-28&countries=tw&attribution_type=click&range=today&gkpi=installs&scale=sqrt&grouping=trackers&timezone_id=172&conversion_type=all&attribution_source=dynamic) OEM track
