### ISSUE TITLE
2.0 - Turbo Mode switch on the wrong onboarding page 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1757]

**Comment by joechengla** [comment]
Turbo mode intro is now on the 1st page so the switch should be on the first page as well.

**Comment by cynthiatang** [comment]
<img width="635" alt="screen shot 2018-04-03 at 2 49 47" src="https://user-images.githubusercontent.com/12458450/38233792-68d0fc96-374e-11e8-9108-f5a18c38d1ea.png">
