### ISSUE TITLE
Contextual Hints: Clean up and use Firebase remote config 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1758]
1. For promotions only. Include the content and time for dialogues and notifications
2. May need to add new timing/criterial for above

**Comment by cnevinc** [comment]
I'll need the list of dialogues and notifications to use Remote Config.
And what's the new timing for 2?

**Comment by joechengla** [comment]
- Set as default browser
- Like Firefox Rocket
- Share with Friends

**Comment by weslyhuang** [comment]
in May 12 scope.
