### ISSUE TITLE
A keyboard overlaps the on-boarding page after taping the top of the screen

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1772]
STR
 1. Install Rocket 2.0
 2. Launch Rocket 
 3. Tap the top of the screen 
 
Expected result:
 - Nothing happened

Actual result:
 - There is a search bar with the keyboard. It overlaps the onboarding page. 
 - Enter "mozilla.org" in the search bar -> close on-onboarding page -> Tap tab tray -> There is a tab for mozilla.org
 - Video: https://drive.google.com/open?id=1gExvrzJAnyZSWODpgf6CEBDwg44s6JTd
 - Image:
<img width="974" alt="screen shot 2018-04-10 at 11 41 34" src="https://user-images.githubusercontent.com/12458450/38535031-34929cda-3cb4-11e8-8239-e209301ecd64.png">

Device: Sony Z3C 
Rocket: 2.0.0(3279)
Android 6.0.1
Webview: 65:0.3325.109

**Comment by benjamin-cheng** [comment]
Touch event passed to the underneath browser fragment's url bar (@+id/display_url)

![screen shot 2018-04-11 at 10 44 23 am](https://user-images.githubusercontent.com/7045016/38593721-62b48b52-3d75-11e8-9015-48ba9aeb1bf0.png)

**Comment by weslyhuang** [comment]
will be S1 if worked in 1.X before. (Regression from the user point of view)

**Comment by weslyhuang** [comment]
Severity S1, as confirmed it' is a regression (and visible to the end user)
Priority TBD, blocking 2.0 or not?

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8.1.0
Rocket 2.1.1(4696).nightly
WebView 67.0.3396.68
