### ISSUE TITLE
When tabs count to 99, the text size become bigger 

### ISSUE THREAD

**Issue by carol-mozilla** [mozilla-tw/Rocket#1793]
![screenshot_20180412-172520](https://user-images.githubusercontent.com/6700296/38668643-f0b80ef4-3e76-11e8-925e-322addb88ae7.png)
![screenshot_20180412-172531](https://user-images.githubusercontent.com/6700296/38668644-f0e705f6-3e76-11e8-8e5c-d6d613fee2f6.png)

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks

Rocket 2.0.0(3585)
Redmi Note4
Android 7.0
WebView: 66.0.3359.82
