### ISSUE TITLE
Experiment: Asian Games in Jakarta content offering

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1798]

**Comment by chianger** [comment]
most likely won't make 2.4 so we can ship dot release (2.4.1) for this feature

**Comment by chianger** [comment]
For 2.4.1 we target string freeze by July20 so it makes sense to confirm the four sites before that.

**Comment by Pekochen** [comment]
visual [spec:](https://drive.google.com/open?id=1_OzeVmSZWImRs22bHHky6cYKK3xfnc1R)

**Comment by Pekochen** [comment]
visual spec is here
https://drive.google.com/open?id=1_OzeVmSZWImRs22bHHky6cYKK3xfnc1R

**Comment by chianger** [comment]
acceptance criteria: 
1. pref on/off thru firebase
2. consider to coexist with #2259

**Comment by Pekochen** [comment]
update Asian games visual spec:
https://drive.google.com/open?id=1OSl3FbQcUcYD_KULbCvTOjoF6ORqojxY
add a description of website alignment.

**Comment by joechengla** [comment]
https://asiangames2018.id/
https://www.detik.com/tag/asian-games-2018
https://m.cnnindonesia.com/tag/asian-games
http://www.thejakartapost.com/tag/Asian-Games

**Comment by mTwTm** [comment]
I'm using https://indeks.kompas.com/tag/asian-games-2018 instead of https://m.cnnindonesia.com/tag/asian-games.
