### ISSUE TITLE
Page is enlarged while using Rocket visiting m.bilibili.com

### ISSUE THREAD

**Issue by rxumoz** [mozilla-tw/Rocket#1813]
**STR:**

    Launch Rocket
    Visit  https://m.bilibili.com

**Expected result:**
![screenshot_20180417-163646](https://user-images.githubusercontent.com/33616048/38975592-01182cec-43e1-11e8-8010-83cd4bd5e96a.png)

**Actual result:**
![screenshot_20180417-163635](https://user-images.githubusercontent.com/33616048/38975608-14483d48-43e1-11e8-9186-cf355dc9a8bc.png)

Firefox for Android and Chrome are able to display the page correctly, while Focus and Rocket cannot.

**Comment by mTwTm** [comment]
IIRC, changing some zooming related webviewsettings will fix this. There may be a discussion somewhere around why we didn't enable these setting but I can't find them now.

**Comment by chianger** [comment]
dup of #1284
