### ISSUE TITLE
Experiment: Wifi Finder Offering (Landing Page Test)

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1821]

**Comment by weslyhuang** [comment]
need engineering study for some design input.

**Comment by Jacklin-ux** [comment]
UX draft spec: https://drive.google.com/file/d/13-4IUB4DKoEi2apWJqHLTMZrsX3v7ELb/view?usp=sharing

**Comment by chianger** [comment]
visual design will come soon. this is sibling to #1820

**Comment by Pekochen** [comment]
wifi & vpn visual spec:
https://drive.google.com/open?id=1XULh6sqI2RxECra_aqvVAmUF9V9hqaiF
assets:
https://drive.google.com/open?id=1Fl0lnHb7ePeMJ1LsWvqq6UHwnICyPIfh
preview:
https://drive.google.com/open?id=1OeFAdt3wuyAYJShRtnOAfqiMUbGzLyxC

**Comment by elin-moco** [comment]
@cnevinc My suggested event structure would be (in method/object/value format):
Click on Wifi Finder Button: click/home/wifi_finder
Click "Yes" on Wifi Finder Doorhanger: click/doorhanger/positive (extra: {source: wifi_finder})
Click "No" on Wifi Finder Doorhanger: click/doorhanger/negative (extra: {source: wifi_finder})
Dismissed Wifi Finder Doorhanger: click/doorhanger/dismiss (extra: {source: wifi_finder})
We'll need to put "wifi_finder" in extra for the doorhanger so that we can compare metrics in A/B testing.
I'll separate a dashboard to visualize the extra information.

**Comment by cnevinc** [comment]
Please help answer below question for data review:

1) What questions will you answer with this data?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

* Establish baselines or measure changes in product or platform quality or performance.

* Provide information essential for advancing a business objective such as supporting OKRs.

* Determine whether a product or platform change has an effect on user or browser behavior.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

4) Can current instrumentation answer these questions?

5) List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>


6) How long will this data be collected?  Choose one of the following:

* This is scoped to a time-limited experiment/project until date MM-DD-YYYY.

* I want this data to be collected for 6 months initially (potentially renewable).

* I want to permanently monitor this data. (put someone’s name here)

7) What populations will you measure?

* Which release channels?

* Which countries?

* Which locales?

* Any other filters?  Please describe in detail below.

8) If this data collection is default on, what is the opt-out mechanism for users?

9) Please provide a general description of how you will analyze this data.

10) Where do you intend to share the results of your analysis?

**Comment by chianger** [comment]
_1. What questions will you answer with this data?_
We want to know if user would like VPN or WIFI finding functions.

_2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?_
We need more information from the user so we can further make plan for new features.

_3. What alternative methods did you consider to answer these questions? Why were they not sufficient?_
We don't have any other than user survey, but that is not enough to get granular detailed data.

_4. Can current instrumentation answer these questions?_
No.

_5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki._
Category 2 “Interaction data”

_6. How long will this data be collected? Choose one of the following:_
We want to collect this data until end of 2018Q4 initially and then decide if we want this data to be collected going forward.

_7. What populations will you measure?_
All users in all channels.

_8. If this data collection is default on, what is the opt-out mechanism for users?_
The user can disable "Send usage data" in settings to opt-out.

_9. Please provide a general description of how you will analyze this data._
We'll use Firebase and STMO. Comparing retention rate and the screenshot usage over time.

_10. Where do you intend to share the results of your analysis?_
N/A. Data is for internal feature planning evaluation only
