### ISSUE TITLE
In-app message methods for Firebase

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1845]

**Comment by Jacklin-ux** [comment]
Currently, we can use the templates we have in Firefox Rocket to fulfil current request. So please remove the "UX&VD Wanted" label.

**Comment by weslyhuang** [comment]
per 2.2 planning meeting, we need to clarify again the scope and expectation of this feature, thus move back to candidates for TOP20.

**Comment by weslyhuang** [comment]
need more detail about the requirement, may adjust title as well.

**Comment by chianger** [comment]
dup to #2515
