### ISSUE TITLE
Would be nice to revise UX spec for onboarding page

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1861]
UX spec: Firefox Rocket 2.1_v0.1.pdf, page 119

For example, the first onboarding page should be "Browse faster than ever"

**Comment by chianger** [comment]
@Jacklin-ux

**Comment by Jacklin-ux** [comment]
Updated
https://drive.google.com/drive/folders/1ai-4O9cbqtmWyY-j_8ZDaE-DelKCNkTP

Thanks
