### ISSUE TITLE
The image is still viewable after disabling storage access permission from System Settings

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#1862]
STR

   1. Install Rocket 2.0
   2. Launch Rocket 2.0
   3. Visit a website with images or files to download
   4. Long press on an image
   5. Press "Save image" from context menu
   6. Check from Gallery or File manager
   7. The image is downloaded correctly and viewable
   8. Disable storage access permission from System Settings\Permissions\Permissions\Storage\Rocket
   9. Check from Gallery of File manager
   10. The image is still viewable

https://drive.google.com/file/d/1CqS86x92Y-yHtJLJ_17xs6mbqyekieiS/view?usp=sharing

Expected result:

- Image is still viewable after disable storage access permission from System Settings

Actual result:

- Image should be not viewable after disable storage access permission from System Settings

Device: Redmi 4A
Rocket: 2.0.0(3585)
Android: 7.1.2
Webview: 65:0.3359.126

**Comment by chianger** [comment]
Per the conclusion from previous discussion in  #1351 , the current behavior (android 7) is expected. 
On Android 8 there's known issue in backlog => #1388 

See below quotes from #1351 
=================================
Expected result on Android 6 and Android 7:

    Image is still viewable

Expected result on Android 8:

    Ask for permission first
