### ISSUE TITLE
The description "Cache" on Clear browsing data function does not match SPEC

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#1869]
UX spec: Firefox Rocket 2.0_v0.2.pdf, page 103

The description "Cache" on Clear browsing data function does not match SPEC

The difference is defined "used cache size" on SPEC

- Rocket 2.0: Cache

- SPEC: Cache (7.3M)

**Comment by chianger** [comment]
Per discussion we'll update spec to get aligned with current working software.
