### ISSUE TITLE
Update telemetry wiki before we ship Firebase on Rocket

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#1876]
https://github.com/mozilla-tw/Rocket/wiki/Telemetry

**Comment by cnevinc** [comment]
I've updated the wiki in https://github.com/mozilla-tw/Rocket/wiki/Telemetry
I've also updated the wiki to align the code base at my best effort.

I also found that we collect extra events for App Launch, which are not included in previous data review.
I've created #1960 for this.
