### ISSUE TITLE
"Close all tabs" feature

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/Rocket#1878]
create and add to 2.2 milestone, per the 2.2 planning meeting on Apr. 25.

UX can add necessary content once available.

**Comment by carol-mozilla** [comment]
![screen shot 2018-05-03 at 10 34 09 am](https://user-images.githubusercontent.com/6700296/39557934-8b4a3bc6-4ebd-11e8-875b-5176af59337b.png)

**Comment by Jacklin-ux** [comment]
The spec for close all tabs
https://drive.google.com/file/d/1hJXmJiruLiU0utZmoxKYj_VypPO44ab6/view?usp=sharing

**Comment by carol-mozilla** [comment]
![screen shot 2018-05-03 at 6 25 21 pm](https://user-images.githubusercontent.com/6700296/39571822-60876f66-4eff-11e8-9cc7-19afd8103149.png)
Please update the text to all caps. Thanks!

**Comment by carol-mozilla** [comment]
![screen shot 2018-05-04 at 10 39 33 am](https://user-images.githubusercontent.com/6700296/39611102-892228f2-4f87-11e8-9605-78ab04adcbce.png)

**Comment by carol-mozilla** [comment]
![screen shot 2018-05-04 at 10 43 15 am](https://user-images.githubusercontent.com/6700296/39611148-08db8d36-4f88-11e8-8d92-680ebf083bf0.png)

**Comment by Jacklin-ux** [comment]
We can remove the "UX&VD Wanted" label.
