### ISSUE TITLE
Support of auto orientation between portrait/landscape mode

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#1890]
STR

1. Install Rocket 2.0
2. Launch Rocket 2.0
3. Visit a website "https://m.youtube.com/"
4. Put the device to landscape mode
5. The auto Orientation function does not work on the following situation:
- Youtube homepage 
- Video played in window mode

https://drive.google.com/open?id=14xCsKraBKo87wnvYo5pMTYswNFNcrc-t

Expected result:

- The auto orientation function work with landscape mode on Youtube website

Actual result:

- The auto orientation function does not work with landscape mode on Youtube website

Reproduce rate: 100%

Device: Redmi 4A
Rocket: 2.0.0(3585)
Android: 7.1.2
Webview: 65:0.3359.126

**Comment by mTwTm** [comment]
Currently we only support landscape when user enters full screen.

**Comment by chianger** [comment]
And only fullscreen playback will get you the landscape mode.
Rocket currently has only portrait mode.

**Comment by mTwTm** [comment]
I think this one is a duplicate to #1231
