### ISSUE TITLE
Find in page

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1891]
From Google Play reviews, seems like search is the next hottest user request after multi-tab. However personally I think it's very hard to implement with pure webview.

**Comment by Pekochen** [comment]
Here are some layouts for find in page design.
Please check here 
https://drive.google.com/open?id=1ddJkhkAI60hB28c7DGaayW8U-nWwxshU

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1ErT0QMCUx6iSB7ISR1Y5PdbOLgkKdPoL/view?usp=sharing

**Comment by Pekochen** [comment]
current visual spec for find in page
https://drive.google.com/open?id=1n3QI2XWij3OsNV4jhVLMt3Lfp4IZi4a0

**Comment by chianger** [comment]
this is a big user story which we probably want to break it down.

**Comment by chianger** [comment]
This is XL size so we actually can't do it in a sprint. 
I'm replacing this by #2514 in sprint C.

**Comment by Pekochen** [comment]
upload find in page icon
https://drive.google.com/open?id=1YnPJ0HZWauNarddan4a-fNuEYwKJHKad

**Comment by walkingice** [comment]
Discussed with @elin-moco , in current design there is no search suggestion in Find-in-page, so we won't add telemetry for that. For easier implementation, to use 'other' to instead of 'open_link' on dismissing find-in-page telemetry.
