### ISSUE TITLE
Often see tab number showing 0 and then jump to the correct number when relaunch Rocket (sometimes the lag is long)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1892]
STR:
 1. Launch Rocket 
 2. Add some tabs
 3. Tap system Back key
 4. Tap system Back key
 5. Launch Rocket again
 6. Repeat step 3 to step 5 

Expected result:
 - show the correct number

Actual result: 
 - Often see tab number showing 0 and then jump to the correct number when relaunching Rocket (sometimes the lag is long) 
 - Video: https://drive.google.com/open?id=1lLWR0ohxJOBS8sOG3X7csdmmtCQEXeSv

Reproduced rate: 2/3

Device: Pixel 2 and Redmi Note4
Rocket: 2.0.0(4006).night and 2.0.0(3585)
Android version: 8.1.0 and 7.0
WebView version 65.0.3325.109

**Comment by chianger** [comment]
we would like to see the smiley face instead of 0.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8.1.0
Rocket 2.1.1(4696).nightly 
WebView 67.0.3396.68
