### ISSUE TITLE
The content will be moved when tapping url bar in some websites 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1895]
STR:
 1. Launch Rocket 
 2. Go to pinterest.com
 3. Tap Url bar 

Expected result:
 - The content will not be moved 

Actual result: 
 - The content would be moved 
 - Video: https://drive.google.com/open?id=108STiRuhkwIvTr8nYWUh2J_l_-_V-De2 

Reproduced rate: 5/5

Device: Pixel 2 and Redmi Note4
Rocket: 2.0.0(4006).night and 2.0.0(3585)
Android version: 8.1.0 and 7.0
WebView version 65.0.3325.109

**Comment by chianger** [comment]
minor visual impact.

**Comment by chianger** [comment]
and it's probably on purpose so that the keyboard won't overlap website's text input box. for instrance, duckduckgo.
