### ISSUE TITLE
Nothing happens after tapping Menu -> Settings -> About -> Learn More -> Share on Twitter

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1899]
STR:
 1. Launch Rocket 
 2. Tap Menu -> Settings -> About -> Learn More
 3. Scroll down and Tap "Share on Twitter" 

Expected result:
 - A user can share it on Twitter

Actual result: 
 - Nothing happens
 - Video: https://drive.google.com/open?id=1_l0Mz8USJtkY5Bb8q7vuP5IfBuLXJO8R 

Reproduced rate: 5/5

Device: Pixel 2
Rocket: 2.0.0(4045).night and 2.0.0(3585)
Android version: 8.1.0 
WebView version 67.0.3396.29

**Comment by chianger** [comment]
Interesting. I used rocket to go to that page "https://www.mozilla.org/en-US/about/manifesto/" directly and the twitter button works.

**Comment by mTwTm** [comment]
We have different webvies settings applied to normal webviews (tab webview) and setting webview

**Comment by chianger** [comment]
It's likely a regression so change to S1

**Comment by benjamin-cheng** [comment]
Same root cause as #1930
