### ISSUE TITLE
Failed to swipe down the screen to update Facebook's page

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1905]
STR:
 1. Launch Rocket 
 2. Login Facebook with your account and password
 3. Swipe down the screen to update Facebook's page

Expected result:
 - A user can swipe down the screen to update Facebook's page 

Actual result: 
 - Nothing happens. Turbo mode off doesn't help
 - This issue can be reproduced in Rocket 
    - Rocket: https://drive.google.com/open?id=1W64SwAeo2qwqq16SMwNOVCDQkFsjinIc

 - This issue cannot be reproduced in Chrome  
    - Chrome: https://drive.google.com/open?id=1BHf18PwT74YdY62yvf8iwrNsrI7BakTt

Reproduced rate: 3/3

Device: Pixel 2
Rocket: 2.0.0(4045).night 
Android version: 8.1.0 
WebView version 67.0.3396.29

**Comment by chianger** [comment]
a dup to pull to refresh feature, which we dont' have yet.

**Comment by chianger** [comment]
dup to #40
