### ISSUE TITLE
Private browsing mode

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#1909]
Accounting to "Report for Firefox Rocket" user feedback, many users would like to have private browsing mode in our Rocket.

Pending bugs
----------------
#2244 Add Telemetry

**Comment by joechengla** [comment]
related https://github.com/mozilla-tw/Rocket/issues/1622

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/16PCV-2OY6ZfstVYw0x79MQXrX_YQEdHE/view?usp=sharing
Peko will deliver transition design and visual spec later :)

**Comment by cnevinc** [comment]
Plan:
- [ ] Make Private Mode behind a runtime switch
- [ ] Open/leave Private Mode
- [ ] Browsing a web page in private mode
- [ ] Notificaiton interaction

**Comment by Pekochen** [comment]
here is 2.4 visual spec
https://drive.google.com/open?id=1qSeFuQMxZELxw-MRTxBpjDP0ZJkJOzfw

**Comment by Pekochen** [comment]
transition reference
1.https://drive.google.com/open?id=18bMcK5oGarYPevaIpuTxXY9U2gvQPduh
2.https://drive.google.com/open?id=11-93SNc8-6p0Kb4IPjWmQyOh1aRO57qu

**Comment by chianger** [comment]
meta bug closed as feature complete
