### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#1910]
Accounting to "Report for Firefox Rocket" user feedback, many users would like to have night mode in our Rocket.

**Comment by weslyhuang** [comment]
plan to get BJ's support for this feature. UX to provide the icon for the first version.

**Comment by Pekochen** [comment]
Night mode visual spec:
https://drive.google.com/open?id=1hVFl_GxvzbSRl51xXUpo5XIwMf2Mbcpt

**Comment by Pekochen** [comment]
According to engineer's request, add the previous spec of normal mode
https://drive.google.com/open?id=12EfqIPRc_uZJjkoCHdO0ApbFyDDXTf55

**Comment by weslyhuang** [comment]
use prototype to check first. ship or not depends on the damage situation of main top 20~25 sites (focus on "article/shopping" sites) of target countries.

**Comment by cnevinc** [comment]
Please download the app-focus-webkit-firebase.apk in deploy.zip.
here's the link
https://app.bitrise.io/build/c370f1645728d2d5

**Comment by weslyhuang** [comment]
possible alternative: don't play with color but allow users to adjust brightness.

**Comment by weslyhuang** [comment]
1. a test apk with adjustable lightness
2. UX try and decide the lightness levels
3. design UX (e.g., scroll bar) for it

**Comment by Jacklin-ux** [comment]
UX draft spec: https://drive.google.com/file/d/1zPToaAZmnt1BfqKCo0oX8H_GNb0_H9Wr/view?usp=sharing

**Comment by Pekochen** [comment]
update night mode visual spec and add brightness adjust control panel
https://drive.google.com/open?id=1vkONwjHSwk-gZglY4lekVfde2_zZjsMc
assets:
https://drive.google.com/open?id=16hT0x5xOQbmps5qElMp6UiRFvn-7YdIT
preview:
https://drive.google.com/open?id=1YKEr-qMtvC0LPAjUWht2OVeLYpuSseEa

**Comment by chianger** [comment]
we have prototype for adjusting lightness in place, for parameter tuning. 
still need to figure out use cases for "exiting"  night mode so this keeps in design.

**Comment by chianger** [comment]
correction for above comment:
let's take that auto-exit night mode use case as a follow up feature.

**Comment by chianger** [comment]
size-wanted because we're not sure what telemetry needed for this feature. that's a dependency for the implementation.
Telemetry-wanted for @joechengla @elin-moco to comment on the telemetry
Keep size wanted but the rough assessment is this likely larger than L.

**Comment by elin-moco** [comment]
Hi @chianger  @cnevinc  @josephyu1110 , 

Here is the suggested event format (in method/object/value/extra):
Click "Night mode" on Menu: change/menu/night_mode/{to: true|false}
Change "Night mode brightness":  change/setting/pref_night_mode_brightness/{source: menu|setting, to: 0-100|auto}

Let me know if any questions.

Thank you!

**Comment by chianger** [comment]
tagging sprint Everest but we're aware of its size:XL so very likely to ship at sprint Fuji-san.

**Comment by chianger** [comment]
as this is cross-sprint ticket, please pref on landed features for dev/nightly builds so that we can test earlier.

**Comment by josephyu1110** [comment]
> Change "Night mode brightness": change/setting/pref_night_mode_brightness/{source: menu|setting, to: 0-100|auto}
@elin-moco 
I suggest to shorten the value name "pref_night_mode_brightness" to "night_mode_brightness" since there's a length limit we just hit it. What do you think?
>>>
java.lang.RuntimeException: Event[change__setting__pref_night_mode_brightness] exceeds Firebase event name limit 43 of 40

**Comment by mTwTm** [comment]
Fixed, please file independent bugs if there is any.

**Comment by josephyu1110** [comment]
1. What questions will you answer with this data?
We want to know how user interacts with the "Night mode" function.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
We need more information from the user so we can enhance the user experience on the "Night mode" feature and also further make plan for new features

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
We don't have any other than user survey, but that is not enough to get granular detailed data.

4. Can current instrumentation answer these questions?
No.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
Category 2 “Interaction data”

6. How long will this data be collected? Choose one of the following:
We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.

7. What populations will you measure?
All users in all channels.

8. If this data collection is default on, what is the opt-out mechanism for users?
The user can disable "Send usage data" in settings to opt-out.

9. Please provide a general description of how you will analyze this data.
We'll use Firebase and STMO. Comparing retention rate and the screenshot usage over time.

10. Where do you intend to share the results of your analysis?
N/A. Data is for internal feature planning evaluation only

**Comment by josephyu1110** [comment]
Data review and telemetry wiki is updated.
