### ISSUE TITLE
Unable to set default browser 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1926]
Build 4341. Unable to set default browser
Sony Z3C android 6.0.1

**Comment by joechengla** [comment]
I saw it work once, the first time when nightly is taking over default browser from Rocket release.

Then I changed the default browser to other browsers and tried to set default browser again in rocket nightly, it never worked again

**Comment by chianger** [comment]
With the STR above, I can also reproduce with Samsung J7 (android 6.0.1).

**Comment by cynthiatang** [comment]
Hi @joechengla, 

Test cases 1: 
1. Set Firefox Focus as the default browser
2. Install Rocket
3. Launch Rocket
4. Go to Menu -> Settings
5. Tap "Make default browser"
6. Wait for 1 min
7. Select Firefox Rocket as default browser Check the status of "Make default browser"    
10. Select Firefox Rocket as default browser 
11. If Rocket is not the first item, repeat step7 to step10
12. Go back to Rocket's settings "

Expected: 

Video: https://drive.google.com/drive/folders/1szlQCYCvyuuifIDleaiD7Q-j5AHacc0N 

Device: Nexus 5

**Comment by NashTung** [comment]
This issue can be reproduced.
Video:
https://drive.google.com/open?id=1t1h75nxXk4WMZXA_7qJlQo3avWtHPyjT

Device: Advan i5C
Rocket: 2.0.0(4354).nightly
Android: 5.1
Android Webview: 51.0.2704.81

**Comment by cynthiatang** [comment]
Unable to set default browser
 - Vivo 1606    Android 6.0.1
 - Sony Z3C    Android 6.0.1
 - Nexus 5    Andorid 6.0.1

Able to set default browser
 - Oppo    Android  5.1.1
 - Acer GT810    Android 5.1 

Rocket 2.0.0(4354).nightly
Webview 66.0.3359.158

**Comment by NashTung** [comment]
Able to set default browser
Video:
https://drive.google.com/open?id=1t1h75nxXk4WMZXA_7qJlQo3avWtHPyjT

Device: Advan i5C
Rocket: 2.0.0(4354).nightly
Android: 5.1
Android Webview: 51.0.2704.81

**Comment by walkingice** [comment]
this issue should be resolved in #1942

**Comment by cynthiatang** [comment]
Verified: fixed

For Android 6.x, it would be redirected to the Make default browser page 

Nexus 5 & Sony Z3C
Android 6.0.1
Rocket 2.1.0(4414)
Webview 66.0.3359.158
