### ISSUE TITLE
Unable to unset default browser 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1927]
Build 4341. 
Sony Z3C android 6.0.1

When I try to uncheck default browser, I was taken to Firefox rocket nightly app info page. Is this expected?

**Comment by chianger** [comment]
From that app info page, user can deselect the default browser. I guess this is expected.
@Jacklin-ux ?

**Comment by chianger** [comment]
confirmed with jack that this is expected behavior.
