### ISSUE TITLE
Can't open the links in License page

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1930]
![screenshot_20180516-154055](https://user-images.githubusercontent.com/6755074/40103330-a898fce6-591f-11e8-9769-1632e9b785c9.png)

Can't open the Zelda and telemetry item. BTW the contents needs an update cause both projects have moved.

**Comment by chianger** [comment]
It's likely a regression so change to S1

**Comment by benjamin-cheng** [comment]
Duplicated with #1899
