### ISSUE TITLE
Failed to open system set deafult browser panel after tapping "Tap to set default browser"

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1931]
STR:
1. Set Chrome as a default browser
2. Launch Rocket 
3. Go to the settings page (Tap menu -> settings)
4. Tap "Make default browser" 
5. Leave Rocket settings page (ex., go to system Home)
6. Wait for 1 min
7. Tap the notification "Tap to set default browser"

Expected result:
 - Back to Rocket Settings page and open system set deafult browser panel
 - Spec.:
   <img width="365" alt="screen shot 2018-05-16 at 5 26 51" src="https://user-images.githubusercontent.com/12458450/40108747-6da009e0-592e-11e8-87a0-ca96ad67365e.png">

Actual result: 
 - Failed to open system set default browser panel
 - Video: https://drive.google.com/open?id=1WPNa7-8kRuK3zAMJIrtINduU2TwgaHFy 

Reproduced rate: 3/3

Device: Nexus 5
Rocket: 2.0.0(4341).night 
Android version: 6.0.1
Webview: 66.0.3359.158

**Comment by chianger** [comment]
6.0 by updated spec is expected to redirect user to sumo
