### ISSUE TITLE
Notifications with wrong icons:  Tap to set default browser, Changing settings...

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1932]
STR:
1. Set Chrome as a default browser
2. Launch Rocket 
3. Go to the settings page (Tap menu -> settings)
4. Tap "Make default browser" 
5. Leave Rocket settings page (ex., go to system Home)
6. Wait for 1 min

Actual result:
 - ![screenshot_20180516-174726 2](https://user-images.githubusercontent.com/12458450/40110061-9f14d8b8-5931-11e8-9db7-84d5101c1ca5.png)
 - ![screenshot_20180516-174722 2](https://user-images.githubusercontent.com/12458450/40110063-a0a09456-5931-11e8-9fe2-dddcec303926.png)

Reproduced rate: 3/3

Device: Nexus 5
Rocket: 2.0.0(4341).night 
Android version: 6.0.1
Webview: 66.0.3359.158

**Comment by chianger** [comment]
S1 P1 but non-blocking to 2.1.
