### ISSUE TITLE
automate l10n strings import

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#1939]
current integration of localized string is to manual import.
as rocket dev, we would like to have this process automated.

**Comment by weslyhuang** [comment]
a good to have when we want to add more locales

**Comment by mTwTm** [comment]
I'm interested in this one, self-assigned but let's discuss when do we have some bandwidth for this one.

**Comment by weslyhuang** [comment]
per discussion in SF all-hands this is not super urgent now, removed from 2.3.

**Comment by mTwTm** [comment]
All works are on CI and it's done.
