### ISSUE TITLE
[debug build only] Can't browse mozilla.org

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#1947]

**Comment by mTwTm** [comment]
There's a SslError. Why?

**Comment by mTwTm** [comment]
error.hasError(SslError.SSL_UNTRUSTED) ...why?

**Comment by cynthiatang** [comment]
Hi @mTwTm , I cannot reproduce it. Could you please try it again? Thanks :)
https://drive.google.com/open?id=1AEl290HFEnXE4v8lPXvrdGdcojOLkB0o

**Comment by mTwTm** [comment]
Not exist anymore in the latest version of dev version. (Sidenote: dev is not release and is neither Nightly, though.)
