### ISSUE TITLE
Incorrect Notification behavior when multiple notification is shown.

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#1948]
STR:
1. Install Rocket 1.x or 2.0
2. Launch Rocket
3. Update to Rocket 2.1
4. Launch Rocket   
    - Result: Show onboarding page for the exited user.  (We heard your feedback! 1. multiple tabs 2. add to Home)
5. Tap "OK, GOT IT!" 
6. Tap Settings
    - Result: Show the notification "Make default browser?"
7. Close Rocket
8. Relaunch Rocket 
    - Result: Show the notification "Product Update Notice"
9. Tap the notification "Product Update Notice"

Expected result:
 - Go to the page for "Product Update Notice"
 - Image
    ![screenshot_20180518-112848](https://user-images.githubusercontent.com/12458450/40214778-45017318-5a8f-11e8-9bfd-d65f10b08ebf.png)

Actual result: 
 - Go to the page for "Make default browser?"
 - Other Rocket notification disappears
 - Video: https://drive.google.com/open?id=1iEJf_q1IVODwUrpgRv4LJrbhnLN1f-Tb
 - Image:
    ![screenshot_20180518-112822](https://user-images.githubusercontent.com/12458450/40214784-48d45438-5a8f-11e8-8390-d67bec9fd2ca.png)

Reproduced rate: 3/3

Device: Nexus 5
Rocket: 2.0.0(4390)
Android version: 6.0.1
Webview: 66.0.3359.158

**Comment by mTwTm** [comment]
I think the user should start with 1.X to have step 4. Tried with 2.0 and my STR is more like:


1. Install Rocket 2.0
2. Launch Rocket
3. Update to Rocket 2.1
4. Launch Rocket
5. Show the notification "Product Update Notice"
~Result: Show onboarding page for the exited user. (We heard your feedback! 1. multiple tabs 2. add to Home)~
~Tap "OK, GOT IT!"~
6. Tap Settings twice
7. Result: Show the notification "Make default browser?"
8. Tap the notification "Product Update Notice"
9. Tap the notification "Make default browser?"
Expected: move to setting page
Actual: still on Privacy notice.

**Comment by cynthiatang** [comment]
Verified: Fixed 

Device: Oppo
Rocket2.1.0(4414)
Android Version: 5.1.1
WebView Version 66.0.3359.158
