### ISSUE TITLE
Telemetry events not copied to FIrebase 

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#1963]
Follow up for #1759
Currently found:

Screenshots.                      | click    | menu |  capture 
add-to-homescreen sites | launch | app    |  shortcut

**Comment by chianger** [comment]
[uplift] flag to go into 2.1

**Comment by cynthiatang** [comment]
Verified: Fixed

Rocket 2.1.0(4491).nightly
WebView: 66.0.3359.158
Sony Z3C 
Android: 6.0.1
