### ISSUE TITLE
Experiment: Screenshot on-boarding (Drive users towards MyShots)

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1968]
Idea from Max; show a blue dot when users has unread screenshots in MyShots.

**Comment by joechengla** [comment]
Two scenarios 
1. Screenshot on-boarding (first time screenshot use)
2. Unread Screenshots (subsequent screenshot use)
We want to be able to remote config the 2 scenarios so we can compare results of A/B testings
Key metrics to track:  MyShot access conversion and Screenshot view conversion

**Comment by joechengla** [comment]
strings for the screenshot onboarding: View your screenshot here

**Comment by chianger** [comment]
![screen shot 2018-05-29 at 6 38 14 pm](https://user-images.githubusercontent.com/9859809/40701992-b79715c2-6412-11e8-8e0b-fa4c330c46c5.png)

**Comment by carol-mozilla** [comment]
Here's the visual spec and assets: https://drive.google.com/open?id=1SU47xMvurwdVlul943ToIKT3N_AYPkc_

**Comment by weslyhuang** [comment]
(2) is done, (1) todo. And string for (1): "View your screenshot here", removed UX label.

1. Screenshot on-boarding (first time screenshot use)
2. Unread Screenshots (subsequent screenshot use)

**Comment by weslyhuang** [comment]
fable would like to confirm
1. the onboarding will open the menu automatically after 1st screenshot?
2. the flow to dismiss onboarding

**Comment by Jacklin-ux** [comment]
1.Yes (show the menu just one time)
2.Can do 
    1) Press other grey area to close the onboarding
3.

**Comment by Pekochen** [comment]
New visual spec 
https://drive.google.com/open?id=1QUnjKLARmBDMOJkdfwOr4VAstHNR4tw9

**Comment by josephyu1110** [comment]
> 2.Can do?
> 1) Press other grey area to close the onboarding
> 2) Press "My shots" (circle area) then open my shots panel
Above requirements are doable and already include in the referenced PR.

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1b3JMx1j11L9Rddwix2tV6RqG4sC9e7lR/view?usp=sharing
Please let me know if anything missing. Thanks :)
