### ISSUE TITLE
User feedback: Force closed every time i tried to save images

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1972]

**Comment by cynthiatang** [comment]
It works for me.

1. Visit Twitter, Facebook, Liputan6, Tribunnews, Tokopedia, Bukalapak or Google Drive
2. Long Tap on any image
3. Tap Save image

Actual result: 
 - A user can save images. No force closed. 

Rocket 2.1.0(4414)
WebVidw 66.0.3359.158

=========================
Oppo A37f
Android 5.1.1
=========================
Sony Z3C 
Android 6.0.1
=========================
Redmi 4X
Android 7.1.2
=========================
Pixel 2
Android 8.1.0

**Comment by chianger** [comment]
QAWanted to test on acer tabler and advan. If it cannot be repro then let's close as WORKSFORME

**Comment by cynthiatang** [comment]
Hi @NashTung , Could you please verify it in Advan? Thanks :)

**Comment by NashTung** [comment]
It works for me.

Device: Advan i5C
Rocket: 2.1.0(4414)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
This issue cannot be reproduced.

Acer: GT-810
Android: 5.1
Rocket: 2.1.0(4551).nightly
WebView: 66.0.3359.158
