### ISSUE TITLE
Deeplinks -> Goto Android Set Default App page (Android 7.0+) through Firebase

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1983]

**Comment by chianger** [comment]
@Jacklin-ux to chime in

**Comment by joechengla** [comment]
when we push a notification to remind users to set Rocket as default browser, when user tap on the notification, we'd like to take users directly to Android system app setting directly instead of taking users to Rocket settings

**Comment by weslyhuang** [comment]
may break users' current workflow. e.g., what if users press "back"? "recent app"? ...

**Comment by cnevinc** [comment]
Question: 
Do we want other apps to use this deep link? I guess only Rocket will need this.
In that case, we don't need a real [deep link](https://developer.android.com/training/app-links/deep-linking). We just need to fire some command ( in the push/notification's payload, passed by RemoteMessage or intent extra ) and handle that. Why not call it a command or internal deep link?
