### ISSUE TITLE
The webpage does not reload again after setting Block image icon from on to off

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#1989]
STR

1. Install Rocket 2.0
2. Launch Rocket 2.0
3. Visit any website
4. Tab Block image icon to on
5. The web page is reloaded and image is block properly
6. Tab Block image icon to off
7. The web page is not reloaded and image displayed

Video: https://drive.google.com/open?id=1rj5P6YQZ5XfuhabklkhG9UKe3EmdA-9-

Expected result:

- The web page is reloaded again after setting Block image function from on to off

Actual result:

- The web page is not reloaded again after setting Block image function from on to off

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.0(4414)
Android: 5.1
Android Webview: 67.0.3369.49

Device: Redmi 4A
Rocket: 2.1.0(4414)
Android: 7.1.2
Android Webview: 66.0.3359.158

**Comment by chianger** [comment]
QAWanted: according to the video it seems the "images" does reload as expected. What's considered unexpected here?

**Comment by chianger** [comment]
RESOLVED INVALID
