### ISSUE TITLE
It takes more time (4 minutes) to display the error page when visiting page 192.168.1.1 (only HTC Desire 10 pro)

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#2003]
STR

1. Install Rocket 2.1.1
2. Launch Rocket 2.1.1
3. Visit page 192.168.1.1

Video: https://drive.google.com/open?id=1laFD-zGyB-gLNmKdsEbee-byjZLa6aVc

The issue does not on the following phone:
1. Advan i5C (35 seconds) 
2. Redmi 4A (10 seconds)

Expected result:

- It takes less time to display the error page

Actual result:

- It takes more time to display the error page
- It takes more time (4 minutes) to display the error page

Reproduce rate: 100%

Device: HTC Desire 10 pro
Rocket: 2.1.1(4587)
Android: 6.0
Android Webview: 66.0.3359.158

**Comment by NashTung** [comment]
Update info on other browsers for HTC Desire 10 pro:
1. UC (12.5.0.1109(): 75 seconds
2. Chrome (56.0.2924.87): 4 minutes
3. Opera (35.0.2254.127755): 3 minutes 58 seconds

**Comment by chianger** [comment]
Suggest updating the test cases to a.b.c that doens't actually exist, if the testing purpose it for checking non-response . @cynthiatang

**Comment by chianger** [comment]
CLOSE as WON"TFIX
