### ISSUE TITLE
"Close all" can still be tapped with only one tab 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2008]
(Issued by Joe)

STR:
1. Launch Rocket with one tab
2. Open the tab tray
3. Tap "Close all"

Expected result:
 -  "Close all" cannot be tapped with only one tab 

Actual result:
 - "Close all" can still be tapped with only one tab 
 - Video: https://drive.google.com/open?id=1cc7vk5eTj27MDjAyibHib3QrjF8FSmXr

Device: Sony Z3C 
Android: 6.0.1
Rocket: 2.1.1(4599).nightly
WebView: 66.0.3359.158

**Comment by pharspher** [comment]
As discussed with @Jacklin-ux, this is expected behavior.
