### ISSUE TITLE
"Close all" does not feel like an actionable button?

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2009]
(Issued by Joe)

STR:
1. Launch Rocket with one tab
2. Open the tab tray
3. Tap "Close all"

Expected result:
 -  "Close all" feel like an actionable button

Actual result:
 - "Close all" does not feel like an actionable button
 - Image: 
![screenshot_2018-05-28-15-50-13-911_gro allizom zelda beta](https://user-images.githubusercontent.com/12458450/40606265-696f2992-6297-11e8-9455-995c9296c63f.png)

Device: Sony Z3C 
Android: 6.0.1
Rocket: 2.1.1(4599).nightly
WebView: 66.0.3359.158

**Comment by carol-mozilla** [comment]
Update visual spec: https://drive.google.com/open?id=1HJg8E23eXMxEJhRJt2dFSiqGggxVvQR9

**Comment by carol-mozilla** [comment]
![tab tray -close all](https://user-images.githubusercontent.com/6700296/40643286-2f28313c-6352-11e8-9afe-09ff0f876b25.png)

**Comment by cynthiatang** [comment]
Verified: fixed

Redmi 4X
Android 7.1
WebView: 2.1.1(4696).nightly
WebView version 66.0.3359.158
