### ISSUE TITLE
Should bump the version to 2.2 now

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2015]
(Issued by Wesley)

STR:
1. Launch Rocket
2. Go to Menu -> Setting -> About 
3. Check the version of Rocket

Expected result:
 -  Should bump the version to 2.2 now

Actual result:
 - It is 2.1.1(4599).nightly

Device: Sony Z3C 
Android: 6.0.1
Rocket: 2.1.1(4599).nightly
WebView: 66.0.3359.158

**Comment by mTwTm** [comment]
Fixed in #2047

**Comment by cynthiatang** [comment]
Verified: fixed 

Nexus 5
Android 6
Rocket 2.2.0(4809).nightly
WebView: 66.0.3359.158
