### ISSUE TITLE
The notification "Changing setttings...It may take a while" does not show after setting Make default browser to on. 

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#2020]
STR

1. Set Chrome as default browser by using Gmail app (3rd app) to open a link
2. Install Rocket 2.1.1
3. Launch Rocket 2.1.1
4. Tab Make default browser to on
5. The notification "Changing setttings...It may take a while" does not show up.

Video: https://drive.google.com/open?id=1WkR8pLDeVR5dKHY_28iXiHlkEw45tiyP

Expected result:

- The notification "Changing setttings...It may take a while" should show up.

Actual result:

- The notification "Changing setttings...It may take a while" does not show up.

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.1(4587)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
This issue cannot be reproduced on Nexus 5 with Android5.1.1.

**Comment by chianger** [comment]
No actual user impact.

**Comment by chianger** [comment]
per discussion the notification is designed for situation that prompt comes out late. 
In the video the prompt pops up immediately so it's really no user impact. 
Close as WON"TFIX
