### ISSUE TITLE
Failed to show the full content after opening an AD in the new tab

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2027]
STR:
1. Launch Rocket 
2. Tap the topsite "Kapanlagi"
3. Wait for 30 seconds (It will show an AD at the top of the website)
4. Long Press the AD
5. Select "Open link in new tab"
6. Tap "SWITCH"

Expected result:
 - Show the full content 
 - After step3, it will show the full content 
 - Image:
    ![screenshot_20180529-180740](https://user-images.githubusercontent.com/12458450/40652925-416e6004-636c-11e8-9cea-5e635cf89087.png)

Actual result:
 - Failed to show the full content
 - Video: https://drive.google.com/open?id=16xemYClk-ysLsCb_4cAr8OR33IUUYHmo
 - Image:
    ![screenshot_20180529-180731](https://user-images.githubusercontent.com/12458450/40652915-3d1e241c-636c-11e8-82ba-c53ba71ee2a0.png)

Device: Pixel2 
Android: 8.1
Rocket: 2.1.1(4587)
WebView: 67.0.3396.59

**Comment by chianger** [comment]
Is turbo-mode on/off? Not sure if it makes any difference.

**Comment by cynthiatang** [comment]
Sorry, I could not reproduce it because the website changed the AD. I would like to close this issue.
