### ISSUE TITLE
Make default browser function does not be directed after pressing notification "Make default browser" when tab settings 2ed time

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#2030]
STR

1. Install Rocket 2.1.1
2. Launch Rocket 2.1.1
3. Tab settings 2ed time
4. The notification "Make default browser" shows up
5. Tab it and directed to Mozilla support page
6.  The Make default browser function on settings does not be directed

Video: https://drive.google.com/open?id=10nwJpAshtlgC1gdeFkjrwdeDwDWyjMWY

Expected result:

- The Make default browser function on settings is directed 

Actual result:

- The Make default browser function on settings does not be directed

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.1(4587)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
Invalid bug
