### ISSUE TITLE
Crash after tapping "Clear browsing data".   (java.lang.IllegalArgumentException: Exceeding limit of param content length:1132 of 100)

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#2033]
STR

1. Install Rocket 2.1.1.nightly
2. Launch Rocket 2.1.1.nightly
3. Tab "Clear browsing data" function
4. The error message "Firefox Rocket Nightly keeps stopping" shows and Rocket app crash

Video: https://drive.google.com/open?id=165npwXnuMfhFenpy0ip0WduM1mqb3PMj

The Rocket 2.1.1(4587) work fine

Expected result:

- The error message does not shows up and Rocket app works fine

Actual result:

- The error message shows and Rocket app crash

Reproduce rate: 100%

Device: Redmi 4A
Rocket: 2.1.1(4696).nightly
Android: 7.1.2
Android Webview: 67.0.3396.68

**Comment by cynthiatang** [comment]
--------- beginning of crash
05-31 11:41:43.247  5992  5992 E AndroidRuntime: FATAL EXCEPTION: main
05-31 11:41:43.247  5992  5992 E AndroidRuntime: Process: gro.allizom.zelda.beta, PID: 5992
05-31 11:41:43.247  5992  5992 E AndroidRuntime: java.lang.IllegalArgumentException: Exceeding limit of param content length:1132 of 100
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.telemetry.FirebaseEvent.safeParamLength(FirebaseEvent.java:83)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.telemetry.FirebaseEvent.param(FirebaseEvent.java:75)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.telemetry.TelemetryWrapper$EventBuilder.extra(TelemetryWrapper.java:720)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.telemetry.TelemetryWrapper.settingsEvent(TelemetryWrapper.java:289)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.settings.SettingsFragment.onSharedPreferenceChanged(SettingsFragment.java:143)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:497)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:397)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.utils.TopSitesUtils.saveDefaultSites(TopSitesUtils.java:93)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.utils.TopSitesUtils.getDefaultSitesJsonArrayFromAssets(TopSitesUtils.java:49)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at org.mozilla.focus.widget.CleanBrowsingDataPreference.onDialogClosed(CleanBrowsingDataPreference.java:56)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1355)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6205)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
05-31 11:41:43.247  5992  5992 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
05-31 11:41:43.591  2225  2273 I octvm_klo: klo lock
05-31 11:41:43.593  1513  5085 W ActivityManager:   Force finishing activity gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity
05-31 11:41:43.602  1513  5085 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
05-31 11:41:43.614  2476  2572 I WtProcessController: Receive am_crash event for pid: 5992 pkg = gro.allizom.zelda.beta
05-31 11:41:43.630  2476  2572 W KloServer: Aborted broadcast does not supprt for: gro.allizom.zelda.beta
05-31 11:41:43.647  1513  1529 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@f6356ca
05-31 11:41:43.647  1513  1529 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@bf9b03b
05-31 11:41:43.648  2225  2273 I octvm_klo: get wanted event[mask:128, name:data_app_crash@1527741703648.txt] from the watchset
05-31 11:41:43.648  2225  2273 I octvm_klo: start gathering logcat log...
05-31 11:41:43.655  2225  2273 I octvm_klo: gathering logcat log done
05-31 11:41:43.655  2225  2273 I octvm_klo: klo unlock
05-31 11:41:43.742  1513  6475 I OpenGLRenderer: Initialized EGL, version 1.4
05-31 11:41:43.743  1513  6475 D OpenGLRenderer: Swap behavior 1
05-31 11:41:43.991   673   765 D ThermalEngine: sensor_wait: case_therm Wait done.
05-31 11:41:43.993   673   765 D ThermalEngine: sensor_monitor: case_therm Reading 34000 .
05-31 11:41:43.993   673   765 I ThermalEngine: Sensor:case_therm:34000 mC
05-31 11:41:43.993   673   765 D ThermalEngine: update_active_thresh: case_therm Active(1), Hi(1) 42000, Lo(0) -2147483648, Interval(1) 1000
05-31 11:41:43.993   673   765 D ThermalEngine: sensor_monitor: case_therm Sensor wait.
05-31 11:41:43.993   673   765 D ThermalEngine: sensor_wait: case_therm Wait start. 1000ms
05-31 11:41:44.070   697  1336 I miuiFirewall: miui firewall always allow android
05-31 11:41:44.071   697  1336 I miuiFirewall: miui firewall always allow android
05-31 11:41:44.103  1513  1528 W ActivityManager: Activity pause timeout for ActivityRecord{a115fe3 u0 gro.allizom.zelda.beta/org.mozilla.focus.activity.SettingsActivity t394 f}
05-31 11:41:44.116  2476  2572 I WtProcessController: MOVE TO FOREGROUND: gro.allizom.zelda.beta 10157
05-31 11:41:44.117  2476  2572 I WtProcessController: FOREGROUND INFO: name=gro.allizom.zelda.beta uid=10157 pid=5992 TaskId:394
05-31 11:41:44.130  1513  1528 I Timeline: Timeline: App_transition_ready time:5746506
05-31 11:41:44.180  1513  1534 I Timeline: Timeline: App_transition_ready time:5746556
05-31 11:41:44.433  1513  6472 W ErrorReport: Fail to sendHttpRequest
05-31 11:41:44.433  1513  6472 W ErrorReport: java.lang.IllegalArgumentException: HTTP entity may not be null
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:115)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:151)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at miui.util.ErrorReport.tQ(SourceFile:396)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at miui.util.ErrorReport.sendReportRequest(SourceFile:353)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at miui.util.ErrorReport$1.wy(SourceFile:369)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at miui.util.ErrorReport$1.doInBackground(SourceFile:368)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-31 11:41:44.433  1513  6472 W ErrorReport: 	at java.lang.Thread.run(Thread.java:760)
05-31 11:41:44.436  1513  6472 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1458 android.content.ContextWrapper.bindService:646 miui.os.DropBoxManager.yG:361 miui.os.DropBoxManager.yF:350 miui.os.DropBoxManager.addText:314 
05-31 11:41:44.629 24976 24976 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
05-31 11:41:44.633 24976 24976 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=8 sndbuf=212992 outq=0 send_len=48
05-31 11:41:44.824  5992  6107 I CrashlyticsCore: Crashlytics report upload complete: 5B0F7CE402C9-0001-1768-899D69AEB3AC

**Comment by mTwTm** [comment]
We're sending a big object here:
TelemetryWrapper.settingsEvent(getKey(), flattenToJsonObject(getValues()).toString());

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Nexus 5
Rocket 2.2.0(4871).nightly
WebView version 66.0.3359.158
