### ISSUE TITLE
Show unread notification for new screen captures.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2035]
Part of #1968. Spec is also available there.

**Comment by cynthiatang** [comment]
Verified: it works

Rocket 2.1.1(4754).nightly
WebView: 67.0.3396.68


Android 5.1.1     OPPO A37f, Nexus 5
Android 6.0.1    Nexus 5
Android 7.0       Redmin Note 4, Galazy J7 Prime
Android 7.1.2    Redmi 4x 
Android 8.1.0     Pixel 2

**Comment by mTwTm** [comment]
I should have mentioned that this is controlled by Firebase.
