### ISSUE TITLE
"Close all tabs" not localized in Indonesian

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2039]
STR:
1. Launch Rocket with some tabs
2. Go to Menu -> Setting -> Language -> Select "Indonesia"
3. Open the tab tray (Tap system Back key twice and tap the tab tray)
4. Tap "CLOSE ALL"

Expected result:
 - "Close all tabs?" localized in Indonesian

Actual result:
 - "Close all tabs" not localized in Indonesian
 - Image:       
     ![screenshot_2018-05-31-13-26-27-921_gro allizom zelda beta](https://user-images.githubusercontent.com/12458450/40836613-ee36c6f0-65c9-11e8-9892-1580aa3245bc.png)

Device: Redmi 4A 
Android: 7.1.2
Rocket: 2.1.1(4731).nightly
WebView: 66.0.3359.158

**Comment by chianger** [comment]
This is supposedly to be verified. @NashTung @cynthiatang

**Comment by cynthiatang** [comment]
Verified: Fixed

Rocket 2.1.1(4754).nightly
WebView: 67.0.3396.68
Pixel 2
Android 8.1.0
