### ISSUE TITLE
Experiment follow-up: "invite referral" integration test

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2056]
#1809 has done validation from client side, in terms of adjust SDK + Rocket. 
This is the follow up to validate with the MKT team's web page.

**Comment by chianger** [comment]
just for tracking. external dependency is involved

**Comment by elin-moco** [comment]
Just confirmed that integration is done.
I'll setup the campaign and run some tests internally.
Hopefully we can get it live this week or early next week.

**Comment by chianger** [comment]
This was up and runnin
