### ISSUE TITLE
A dialog does not pop up on top of Home page when launching Rocket on 6th.

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#2062]
STR:

1. Launch\ Exit  Rocket and Kill the Rocket 5 times.
2. Launch Zerda (6th).

Video: https://drive.google.com/open?id=1fzTWDeXAqm-IcYvGu7cCBbTkht72I7E-

Expected result:

- A dialog is on top of Home page 

Actual result:

- A dialog does not pop up on top of Home page.

- Unless on 8th, a dialog is on top of Home page.

Reproduce rate: 50%

Device: Redmi4A
Rocket: 2.2.0 (4869)
Android: 7.1.2
Android Webview:  67.0.3396.68

**Comment by mTwTm** [comment]
Sounds like the experiment we're doing so I guess this might be an invalid issue. We should have documented or notified this. Sorry for the confusion Nash! @joechengla @cynthiatang to confirm.

**Comment by cynthiatang** [comment]
Hi @NashTung ,

Could you please disable "Send usage data" and test it again? Thanks. 

STR:
1. Install Rocket
2. Go to Menu -> Settings -> Disable "Send usage data"
3. Start the test

**Comment by chianger** [comment]
resolved invalid
