### ISSUE TITLE
Modify Error Page background color

### ISSUE THREAD

**Issue by carol-mozilla** [mozilla-tw/Rocket#2071]
![error page](https://user-images.githubusercontent.com/6700296/41711071-c9fa9c98-7579-11e8-8230-b60eb18470f3.png)
Adding a gradient to the background color of 'Error Page'
- Fit more into Photon design
- Visually will be less flat

**Comment by carol-mozilla** [comment]
![error page_spec](https://user-images.githubusercontent.com/6700296/42009073-47a308f6-7abb-11e8-9188-0d9c565e54e1.png)

**Comment by carol-mozilla** [comment]
![screen shot 2018-07-03 at 2 18 13 pm](https://user-images.githubusercontent.com/6700296/42201850-119815ac-7ecc-11e8-86f6-cd2f498fb0dc.png)
Update button spec

**Comment by chianger** [comment]
visual impact. S2

**Comment by chianger** [comment]
pull request #2079 is for this
