### ISSUE TITLE
Update some icons to the latest style

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#2082]
Change some icons in downloads panel to the latest style

**Comment by Pekochen** [comment]
hi, please help to update these icons.
https://drive.google.com/open?id=1D59sg2OzNmBpfI1gJcrhZ7fWpOZW0vBI
thanks!

**Comment by cynthiatang** [comment]
Verified: Fixed

Rocket 2.3.0(5271).nightly
WebView 67.0.33396.87
Nexus 5
Android 5.1.1
