### ISSUE TITLE
[urlbar] url/search bar cannot be shown on some Xiaomi devices (specific models)

### ISSUE THREAD

**Issue by bli-mozbj** [mozilla-tw/Rocket#2100]
Feedback from user 
-------------------------------
Device: Xiaomi 6X
Rocket v2.0

url/search bar cannot be shown on 18:9 aspect ratio screen

<img width="125" alt="145246su9ooqviuqiqo4l4" src="https://user-images.githubusercontent.com/25242209/42079838-5f1b07d8-7bb3-11e8-83bb-84a515bf613a.png">

**Comment by chianger** [comment]
action: figure out if this is keyboard specific

**Comment by chianger** [comment]
@bli-mozbj do you have idea is this still reproducible when using other keyboard?

**Comment by bli-mozbj** [comment]
This issue is from users' feedback, one user mentioned that the keyboard is Sogou Keyboard.
I can try to contact those users to see if they have other keyboards installed.

**Comment by chianger** [comment]
I tried sogou but it's not reproduced on Pixel XL. So it seems to require 18:9 and a specific keyboard.

**Comment by cynthiatang** [comment]
I don't have a device with 18:9 ratio. 

By the way, this issues cannot be reproduced in Redmi Note4 (16:9) and Lenovo A1000f (5:3).

Device: Xiaomi Redmi Note 4 
Resolution: 1080 x 1920 pixels, 16:9 ratio

![screenshot_2018-07-20-11-35-13-966_gro allizom zelda beta](https://user-images.githubusercontent.com/12458450/42990831-76f534f8-8c36-11e8-8cf6-7a5295279b9c.png)



Lenovo A1000:
Resolution, 480 x 800 pixels, 5:3 ratio

![screenshot_2018-07-20-15-56-08](https://user-images.githubusercontent.com/12458450/42990828-72c30c7a-8c36-11e8-8eef-593113115fb5.png)

**Comment by mTwTm** [comment]
Another report from Google Play:

Hi developer, please fix hidden address bar on 18:9 screen, i use xiaomi
redmi note 5, if i write text on address bar, text couldn't show, hidden.

**Comment by chianger** [comment]
Current information shows that Xiaomi 6x and Redmi note5 can reproduce.

**Comment by mTwTm** [comment]
Porbably related:

**Comment by mTwTm** [comment]
Yet another report from Google Play:
The seach bar remain hidden under the keyboard when I tab on it. Can't see what am I typing. Am I the only one who is facing this problem?

**Comment by joechengla** [comment]
Another reporting: Search bar get hidden by keyboard during typing. I can't see what I'm typing. Fix this issue ASAP. (Redmi Note 5 Pro)

**Comment by joechengla** [comment]
Another one: Layout not working with 18:9 screen. I can not see address bar while typing. (Redmi Note 5 Pro)

**Comment by joechengla** [comment]
Another one: Pls move the search bar a little higher it's getting blocker by keyboard. (POCO F1 (by Xiaomi)

**Comment by joechengla** [comment]
also reproduced by turning on display cutouts in developer options with Android 9
https://drive.google.com/file/d/1NTIlSqXPQkjvr9nJocdJTPyWZuCL52B6/view?usp=sharing

**Comment by chianger** [comment]
uplift to 3.2

**Comment by Daisy-pliu** [comment]
Verify :✅
device: Oppo R11s Plus (7.1.1),  screen 18:9
test result: see search bar
![Screenshot_2019-04-16-14-03-31-54](https://user-images.githubusercontent.com/44990878/56194414-845a8900-6065-11e9-836b-e7cdd59ac9e5.png)
