### ISSUE TITLE
Would be nice to keep the same sequence of bookmarks after editing a bookmark

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2105]
STR
1. Launch Rocket 
2. Add three bookmarks, e.g., Google, Yahoo, CNN
3. Go to Menu -> Bookmarks to view the bookmark list
4. Edit the bookmark at the top of bookmarks, e.g., Google
5. Tap Save

Expected Result 
 - Google ------> edited
   Yahoo
   CNN

Actual Result
 - Yahoo
    CNN
    Google ------> edited

Video: https://drive.google.com/open?id=1mL9xuCOVXeU3I3U2V7flpMqh2DA3i49y

Reproduce Rate: 3/3

Device: Pixel 2
Android 8.1.0
Rocket 2.2.0(5192).nightly
WebView: 68.0.3440.34

**Comment by chianger** [comment]
@Jacklin-ux input from UX?

**Comment by Jacklin-ux** [comment]
Agree. I suggest to put the edited bookmark in the place where is before editing as well. Currently, if the list is long and after the bookmark is edited, it's hard for users to find the edited bookmark in the list, they need to swipe the list to the end to see it.

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Pixel2
Android 8.1.0
Rocket 2.2.0(5257).nightly
WebView: 68.0.3440.34
