### ISSUE TITLE
Bottom toolbar suddenly become translucent

### ISSUE THREAD

**Issue by fauzanalfi** [mozilla-tw/Rocket#2109]
![photo_2018-06-30_18-22-55](https://user-images.githubusercontent.com/1860909/42124766-0afbdfca-7c93-11e8-9b42-d2e4f6c81fd3.jpg)

As I posted in Telegram group, I found out that the bottom toolbar suddenly become translucent after opening browsing some websites still in the same tab. Device I used is Xiaomi Redmi S2 running MIUI Global 9.5 (Stable 9.5.14.0) and Firefox Rocket version I used is 2.2.0 (4869)

**Comment by chianger** [comment]
@cynthiatang this is not reproducible on my phone. maybe it's Redmi only?

**Comment by chianger** [comment]
QA Cannot reproduce
