### ISSUE TITLE
Crash - Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2110]
STR
 1. Uninstall Rocket nightly
 2. Install Rocket nightly
 3. Tap Next to close all onboarding pages
 4. Tap the top site "Kompas" when "Color your life" appears

Expected result:
 - No crash

Actual result 
 - Crash
 - Video: https://drive.google.com/open?id=1iZEp5yz_sI2tAE0wjTMsY1pPoj6Y8w2_ 
Reproduce Rate: 6/6

Device: Pixel 2
Android 8.1.0
Rocket 2.2.0(5213).nightly
WebView: 68.0.3440.40

--------- beginning of crash
06-30 19:01:42.771 13820 13820 E AndroidRuntime: FATAL EXCEPTION: main
06-30 19:01:42.771 13820 13820 E AndroidRuntime: Process: gro.allizom.zelda.beta, PID: 13820
06-30 19:01:42.771 13820 13820 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:537)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:526)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at org.mozilla.rocket.theme.ThemeManager.getSharedPreferences(ThemeManager.java:56)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at org.mozilla.rocket.theme.ThemeManager.dismissOnboarding(ThemeManager.java:77)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at org.mozilla.focus.home.HomeFragment$GestureListenerAdapter.onSingleTapConfirmed(HomeFragment.java:511)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at org.mozilla.focus.utils.SwipeMotionDetector$GestureListener.onSingleTapConfirmed(SwipeMotionDetector.java:44)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-30 19:01:42.771 13820 13820 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-30 19:01:42.838  1117  1132 I chatty  : uid=1000(system) android.ui expire 1 line
06-30 19:01:57.899  1117  2457 I chatty  : uid=1000(system) Binder:1117_14 expire 5 lines
06-30 19:01:57.912  1117  2311 I chatty  : uid=1000(system) Binder:1117_12 expire 7 lines
06-30 19:01:57.913  1117  1127 I chatty  : uid=1000(system) Binder:1117_1 expire 6 lines
06-30 19:01:57.916  1117  1138 I chatty  : uid=1000(system) android.display expire 5 lines
06-30 19:01:57.927  1117  1592 I chatty  : uid=1000(system) Binder:1117_7 expire 5 lines
06-30 19:01:57.963  1117  1134 I chatty  : uid=1000(system) batterystats-wo expire 8 lines
06-30 19:01:58.063  1117  1219 I chatty  : uid=1000(system) android.anim expire 2 lines
06-30 19:02:13.055  1376  1376 V DeadZone: consuming errant click: (657.0,6.0)
06-30 19:02:22.201  1117  1117 I chatty  : uid=1000 system_server expire 8 lines
06-30 19:02:32.567  1117  1282 I chatty  : uid=1000(system) Binder:1117_3 expire 10 lines
06-30 19:02:36.952  1117  2463 I chatty  : uid=1000(system) Binder:1117_18 expire 3 lines
06-30 19:02:37.319 14282 14282 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1556 android.content.ContextWrapper.bindService:684 android.content.pm.permission.RuntimePermissionPresenter$RemoteService.processMessage:171 android.content.pm.permission.RuntimePermissionPresenter.getAppPermissions:118 com.android.settingslib.applications.PermissionsSummaryHelper.getPermissionSummary:34 
06-30 19:02:38.831  2322  2322 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
06-30 19:02:38.831  2322  2322 I chatty  : uid=10028(com.google.android.apps.nexuslauncher) identical 2 lines
06-30 19:02:38.831  2322  2322 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
06-30 19:02:38.860  2322  2322 W ViewRootImpl[NexusLauncherActivity]: Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=12343789, downTime=12343789, deviceId=-1, source=0x101 }
06-30 19:02:38.875  2322  2322 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
06-30 19:02:39.130  1117  1131 I chatty  : uid=1000(system) ActivityManager expire 14 lines
06-30 19:02:39.143  1117  2458 I chatty  : uid=1000(system) Binder:1117_15 expire 2 lines
06-30 19:02:39.194  1117  2251 I chatty  : uid=1000(system) Binder:1117_D expire 8 lines
06-30 19:02:39.226  1117  2249 I chatty  : uid=1000(system) Binder:1117_C expire 4 lines
06-30 19:02:48.021  1117  2269 I chatty  : uid=1000(system) Binder:1117_F expire 3 lines
06-30 19:02:48.845  1117  1143 I chatty  : uid=1000(system) PackageManager expire 60 lines
06-30 19:02:49.276  1117  1523 I chatty  : uid=1000(system) Binder:1117_5 expire 2 lines
06-30 19:02:49.276  2322  2322 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
06-30 19:02:49.276  2322  2322 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
06-30 19:02:49.285  1117  1261 I chatty  : uid=1000(system) NetworkPolicy expire 15 lines
06-30 19:02:49.323  2322  2322 E SchedPolicy: set_timerslack_ns write failed: Operation not permitted
06-30 19:02:50.878  1117  1247 I chatty  : uid=1000(system) InputDispatcher expire 1 line
06-30 19:02:52.004  1117  1615 I chatty  : uid=1000(system) Binder:1117_8 expire 4 lines
06-30 19:02:56.437 27808 27808 E ActivityThread: Failed to find provider info for com.facebook.appmanager.oxygen.nekodirect.progress

**Comment by chianger** [comment]
per discussion during the standup meeting, this should block 2.3

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Pixel2
Android 8.1.0
Rocket 2.2.0(5257).nightly
WebView: 68.0.3440.34
