### ISSUE TITLE
Input of url is not optimized

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2122]
Issued by Teng-pao

1. Launch Rocket 
2. Add a bookmark
3. Tap EDIT

Expected: Set input type to textUri of bookmark_location

Actual Result: No set input type to the Location field

Reproduce Rate: 10/10

All devices
Rocket 2.2.0(5257).nightly

**Comment by mTwTm** [comment]
Expected: Only one line for url.

**Comment by cynthiatang** [comment]
Verified: Fixed

Samsung Galaxy J7 prime
Android 7.0
Rocket 2.3.0(5271)
WebView 67.0.3396.68
