### ISSUE TITLE
Click color your life text will bring up search

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2123]
STR
1. uninstall Rocket
2. Install Rocket
3. Skip all onboarding pages
4. Tap the 

Expected Result 
 - "Color your life" text will disappear. It will not bring up the search field 

Actual Result:
 - Click color your life text will bring up the search
 - https://drive.google.com/open?id=1A0GZ3JbYREiWjKrS6qM1eW6AtpywpqGJ

Pixel2
Android 8.1.0
Rocket 2.2.0(5257)nightly
Webview 68.0.3440.40

**Comment by chianger** [comment]
QAWanted to verify,

**Comment by cynthiatang** [comment]
It works for me. 

Pixel2 
Android 8.1.0
Rocket 2.3.0(5507).nightly
67.0.3396.87
