### ISSUE TITLE
Crash - java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.mozilla.focus.navigation.TransactionHelper$EntryData.tag' on a null object reference

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2131]
Pixel2
Android 8.1.0
Rocket 2.2.3(5271).nightly

7-04 00:07:01.077  1108  1734 I SoundTriggerHelper: startRecognition successful.
07-04 00:07:01.191  1108  1133 I ActivityManager: Killing 7271:com.google.process.gapps/u0a33 (adj 906): empty #17
07-04 00:07:01.192  1108  1133 I ActivityManager: Killing 7504:com.google.android.inputmethod.latin:train/u0a88 (adj 906): empty #18
07-04 00:07:01.252  1108 21413 I ActivityManager: Process com.chrome.beta:sandboxed_process0 (pid 8848) has died: cch  CEM 
07-04 00:07:01.252  1108 21413 W ActivityManager: Scheduling restart of crashed service org.mozilla.rocket/org.chromium.content.app.SandboxedProcessService0 in 1000ms
07-04 00:07:01.279  1108  1136 D KernelUidCpuTimeReader: Removing uids 99026-99026
07-04 00:07:01.886  1108  1734 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.mozilla.focus/.activity.MainActivity bnds=[237,84][439,346]} from uid 10028
07-04 00:07:07.163  1108  1266 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.google.android.apps.nexuslauncher/.NexusLauncherActivity (has extras)} from uid 1000
07-04 00:07:07.359  1108  1734 I SoundTriggerHelper: startRecognition successful.
07-04 00:07:09.163  1108  1734 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity bnds=[843,608][1045,870]} from uid 10028
07-04 00:07:09.181  1108 21413 I ActivityManager: Start proc 9021:gro.allizom.zelda.beta/u0a289 for activity gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity
07-04 00:07:09.355  1108 20343 I ActivityManager: Start proc 9078:com.chrome.beta:sandboxed_process0/u0i27 for webview_service gro.allizom.zelda.beta/org.chromium.content.app.SandboxedProcessService0
07-04 00:07:12.472  9021  9021 E AndroidRuntime: FATAL EXCEPTION: main
07-04 00:07:12.472  9021  9021 E AndroidRuntime: Process: gro.allizom.zelda.beta, PID: 9021
07-04 00:07:12.472  9021  9021 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.lang.String org.mozilla.focus.navigation.TransactionHelper$EntryData.tag' on a null object reference
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at org.mozilla.focus.navigation.TransactionHelper.getEntryTag(TransactionHelper.java:200)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at org.mozilla.focus.navigation.TransactionHelper.popScreensUntil(TransactionHelper.java:127)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at org.mozilla.focus.navigation.ScreenNavigator.popToHomeScreen(ScreenNavigator.java:155)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at org.mozilla.focus.activity.MainActivity.firstrunFinished(MainActivity.java:782)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at org.mozilla.focus.fragment.FirstrunFragment.finishFirstrun(FirstrunFragment.java:175)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at org.mozilla.focus.fragment.FirstrunFragment.onClick(FirstrunFragment.java:147)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at android.view.View.performClick(View.java:6294)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24770)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-04 00:07:12.472  9021  9021 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-04 00:07:12.535  1108  1453 D ConnectivityService: Returning UNBLOCKED NetworkInfo to uid=10289
07-04 00:07:12.537  1108  1453 W ActivityManager:   Force finishing activity gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity
07-04 00:07:12.553  1108  1134 I ActivityManager: Showing crash dialog for package gro.allizom.zelda.beta u0
07-04 00:07:13.038  1108  1133 W ActivityManager: Activity pause timeout for ActivityRecord{83cf5a5 u0 gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity t2263 f}
07-04 00:07:13.332  1108 19336 I SoundTriggerHelper: startRecognition successful.
07-04 00:07:13.517  1108  1133 I ActivityManager: Killing 6300:com.google.android.apps.messaging/u0a11 (adj 906): empty #17
07-04 00:07:15.302  1108  1136 E BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
07-04 00:07:19.755  1108  1453 I ActivityManager: START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.activities.AppCrashProxy (has extras)} from uid 1000
07-04 00:07:19.795  1108 19339 I WindowManager: WIN DEATH: Window{869345e u0 gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity}
07-04 00:07:19.795  1108  1689 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=158, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@b0240db)
07-04 00:07:19.796  1108  1119 I ActivityManager: Process gro.allizom.zelda.beta (pid 9021) has died: cch  CEM 
07-04 00:07:19.800  1108  1119 I ActivityManager: Killing 9078:com.chrome.beta:sandboxed_process0/u0a289i27 (adj 0): isolated not needed
07-04 00:07:19.801  1108  1140 W ActivityManager: setHasOverlayUi called on unknown pid: 9021

**Comment by mTwTm** [comment]
STR:

1. Re-install Rocket
2. Press system home to leave Rocket
3. Use a lot of other Apps to get Rocket is recycled. (Or, enable "Don't keep Activity" before step 1.)
4. Get back to Rocket
5. Finish onboarding
6. Crash.

**Comment by cynthiatang** [comment]
Verified: Fixed

Nexus 5
Android 5.1.1
Rocket 2.3.0(5330).nightly
WebView 67.0.3396.87
