### ISSUE TITLE
Color theme will change back to default if long press on top sites 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2132]
1. Make sure background theme is a new color
2. Long press on top site to remove top site
3. Background changes to default color

**Comment by cynthiatang** [comment]
This issue can be reproduced. 
Video: https://drive.google.com/open?id=1tZjJIiz4vmhF-9XfD2lqFDgPZfX5laUC

All devices

**Comment by chianger** [comment]
Major bug around new feature so it blocks 2.3.

**Comment by cynthiatang** [comment]
Verified: Fixed

Device: Pixel2
Android 8.1.0
Rocket 2.3.0(5330).nightly
WebView 68.0.3440.40
