### ISSUE TITLE
Promote "set as default browser" on the first launch on preloads 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2137]

**Comment by weslyhuang** [comment]
1. in order to track correctly, better to be preloaded as a system app
2. assuming preloaded as system app already. using the existing way (notification) for promotion.

question: notification style?

**Comment by Jacklin-ux** [comment]
Proposal: after onboarding pages then display Rocket's home, show "Set as default browser" dropped-down notification (not hidden notification) to trigger users to set Rocket's as default browser.
My assumption is to be a preload browser, after users view onboarding pages, they've already known what's the benefit of the browser and known if they like this browser yes or not, so I think this display timing is suitable.

**Comment by weslyhuang** [comment]
still keep the current one (enter setting twice) as long as Rocket is not set as default browser.

**Comment by chianger** [comment]
to be verified.
