### ISSUE TITLE
[new market] QA for web compat on Top Sites

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2150]
additionally we should look at whether the favicon is looking good if showed up at the topsite page.

**Comment by cynthiatang** [comment]
There is no Indonesia SIM to verify top sites in Indonesia

Verified: Global, India, Phillipines, Thailand

Global:
youtube.com
facebook.com
wikipedia.org
amazon.com
twitter.com
instagram.com
reddit.com
linkedin.com

India
youtube.com
facebook.com
amazon.in
wikipedia.org
flipkart.com
indiatimes.com
instagram.com
hotstar.com


Phillipines:
youtube.com
abs-cbn.com
facebook.com
inquirer.net
gmanetwork.com
wikipedia.org
lazada.com.ph
instagram.com

Thailand:
youtube.com
facebook.com
pantip.com
lazada.co.th
sanook.com
wikipedia.org
instagram.com
twitter.com

**Comment by cynthiatang** [comment]
@chianger , could you please ask the community to verify the top sites in Indonesia? Because we don't have a SIM card from Indonesia. Thank you.
