### ISSUE TITLE
"Save" is disabled while bookmark's name and location is not empty in bookmark edit page

### ISSUE THREAD

**Issue by josephyu1110** [mozilla-tw/Rocket#2151]
STR:
1. Launch Rocket
2. Visit a webpage
3. Bookmark the current webpage
4. Tap EDIT on SnackBar
5. Name and Location is not empty
6. Tap Save

Expected result: 
"Save" can be tapped(Do nothing and close the Edit bookmark page without a toast)

Actual result:
"Save" button is disabled

**Comment by cynthiatang** [comment]
@josephyu1110, 
sorry, I just revisited this test case. If a user doesn't edit the bookmark that he/she just added, the Save button should be disabled. Thanks
