### ISSUE TITLE
Crash - java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mozilla.focus.fragment.BrowserFragment.loadTab(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2165]
STR:
1. Launch Rocket
2. Tap a top site
3. Tap system Back key 3 times
4. Launch Rocket
5. Tap system Back key 3+ times  when the tap tray counter shows a smile icon

Video: https://drive.google.com/open?id=1TEjwlbt1IeB3XIWESoDv38iez6pzxO39

Reproduce Rate: 10/10

Devices Pixel2 
Android 8.1.0

Rocket 2.3.0(5443).nightly
WebView: 68.0.3440.40 and 67.0.3396.87

Rocket 2.3.0(5344)
WebView: 68.0.3440.40 and 67.0.3396.87

07-12 10:27:39.241  1111  1134 I ActivityManager: Displayed gro.allizom.zelda.beta/org.mozilla.rocket.activity.MainActivity: +142ms
07-12 10:27:39.350  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 38, previously 45
07-12 10:27:39.350  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 3595, previously 3596
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 38, previously 45
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 3595, previously 3596
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1169, previously 1449
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 1642, previously 1649
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 174, previously 1351
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 38, previously 45
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 3, previously 93
07-12 10:27:39.351  1340  1359 W ResourceType: ResTable_typeSpec entry count inconsistent: given 3595, previously 3596
07-12 10:27:39.460 26861 27159 D HttpURLTelemetryClient: Ping upload: 200
07-12 10:27:39.461 26861 27159 D TelemetryJobService: Performing upload of ping type: focus-event
07-12 10:27:39.505  1511  1511 I WallpaperService: engine paused
07-12 10:27:39.509   759   798 D CHRE    : @ 173639.922: -: id 10, otherClientPresent 0, mode 3
07-12 10:27:39.509   759   798 D CHRE    : @ 173639.922: [ImuCal] Dynamic sensor configuration: stand-by.
07-12 10:27:39.509   759   798 D CHRE    : @ 173639.922: sensorType 9 allowed 1: mergedMode 1, otherClientPresent 1
07-12 10:27:39.510   759   798 D CHRE    : @ 173639.922: sensorType 11 allowed 1: mergedMode 1, otherClientPresent 1
07-12 10:27:39.511   759   798 D CHRE    : @ 173639.922: sensorType 13 allowed 0: mergedMode 3, otherClientPresent 0
07-12 10:27:39.619  2507  2507 I StreamRenderer: cleanUpRendererScope(nowcards-7702669603849506233)
07-12 10:27:39.624  2507  2507 I PBSessionCacheImpl: Deleted sessionId[6406224961006] from persistence.
07-12 10:27:39.629  1111  1664 I WifiService: getConnectionInfo uid=10022
07-12 10:27:39.630  1111  1664 I WifiService: getWifiEnabledState uid=10022
07-12 10:27:39.637  2507  2507 W SearchServiceCore: Abort, client detached.
07-12 10:27:39.639  2507  2507 I StreamController: cleanUpControllerScope(nowcards-7702669603849506233)
07-12 10:27:39.663  1591  1591 E QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
07-12 10:27:39.663  1591  1591 E QtiImsExtUtils: isCarrierConfigEnabled bundle is null
07-12 10:27:39.743  1322  1322 I GoogleInputMethod: onKeyDown() : keyCode = 4, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=32463730, downTime=32463730, deviceId=-1, source=0x101 }
07-12 10:27:39.811  1111  1369 D WificondControl: Scan result ready event
07-12 10:27:39.824   608   608 D SurfaceFlinger: duplicate layer name: changing com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity to com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity#1
07-12 10:27:39.835  1111  1599 I WifiService: getConnectionInfo uid=10033
07-12 10:27:39.836  1111  1599 I WifiService: getWifiEnabledState uid=10033
07-12 10:27:39.836  1111  1599 I WifiService: getConnectionInfo uid=10033
07-12 10:27:39.839  2507  2507 W SessionLifecycleManager: Handover failed. Creating new session controller.
07-12 10:27:39.841  1322  1322 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
07-12 10:27:39.841  1322  1322 I GoogleInputMethod: onStartInput() : Dummy InputConnection bound
07-12 10:27:39.842  1111  1599 I WifiService: getConnectionInfo uid=10022
07-12 10:27:39.842  2260 25504 W ctxmgr  : [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10033):IndoorOutdoorProducer, vrsn=12685000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2260). Was: 3 for 57, account#-517948760#
07-12 10:27:39.842  1111  1599 I WifiService: getWifiEnabledState uid=10022
07-12 10:27:39.846  1111  3948 I WifiService: getConnectionInfo uid=10022
07-12 10:27:39.846  1111  3948 I WifiService: getWifiEnabledState uid=10022
07-12 10:27:39.847  2260 26116 W ctxmgr  : [AclManager]null policy map (0) 67, clientInfo=(accnt=account#-517948760#, com.google.android.googlequicksearchbox(10022):com.google.android.googlequicksearchbox, vrsn=12211000, 1, 3pPkg = null ,  3pMdlId = null ,  pid = 2507)
07-12 10:27:39.848  2507  3352 E GmsContextObserver: Failed to register context manager listener: Status{statusCode=unknown status code: 7503, resolution=null}
07-12 10:27:39.852  2260 26116 W ctxmgr  : [AclManager]null policy map (0) 67, clientInfo=(accnt=account#-517948760#, com.google.android.googlequicksearchbox(10022):com.google.android.googlequicksearchbox, vrsn=12211000, 1, 3pPkg = null ,  3pMdlId = null ,  pid = 2507)
07-12 10:27:39.854  2507  2507 I StreamController: registerScope: nowcards-7702669603849506233
07-12 10:27:39.857  1511  1511 I WallpaperService: engine resumed
07-12 10:27:39.864   759   798 D CHRE    : @ 173640.266: +: id 10, otherClientPresent 1, mode 3
07-12 10:27:39.865   759   798 D CHRE    : @ 173640.266: [ImuCal] Dynamic sensor configuration: high-performance.
07-12 10:27:39.865   759   798 D CHRE    : @ 173640.266: sensorType 9 allowed 1: mergedMode 1, otherClientPresent 1
07-12 10:27:39.865   759   798 D CHRE    : @ 173640.281: sensorType 11 allowed 1: mergedMode 1, otherClientPresent 1
07-12 10:27:39.867   759   798 D CHRE    : @ 173640.281: sensorType 13 allowed 0: mergedMode 3, otherClientPresent 0
07-12 10:27:39.880  2507  2507 I StreamRenderer: maybeRegisterNowCardsScope(nowcards-7702669603849506233, com.google.android.sidekick.shared.remoteapi.CardRenderingContext@c58f454)
07-12 10:27:39.881  1322  1322 I GoogleInputMethod: onKeyDown() : keyCode = 4, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=32463868, downTime=32463868, deviceId=-1, source=0x101 }
07-12 10:27:39.912  2507  2507 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
07-12 10:27:39.913  2507  2507 I chatty  : uid=10022 com.google.android.googlequicksearchbox:search identical 2 lines
07-12 10:27:39.914  2507  2507 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
07-12 10:27:39.917  1340  1359 W asset   : Asset path /data/app/com.spotify.music-ZpfCbU0db-izWkS73kReMw==/base.apk is neither a directory nor file (type=1).
07-12 10:27:39.918  1340  1359 E ResourcesManager: failed to add asset path /data/app/com.spotify.music-ZpfCbU0db-izWkS73kReMw==/base.apk
07-12 10:27:39.918  1340  1359 W PackageManager: Failure retrieving resources for com.spotify.music
07-12 10:27:39.918  1340  1359 W asset   : Asset path /data/app/com.spotify.music-ZpfCbU0db-izWkS73kReMw==/base.apk is neither a directory nor file (type=1).
07-12 10:27:39.918  1340  1359 E ResourcesManager: failed to add asset path /data/app/com.spotify.music-ZpfCbU0db-izWkS73kReMw==/base.apk
07-12 10:27:39.918  1340  1359 W PackageManager: Failure retrieving resources for com.spotify.music
07-12 10:27:39.918  1340  1359 W asset   : Asset path /data/app/com.spotify.music-ZpfCbU0db-izWkS73kReMw==/base.apk is neither a directory nor file (type=1).
07-12 10:27:39.918  1340  1359 E ResourcesManager: failed to add asset path /data/app/com.spotify.music-ZpfCbU0db-izWkS73kReMw==/base.apk
07-12 10:27:39.918  1340  1359 W PackageManager: Failure retrieving resources for com.spotify.music
07-12 10:27:39.920  2507  2507 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
07-12 10:27:39.921  2507  2507 I chatty  : uid=10022 com.google.android.googlequicksearchbox:search identical 2 lines
07-12 10:27:39.922  2507  2507 W StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
07-12 10:27:39.930   724  1101 D sound_trigger_hw: stdev_start_recognition:[1] Enter
07-12 10:27:39.930   724  1101 D sound_trigger_hw: get_confidence_levels_payload: No smlib for uuid, sending opaque data
07-12 10:27:39.930   724  1101 D sound_trigger_hw: reg_hal_event_session: ST_EVENT_SESSION_REGISTER capture_handle 62 p_ses 0xf4729000
07-12 10:27:39.930   724  1101 D sound_trigger_hw: loaded_state_fn:[1] handle event id 2
07-12 10:27:39.930   724  1101 D sound_trigger_platform: platform_stdev_get_capture_device: available devices 0x80000004, device 0x80000004
07-12 10:27:39.930   724  1101 D sound_trigger_platform: platform_stdev_get_device_sample_rate: sample rate 48000
07-12 10:27:39.931   724  1101 D sound_trigger_platform: platform_stdev_send_hwmad_cal: previous acdb_id 128 matches new acdb_id 128 return
07-12 10:27:39.931   724  1101 D sound_trigger_platform: platform_stdev_send_calibration: sending device calibration for device(1) acdb_id(128)
07-12 10:27:39.931   724  1101 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 128, Topology Id 12e19
07-12 10:27:39.931   724  1101 D sound_trigger_hw: set_device: enable device (1) = listen-cpe-handset-mic
07-12 10:27:39.931   724  1101 D audio_route: Apply path: listen-cpe-handset-mic
07-12 10:27:39.940   724  1101 D sound_trigger_hw: start:[1] gcs start VA engine, enable 1 token 383
07-12 10:27:39.940   724  1101 D sound_trigger_hw: start:[1] calling gcs_enable with handle 1, non-persist cal 0xf470f028, sz 24
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION_SIZE
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION_SIZE
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CALIBRATION
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CONNECTION_SIZE
07-12 10:27:39.940   724  1101 E         : gcs_get_sg_mod_conn_and_update_pld: subgraph mod conn size 0. Exiting
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CONNECTION_SIZE
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_MODULE_CONNECTION
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_CONNECTIONS_SIZE
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPHS_CONNECTION
07-12 10:27:39.940   724  1101 D ACDB-LOADER: ACDB -> ACDB_WDSP_CMD_GET_SUBGRAPH_CONNECTIONS_SIZE
07-12 10:27:39.940   724  1101 E         : __gcs_get_sg_conn_and_update_pld: subgraph conn size 0. Exiting
07-12 10:27:39.949   724  1101 D sound_trigger_hw: session[1]: loaded_state_fn ---> active_state_fn 
07-12 10:27:39.949   724  1101 D sound_trigger_hw: stdev_start_recognition:[1] Exit
07-12 10:27:39.949  1111  1599 I SoundTriggerHelper: startRecognition successful.
07-12 10:27:39.950  2292  2292 I GsaVoiceInteractionSrv: Start Hotword Recognition Status: true
07-12 10:27:40.027  1322  1322 I GoogleInputMethod: onKeyDown() : keyCode = 4, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=32464013, downTime=32464013, deviceId=-1, source=0x101 }
07-12 10:27:40.246 26861 27159 D HttpURLTelemetryClient: Ping upload: 200
07-12 10:27:40.247 26861 27159 D TelemetryJobService: All uploads performed
07-12 10:27:40.254 26861 26861 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-12 10:27:40.254 26861 26861 E AndroidRuntime: FATAL EXCEPTION: main
07-12 10:27:40.254 26861 26861 E AndroidRuntime: Process: gro.allizom.zelda.beta, PID: 26861
07-12 10:27:40.254 26861 26861 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.mozilla.focus.fragment.BrowserFragment.loadTab(java.lang.String)' on a null object reference
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at org.mozilla.focus.navigation.ScreenNavigator.restoreBrowserScreen(ScreenNavigator.java:119)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at org.mozilla.focus.activity.MainActivity.onQueryComplete(MainActivity.java:940)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at org.mozilla.focus.tabs.TabModelStore$QueryTabsTask.onPostExecute(TabModelStore.java:112)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at org.mozilla.focus.tabs.TabModelStore$QueryTabsTask.onPostExecute(TabModelStore.java:70)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:695)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-12 10:27:40.254 26861 26861 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-12 10:27:40.256 26861 27159 D TelemetryJobService: Performing upload of ping type: core
07-12 10:27:40.295  1111  7979 I OpenGLRenderer: Initialized EGL, version 1.4
07-12 10:27:40.295  1111  7979 D OpenGLRenderer: Swap behavior 2
07-12 10:27:40.370  1111  1128 I ActivityManager: Showing crash dialog for package gro.allizom.zelda.beta u0
07-12 10:27:40.490  2507 28879 I EventLogSendingHelper: Sending log events.
07-12 10:27:41.171 26861 27159 D HttpURLTelemetryClient: Ping upload: 200
07-12 10:27:41.175 26861 27159 D TelemetryJobService: Performing upload of ping type: focus-event
07-12 10:27:41.190 27076 27081 I zygote  : Do partial code cache collection, code=25KB, data=18KB
07-12 10:27:41.190 27076 27081 I zygote  : After code cache collection, code=25KB, data=18KB
07-12 10:27:41.190 27076 27081 I zygote  : Increasing code cache capacity to 128KB
07-12 10:27:41.580 26861 26901 I CrashlyticsCore: Crashlytics report upload complete: 5B46BC4100F6-0001-68ED-1F18AAE37A50
07-12 10:27:41.917  1111  1664 I ActivityManager: START u0 {act=android.intent.action.APP_ERROR flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.activities.AppCrashProxy (has extras)} from uid 1000
07-12 10:27:41.924   744   744 D QCOM PowerHAL: LAUNCH HINT: ON
07-12 10:27:41.926   744   744 D QCOM PowerHAL: Activity launch hint handled
07-12 10:27:41.944 26861 26861 I Process : Sending signal. PID: 26861 SIG: 9
07-12 10:27:41.974  1111  4202 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=376, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ], android.os.BinderProxy@64141dc)
07-12 10:27:41.977  1111  1121 I ActivityManager: Process gro.allizom.zelda.beta (pid 26861) has died: vis  TRNB
07-12 10:27:41.977  1111  1121 W ActivityManager: Scheduling restart of crashed service gro.allizom.zelda.beta/org.mozilla.telemetry.schedule.jobscheduler.TelemetryJobService in 1000ms
07-12 10:27:41.977  1111  1129 W zygote64: kill(-26861, 9) failed: No such process
07-12 10:27:41.977  1111  1129 I zygote64: Successfully killed process cgroup uid 10328 pid 26861 in 0ms
07-12 10:27:41.979  1111  1134 W ActivityManager: setHasOverlayUi called on unknown pid: 26861
07-12 10:27:41.980 22484 22484 I AppLifecycleTracker: onActivityCreated: 
07-12 10:27:41.980 22484 22484 I Finsky  : [2] com.google.android.finsky.activities.AppCrashProxy.onCreate(67): Sending feedback for crashed gro.allizom.zelda.beta to com.google.android.gms

**Comment by mTwTm** [comment]
Duplicate to #2144, thanks for the STR!
