### ISSUE TITLE
Menu text not centering with Thai.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2172]
![screenshot_20180716-111350](https://user-images.githubusercontent.com/6755074/42742847-0360dcc4-88f1-11e8-9daf-655935aa2e08.png)

**Comment by cynthiatang** [comment]
Verified: Fixed

![screenshot_20180718-115519](https://user-images.githubusercontent.com/12458450/42859105-ad48c6cc-8a84-11e8-879f-794117619d1e.png)

Pixel 2
Android 8.1.0
Rocket 2.3.0(5569).nightly
Android WebView: 67.0.3396.87
