### ISSUE TITLE
l10n -  On-boarding page

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2174]
System language: Thai language 
STR:
1. Install Rocket
2. Launch Rocket
3. Swipe left 3 times

Expected Result: 
 - Show onboarding pages in Thai

Actual Result:
 - ![4](https://user-images.githubusercontent.com/12458450/42748867-3f2d085e-8914-11e8-9ede-00e6defe38f9.png)

Reproduce Rate: 5/5

Sony Z3C
Android 6.0.1
Rocket 2.3.0(5539).nightly
WebView 67.0.3396.87

**Comment by chianger** [comment]
Follow-up is #2190

**Comment by mTwTm** [comment]
Can't reproduce, I guess it's just untranslated yet at that time. QA to double check.

**Comment by cynthiatang** [comment]
It works for me
