### ISSUE TITLE
Localize 'search suggestion' for new markets

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2176]
Same method to distinguish user's market as #2083  (targeting MCC)
Let's also localize 'search suggestion' and 'autocomplete' (previous work #544 , relevant #1888 )

**Comment by weslyhuang** [comment]
follow fennec or focus first.

**Comment by chianger** [comment]
@joechengla does this block shipping ?

**Comment by weslyhuang** [comment]
search suggestion is done by #2300, close this one and open another for auto complete.

**Comment by chianger** [comment]
"autocomplete" becomes followup , broken down to #2442
