### ISSUE TITLE
Would be nice to show the survey page in Thai after tapping "NO,  SEND FEEDBACK" 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2180]
1. Launch Rocket 
2. Set the language to Thai
3. Go to Menu -> Settings -> Give feedback -> NO, SEND FEEDBACK.

Actual Result:
 - Redirect to the survey page in English

Sony Z3C
Android 6.0.1
Rocket 2.3.0(5539).nightly
WebView: 67.0.3396.87

**Comment by chianger** [comment]
this survey page is at server-side and currently we have only ID and English

**Comment by chianger** [comment]
dup as #2339

**Comment by cynthiatang** [comment]
Verified: Fixed

Sony Z3C
Android 6.0.1
Rocket 3.0.0(6166).nightly
WebView: 68.0.3440.85
