### ISSUE TITLE
Missing images in qq.com

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2186]
1. Launch Rocket 
2. Visit xw.qq.com/m/football

Actual Result:
 - Missing an image after step 2. This issue can be reproduced in Focus 
 - Missing an image even though Turbo mode is disabled

Expected Result
 - No missing image 
 - No missing image even though Do Not Track and Tracking Protection are enabled in Fennec

Compare:     Rocket            V.S.               Fennec
    <img width="914" alt="screen shot 2018-07-18 at 2 30 23" src="https://user-images.githubusercontent.com/12458450/42865138-483cf0c0-8a9b-11e8-87a6-4598941fad7b.png">

Device: Pixel 2
Android 8.1.0
Rocket 2.3.0(5569).nightly
Android WebView: 67.0.3396.87

**Comment by chianger** [comment]
mixed content so close as dup to #954
