### ISSUE TITLE
Remove wikipedia (id) from default search engine

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2198]
settings >> default search engine

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8
Rocket 3.0.0(6168).nightly
WEbView 69.0.3497.24

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8
Rocket 3.0.0(6166).nightly
WEbView 69.0.3497.24
