### ISSUE TITLE
A Thai string in a notification is incorrect.

### ISSUE THREAD

**Issue by veer66** [mozilla-tw/Rocket#2215]
I received a string "รัก %1$s" from the notification. It is including "%1$s", which is incorrect.

P.S. I tested on Nokia 3.

![photo_2018-07-23_11-39-33](https://user-images.githubusercontent.com/370688/43057571-518f881a-8e6d-11e8-89cd-6250b2d77f5c.jpg)

**Comment by mTwTm** [comment]
Thanks! This one was just fixed and shall show up in the next Nightly!

**Comment by veer66** [comment]
Thank you.

**Comment by mTwTm** [comment]
Fixed in #2206

**Comment by veer66** [comment]
@mTwTm The mentioned next Nightly is build 5748, isn't it?

**Comment by mTwTm** [comment]
Yes, let me know if it is not fixed. Our QA will try this one later as well, too.

**Comment by mTwTm** [comment]
To reproduce the Notification, you can enter App Settings twice. (New install required, only the second visit but not every next two visits.)

**Comment by veer66** [comment]
@mTwTm  Thank you. I tried to follow the steps. And now I'm waiting for notification.

**Comment by veer66** [comment]
I just got notification ~ 40 minutes ago. And it works.

![photo_2018-07-24_23-59-13](https://user-images.githubusercontent.com/370688/43154186-a4580ad2-8f9d-11e8-8360-ab2f4983f054.jpg)
