### ISSUE TITLE
Change "Share" to "Delete" button on the action bar of private mode

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#2224]
After user interview, many users would like to clear browsing history when using private mode, but they don't know how to do it.
The proposal is as below, and the behavior is when users click "Delete" button, remove browsing history and back to tab tray + show a toast "Your browsing history has been erased.".
<img width="319" alt="screen shot 2018-07-23 at 5 30 21 pm" src="https://user-images.githubusercontent.com/22672569/43071715-3b3b5d12-8ea6-11e8-87dd-c15beedbd379.png">

**Comment by chianger** [comment]
Blocking for general production release. 
UX wanted to confirm which button to replace.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8
Rocket 3.0.0(6166).nightly
WEbView 69.0.3497.24
