### ISSUE TITLE
Clearing all browsing data doesn't sign out user

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2237]

**Comment by chianger** [comment]
normal mode can have browser sign out when clearing browsing data.

**Comment by chianger** [comment]
UX wanted to define behavior

**Comment by Jacklin-ux** [comment]
Expected behaviour is the same as in normal mode - When clear browsing data, browser will sign out.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8
Rocket 3.0.0(6166).nightly
WEbView 69.0.3497.24
