### ISSUE TITLE
always shows then notification

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2238]
1. Launch Rocket 
2. Switch to private mode
3. Visit a website
4. Tap mini-Url and visit youtube.com

**Comment by chianger** [comment]
vibration as well. 
expected to not have both vibration and notification .

**Comment by cynthiatang** [comment]
Verified: Fixed. Thanks

Sony Z3C
Android 6.0.1
Rocket 2.4.0(5887).nightly
WebView 67.0.3396.87

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8
Rocket 3.0.0(6166).nightly
WEbView 69.0.3497.24
