### ISSUE TITLE
Add Telemetry for Private Mode

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#2244]
Document update is required

Which one should be tracked?

- [x] Click the mask in Tab Tray to switch to Private Home
- [x] Click the mask in Private Home to switch to Tab Tray
- [ ] Click "OPEN" in Notification to switch to Private Mode (Home or Browser)
- [x] Click "Erase ...." on Notification Body to end private mode and switch to Normal Mode (Home or Browser)
- [ ] In private mode, start the private session 
- [ ] In private mode, end the private session 
- [ ] In private mode, if any of the Items in the bottom toolbar is clicked
- [ ] In private mode, if any of the Items in the context menu is clicked

**Comment by joechengla** [comment]
only collect PB entry and exit. anything else in PB we do no collect

**Comment by cnevinc** [comment]
wiki updated
https://github.com/mozilla-tw/Rocket/wiki/Telemetry/0758372aea8a4ea462d5f692add024a1074b548f
