### ISSUE TITLE
Inconsistent turbo mode (sometime)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2274]
1. Open Menu and check the status of turbo mode
2. Open Menu -> Settings -> Disable Turbo Mode
3. Open Menu and check the status of turbo mode

Expected:
 - The status of turbo mode is disabled in Menu panel

Actual:
 - The status of turbo mode is enabled in Menu panel
 - Video: https://drive.google.com/open?id=1IHhJVL5JoAEC3XsA8r2PvkDKhlCoQ5im

Reproduce Rate: 1/50 

Pixel 2
Android 8.1.0
Rocket 2.4.0(5814).nightly
WebView 68.0.3440.40

**Comment by chianger** [comment]
QAWanted to check reproduce rate.

**Comment by chianger** [comment]
Close as WORKSFORME

**Comment by weslyhuang** [comment]
reproducible with v3.4.1 (build 7492)

https://drive.google.com/open?id=1CSabt9lyV5o0HPu2m3BAJRIbd9XQTwA0

**Comment by weslyhuang** [comment]
verified pass with 1.0.0 (7832)

**Comment by ivantw08** [comment]
Device:nexus 5
OS: Android: 6.0.1
WebView: 69.0.3497.100
Firefox Lite: 1.0.0(7855)

same issue

**Comment by weslyhuang** [comment]
would you post a video for this as well @ivantw08 ? is it 100% reproducible in your test?

**Comment by ivantw08** [comment]
sorr
