### ISSUE TITLE
Brand Change Transition Experience 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2299]

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1roJYVwZ3Y1rtwxG7XOzLlJVIxELizgAu/view?usp=sharing

**Comment by Pekochen** [comment]
visual spec
https://drive.google.com/open?id=1YfpF6ejBpguxb2xnwBs0NIQrwuze-J_8
assets : 
https://drive.google.com/open?id=1n-WoDMoWXg4XbW96SiHB716wqZf4_S16

**Comment by chianger** [comment]
telemetry-wanted to discuss if we need capture new onboarding, or other new analytics.

**Comment by elin-moco** [comment]
Correct me if I'm wrong, I didn't see anything in this spec that requires extra telemetry event.

Though I'm really interested in seeing how long user stays on each page, but that' probably another story.
Not blocking for this bug.

**Comment by mTwTm** [comment]
I think the only place that might need some telemetry is the 4.0 onboarding?
