### ISSUE TITLE
cannot play a video in Landscape mode (private browsing)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2308]
1. Switch to private browsing mode
2. visit youtube.com
3. play a video in landscape mode

Expected result:
 - play a video in landscape mode

Actual result
 - It still plays a video in Portrait mode

Reproduce Rate:  10/10

Nexus5 
Android 5.1.0
Rocket 3.0.0(5988).nightly
WebView 67.0.3396.87

**Comment by chianger** [comment]
dup as #2387
