### ISSUE TITLE
PH Top Site: ABS-CBN web compat

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2312]
https://drive.google.com/file/d/11rtJa7MYdQ6tpg9Zie-ZIyT2S-GTkSmt/view?usp=sharing

the http version will work ok
but our topsite links to the https version

**Comment by cynthiatang** [comment]
URL with https                               URL with http      
<img width="897" alt="screen shot 2018-08-08 at 7 41 40" src="https://user-images.githubusercontent.com/12458450/43835091-22733030-9b43-11e8-9066-9c354c2eba86.png">

**Comment by cynthiatang** [comment]
Verified: Fixed

StarMobile UP Prime
Android 7
Rocket 3.0.0(6166).nightly
WebView 68.0.3440.91
