### ISSUE TITLE
Editbookmark shows non-localized string

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2322]
<img width="322" alt="screen shot 2018-08-06 at 10 41 23 am" src="https://user-images.githubusercontent.com/9859809/43694787-af114370-9967-11e8-86f0-dfe0401da1bb.png">

**Comment by chianger** [comment]
Can reproduce on 2.3, and 3.0

**Comment by chianger** [comment]
Likely a regression so I'm setting P1. 
I looked at previous side-by-side screenshots for 2.4.0, it was correctly displayed. 
So we seem to have this regression since 2.3.1 (dot release) and then current nightly (3.0).

**Comment by chianger** [comment]
similar to #2344

**Comment by mTwTm** [comment]
It may not be a regression, but we can fix this.

**Comment by mTwTm** [comment]
@mxlius already have a fix @2379 for this.

**Comment by mxlius** [comment]
Closed by #2379

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel 2
Android 8.1.0
Rocket 3.1.0(6550)
WebView 68.0.3440.91
