### ISSUE TITLE
There should be 2 paper dots

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2336]
1. Launch Rocket

Actual result:
 - There are no paper dots

Expected 
 - there are 2 paper dots. Number 5 is about the paper dot.
<img width="315" alt="screen shot 2018-08-06 at 4 50 17" src="https://user-images.githubusercontent.com/12458450/43706825-00395cfc-9999-11e8-86dc-3dcc795e20e5.png">

Pixel2 
Android 8.1.0
Rocket 3.0.0(6038).nightly
WebView 68.0.3440.70

**Comment by mTwTm** [comment]
Duplicate to #2328
