### ISSUE TITLE
The banner is too far away from the search bar

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2338]
STR:
 1. Launch Rocket

Actual result:
 - The banner is too far away from the search bar

Expected result:
 - The distance between the search bar and banner = The distance between the banner and Topsites. Please refer UX spec

<img width="739" alt="screen shot 2018-08-06 at 5 37 32" src="https://user-images.githubusercontent.com/12458450/43709891-a940e1a6-99a0-11e8-9409-01035b3ef68a.png">

Pixel 2
Android 8.10
Rocket 3.0.0(6038).nightly

**Comment by mTwTm** [comment]
The spec seems to have changed. I'll take a look. (was, 40dp from top.)

**Comment by mTwTm** [comment]
Ignore the 40dp from the top specification and honor the symmetric 36dp specification.

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel 2
Android 8.10
Rocket 3.0.0(6069).nightly
WebView68.0.3440.70
