### ISSUE TITLE
Update survey link for 3.0

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/Rocket#2339]
Since the survey options are different in 2.4.
Also we are going to launch in India/Philippines/Thailand. 
To give users proper survey according to their version, also to make initial l10n work easier, we might need to use another survey link for 2.4:
https://www.surveygizmo.com/s3/4500936/2-4-Firefox-Rocket-Your-feedback-is-our-fuel-for-improvement

**Comment by chianger** [comment]
correct title to 3.0
@elin-moco we should consider using a mozilla link

**Comment by elin-moco** [comment]
Just updated to our shorter link, please use this:
https://qsurvey.mozilla.com/s3/Firefox-Rocket-3-0-Input

**Comment by cynthiatang** [comment]
Verified: Fixed

Language: Th           --> Show the survey in Thai
Language: Bahasa   --> Show the survey in Indonesia
Language: Tl            --> Show the survey in English

Sony Z3C
Android 6.0.1
Rocket 3.0.0(6166).nightly
WebView: 68.0.3440.85
