### ISSUE TITLE
Language on the top navigation bar does not change with the language setting (See STR)

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2344]
Prerequisite:
Language is set to English

STR: 
1. Enter settings
2. Set language to Indonesian

Expected result:
'Settings' text should be changed to 'Setelan'

Actual result:
Text remains 'Settings'; will change to 'Setelan' after leaving and re-entering the settings page.

Reproduce Rate: 100%

Device: Advan i5C
Rocket Ver.: 2.3.1#5755
Android Ver.: 5.1
WebView: 67.0.3396.87

Screenshot:
![screenshot_2018-08-07_case53](https://user-images.githubusercontent.com/746727/43759826-00cdcddc-9a53-11e8-9ec8-0bfa4ce3be3d.png)

**Comment by mTwTm** [comment]
Per my test, it is changing but only change for the first time. (Could be device-dependant behavior.)

Tested on 8.0 Pixel

**Comment by mTwTm** [comment]
Not a regression since 3.0 on Pixel.

**Comment by mTwTm** [comment]
Actually, on my device, it is changing. (I was clicking two languages with the same translation in my last report.)

Can't reproduce, labeling QAwanted.

**Comment by cynthiatang** [comment]
Hi @mlwang32 , Could you test it again? If you can still reproduce it, please provide the video. Because I cannot reproduce it. 

Passed:
OPPO A37f
Android 5.1.1
Rocket 3.0.0(6424).nightly
WebView 68.0.3440.91

**Comment by cynthiatang** [comment]
Hi @mTwTm ,
Sorry, the step should be changed. Then I can reproduce it. 
https://drive.google.com/open?id=1dXqWQ1CUKPCmMXYsF7PTl0KtCBO43R-h

**Comment by mTwTm** [comment]
STR:

1. Set Rocket to any language, I, in in-app language picker.
2. Close Rocket
3. Set Rocket to another language, J, in in-app language picker.
4. Set Rocket to the language I.

expected: title (Setting) is shown as the string in the language I

actually: title (Setting) is shown as the string in language J

**Comment by cynthiatang** [comment]
Verified： Fixed

Pixel2
Android 8.1.0
3.2.0(6910).nightly
Webview 68.0.3440.91
