### ISSUE TITLE
Scrambled codes shown on the settings page under Language setting

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2345]
Prerequisite:
N/A

STR:

1. Enter settings
2. Tap language

Expected result:
The option 'Indonesian' should appear alongside System default and English (United State)

Actual result:
Scrambled codes are displayed where the Indonesian language option should appear

Reproduce Rate: 100%

Device: Advan i5C
Rocket Ver.: 3.0.0(6047).nightly
Android Ver.: 5.1
WebView: 67.0.3396.87

Screenshot:
![screenshot_2018-08-07_53](https://user-images.githubusercontent.com/746727/43760791-b825a26e-9a55-11e8-8a3b-c645d937ad7c.png)

**Comment by chianger** [comment]
fixed. please verify.

**Comment by mlwang32** [comment]
Fix verified (v. 3.0.0(6125).nightly, build#3925).
