### ISSUE TITLE
It will redirect to https://firebasestorage.googleapis.com after tapping the "ASIAN GAMES 2018" banner

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2348]
1. Launch Rocket
2. Tap the "ASIAN GAMES 2018" banner

Actual result
 - It will redirect to https://firebasestorage.googleapis.com/v0/b/rocketnightly.appspot.com/o/icons%2Fasian-games.png?alt=media&token=e987af8c-e23e-447b-aafb-ca7c8ce47c2b
 - Video: https://drive.google.com/open?id=1U9JO4XrRH3deh0SSst0sDMC57pREPbmD

Pixel 2
Android 8.10
Rocket 3.0.0(6069).nightly
WebView68.0.3440.70

**Comment by mTwTm** [comment]
Should be fixed when #2347 is merged.

**Comment by cynthiatang** [comment]
Verified: Fixed
