### ISSUE TITLE
Should not show a toast after tapping system Back key from Private Browsing Home

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2360]
1. Launch Rocket 
2. Switch to Private Browsing Home 
3. Tap system Back key

Expected result:
 - Don't show a toast to remind users

Actual result:
 - Show a toast to remind users
 - Video: https://drive.google.com/open?id=1RvasVIFbsFLRQWacB9gQlOoG0sYmn1Lb

Reproduce Rate: 10/10

Pixel 2 
Android 8.1.0
Rocket 3.0.0(6084).nightly
WebView: 68.0.3440.70

**Comment by chianger** [comment]
There shouldn't be a toast if exiting from an empty PB page.

**Comment by mlwang32** [comment]
Same behavior observed on Android 7, Rocket 3.0.0(6193)

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel 2
Android 8.1.0
Rocket 3.1.0(6550)
WebView 68.0.3440.91
