### ISSUE TITLE
Show the tab number with a black link after closing all tabs

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2361]
(Issued by Jack)

1. Launch Rocket's Home 
2. Tap a top site
3. Tap the tab tray
4. Tap Close All Tab
5. Check the tab number

Actual result
 - There is a black link
 - This issue cannot be reproduced in Pixel2 with Android 8.10 
 -Video: https://drive.google.com/open?id=10gm6o06ZjWkYEwu6-o6VuinZuWw5AGII
 - Image: 
    <img width="330" alt="screen shot 2018-08-08 at 6 15 10" src="https://user-images.githubusercontent.com/12458450/43831544-13016ede-9b37-11e8-9928-bd85526d1af2.png">

Expected result:
 - There is no black link

Reproduce Rate: 10/10

Pixel2 
Android 9
Rocket 3.0.0(6084).nightly

**Comment by chianger** [comment]
not reproducible anymore by jack. WORKSFORME
