### ISSUE TITLE
No l10n in setting.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2368]
![screenshot_20180808_173140](https://user-images.githubusercontent.com/6755074/43836084-c4d4aa18-9b46-11e8-9f50-7d6896d671d0.jpg)

**Comment by mTwTm** [comment]
Not sure why but a possibly incorrect syntax which was accepted is now broken. (Did we upgrade Gradle or anything?)

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel 2
Android 8.1.0
Rocket 3.0.0(6112).nightly
WebView 68.0.3440.91

**Comment by mTwTm** [comment]
Dup to #2345
