### ISSUE TITLE
Reload icon does not change to cross during page reload on private browsing mode

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2393]
Prerequisite:
There are existing tabs 

STR:

1. Enter private browsing mode
2. Go to a web page that takes a while to load (i.e. Instagram)
3. Monitor the reload button

Expected result:
Reload button should change to cross(stop) button during page load

Actual result:
Reload button does not change to cross(stop) button during page load

Reproduce Rate: 100%

Device: Advan i5C
Rocket Ver.: 3.0.0(6166).nightly
Android Ver.: 5.1
WebView: 67.0.3396.87

Screenshot:
![screenshot_2018-08-09_case186](https://user-images.githubusercontent.com/746727/43952245-e78cbbfe-9cc7-11e8-9422-3e158a435335.png)

**Comment by chianger** [comment]
function break: S1.

**Comment by mlwang32** [comment]
Same issue on Android 7, Rocket 3.0.0(6193)

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2
Android 8.1.0
Rocket 3.0.0(6354).nightly
WebView 68.0.3440.91
