### ISSUE TITLE
"Javanese" and "Sundanese" appear as language codes when switching languages

### ISSUE THREAD

**Issue by Delphine** [mozilla-tw/Rocket#2398]
Steps to repro:
* Launch app 
* Switch from English to "Javanese" or "Sundanese" (or probably just any other locale) under the app's setting Language Switcher
* Go back into switcher
Result: "Javanese" and "Sundanese" now appear as their language codes "jv" and "su"
Expected: they should appear as their "true" names :)

Please note: today at the Jakarta sprint, localizers will be discussing which names we'd like to have for Sundanese and Javanese in their locale language - since they are currently not localized under language settings. I'll file another bug for that once we've decided.

**Comment by chianger** [comment]
reference #2399

**Comment by mTwTm** [comment]
Fixed in #2427

**Comment by cynthiatang** [comment]
Hi @Delphine ,
Could you please check it? Thanks 
![screenshot_20180828-104419](https://user-images.githubusercontent.com/12458450/44697713-958f5f00-aaaf-11e8-88d0-ba0339875072.png)

**Comment by Delphine** [comment]
Confirming it's now fixed on the latest Nightly! Thanks everyone!
