### ISSUE TITLE
[l10n] Change "Javanese" and "Sundanese" names in language Settings

### ISSUE THREAD

**Issue by Delphine** [mozilla-tw/Rocket#2399]
Right now, in the language settings it says "Javanese" and "Sundanese". However this is not how you say them in their local language.

Here is what the localizers have agreed upon: please call Javanese as 'Basa Jawa' and Sundanese as 'Basa Sunda'.

We do similar thing in Focus Android: see for example https://github.com/mozilla-mobile/focus-android/issues/2627

Thanks :)

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel 2
Android 8.1.0
Rocket 3.1.0(6550)
WebView 68.0.3440.91
