### ISSUE TITLE
generate side-by-side screenshots for l10n (new locales added) (Sprint: Banderpunch)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2414]
We are adding two locales (Javanese and Sundanese), so we would need to provide new screenshots for l10n QA.

Note: there are some new UI pages as well. #1987 and #1968

**Comment by weslyhuang** [comment]
as this is not fully-automated yet we have 2 steps here:

1. @josephyu1110 to help get screenshots of this 2 locale, upload to Gdrive and share us the link.
2. @cynthiatang to take from there, add the rest screenshots (if anything new), compose the side-by-side document for l10n check.

**Comment by josephyu1110** [comment]
@weslyhuang

**Comment by josephyu1110** [comment]
@weslyhuang @cynthiatang 
https://drive.google.com/file/d/1yMKn58mtoGuWft6VKtGpsS501DnjiQ-W/view
New screenshots are generated from master branch, commit id = '47b6cb867254bc3421c88922848dacd9153bca0c'.
