### ISSUE TITLE
New theme for India, Philippines and Thailand

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#2416]

**Comment by Pekochen** [comment]
visual spec 
https://drive.google.com/open?id=1Ph9VqX0rTQrlPxbZPWV9db0sFALhmCXn
assets: 
https://drive.google.com/open?id=1n-WoDMoWXg4XbW96SiHB716wqZf4_S16
will update onboarding spec later.

**Comment by chianger** [comment]
covered by #2299. closed as dup
