### ISSUE TITLE
Should not show toast after launching another app (Pixel with Android 9) 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2417]
(Issued by Jack)

1. Launch Rocket 
2. Switch to Private browsing mode
3. Visit a webpage
4. Tap the Trash button to erase private browsing history
5. Tap system Home
6. Kill Rocket from Task manager
7. Back to system Home
6. Launch Rocket or another app 

Expected Result:
 - Don't show "Your private browsing history has been erased"

Actual Result:
 - Show "Your private browsing history has been erased"
 - This issue cannot be reproduced in Pixel 2 with Android 8.1 
 - https://drive.google.com/open?id=183tFa87_0kyV655RYLuVHaxJVeBsDYuc

Pixel 2 
Android 9
Rocket 6232
WebView 67 or 68

**Comment by chianger** [comment]
@Jacklin-ux can you try reproduce it now?

**Comment by Jacklin-ux** [comment]
Bug fixed, thank you
