### ISSUE TITLE
Webview in Settings is not honoring the language selection of the user

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2425]
STR:
1. go to settings and change language to Hindi
2. go to about page and click the link to support page

Actual result:
Redirect user to English support page

Expected result:
Redirect user to Hindi support page

Note: for Thai it's also reproducible.

**Comment by mTwTm** [comment]
Tested with system language: Hindi, successfully redirected to Hindi Sumo Page.

**Comment by mTwTm** [comment]
About page is not sending the locale we're choosing properly. However, normal browsing page is. Test url: https://support.mozilla.org/kb/get-started-firefox-rocket

**Comment by chianger** [comment]
A regression we should take care of.

**Comment by cynthiatang** [comment]
I can reproduce it. But it works (show ABOUT-SUMO in Hindi) if the system language is Thai. 

https://drive.google.com/open?id=15FXAdeEiEzPQj72hlq5KR-uwd48ZdAWT
System: Thai
Rocket: Hindi
About-SUMO: Hindi

https://drive.google.com/open?id=1qZ1Vtqaqxle_3NvRZH6dY25-6RU7Z7NY
System: English
Rocket: Hindi
About-SUMO: English

Pixel2
Android 8.1.0
Rocket 3.0.0(6232)
WebView 68.0.3440.91

**Comment by josephyu1110** [comment]
This issue is fixed by PR: https://github.com/mozilla-tw/Rocket/pull/2767
Since InfoActivity is changed to locale aware now.

**Comment by josephyu1110** [comment]
This issue is fixed by PR: https://github.com/mozilla-tw/Rocket/pull/2767.
Since InfoActivity is changed to local aware now.

**Comment by josephyu1110** [comment]
This issue is fixed by PR: https://github.com/mozilla-tw/Rocket/pull/2767.
Since InfoActivity is changed to local aware now.

**Comment by josephyu1110** [comment]
This issue is fixed by PR: https://github.com/mozilla-tw/Rocket/pull/2767.
Since InfoActivity is changed to local aware now.
