### ISSUE TITLE
After leaving the private mode, entering settings and tapping exit, the app returns to the private mode

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2432]
Prerequisite:
There are existing tabs

STR:

1. Enter the private browsing mode
2. Tap the purple icon to leave the private mode
3. Enter settings, then tap Exit

Expected result:
The app should exit

Actual result:
The app returns to the private browsing mode

Reproduce Rate: 100%

Device: Samsung Galaxy J7 Prime
Rocket Ver.: 3.0.0(6193)
Android Ver.: 7.0
WebView: 67.0.3396.68

Clip:

[bug.zip](https://github.com/mozilla-tw/Rocket/files/2290569/bug.zip)

**Comment by chianger** [comment]
Sounds weird. @Jacklin-ux thought?

**Comment by Daisy-pliu** [comment]
Test Result: ✅
Test version : 1.0.9(9284)
Test Device: 
1.Redmi 4X(7.1.2)-webview: 71.0.3578.99
2.Samsung galaxy S7 Edge(8.0) -webview:71.0.3578.99
3.Vivo 1606 (6.0.1) -71.0.3578.99
