### ISSUE TITLE
Pirvate browsing is not honoring the language selection of the user

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2436]
STR:

1. Change locale to Hindi in language switcher
2. System locale set to some langauge that is not Hindi
3. visit: https://support.mozilla.org/en-US/kb/get-started-firefox-rocket in private browsing.

Expected behavior:
See Hindi version of sumo page.

Actual behavior:
See non-Hindi version of sumo page.

**Comment by cynthiatang** [comment]
I cannot reproduce it in my Pixel 2

https://drive.google.com/open?id=1I_IJZandCFnrx7Ct-j7jaumUqIVJrolO

Pixel 2
Android 8.1.0
Rocket 3.0.0(6232)
Webview 68.0.3440.91

**Comment by mTwTm** [comment]
Can't reproduce with current STR too. I've found another STR that may be how I reproduced it in the first place. I'll file another bug.

**Comment by mTwTm** [comment]
Actually, we already have a bug for this: #672
