### ISSUE TITLE
Screenshoting overlay string layout issue (shifted to the left?)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2447]
(Issued by Joe)

1. Visit a website
2. Tap screenshot button
3. check the string "capturing screenshot of entire page ..."

Expected Result:
 - Center Text 

Actual Result
 - Shifted to the left
 - Video: https://drive.google.com/file/d/1WtfyU17MCLTsRXzR4km7Nx7JdQ2m5Xz3/view?usp=sharing

Pixel2
Android 8.1.0
Rocket 3.0.0(6354)
WebView 68.0.3440.91

**Comment by chianger** [comment]
In Thai it's really obvious and looks bad.

**Comment by chianger** [comment]
Hindi isn't good either.

**Comment by Pekochen** [comment]
suggest need to modify this position and make it align center.
Thank you.

**Comment by mxlius** [comment]
Closed by #2464

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2 
Android 8.1.0
Rocket 3.1.0(6553).nightly
WebView 68.0.3440.91
