### ISSUE TITLE
Redundant transition from private home to a private search

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2450]
(Issued by Jack)
STR
1. Launch Rocket
2. Switch to private mode
3. Search a work or a website

Actual result:
 - Redundant transition

Expected result:
 - no redundant transition

All device

**Comment by mxlius** [comment]
Closed by #2309

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2 
Android 8.1.0
Rocket 3.1.0(6553).nightly
WebView 68.0.3440.91
