### ISSUE TITLE
Entering Private browsing but only see dark background page

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2452]
(Issued by Wesly)

1. Switch to Private browsing mode

Actual
 - I thought it's the performance issue like #2418 but actually it never really gives me the search page.
 - The user can work around this by clicking on the trash (delete) icon.

Expected 
 - should not see the dark background page

**Comment by chianger** [comment]
STR:
1. settings >debug> don't keep activity ON
2. go to PB and browse something
3. use task switcher to make PB not in foreground
4. go to PB again
Boom

**Comment by chianger** [comment]
user workaround: need to use the "trash bin" icon to recover
S1

**Comment by mTwTm** [comment]
Closed in #2547.

**Comment by cynthiatang** [comment]
Verfied： Fixed

Pixel2 
Android 8.1.0
Rocket 3.2(6855).nightly
WebView 68.0.3440.91
