### ISSUE TITLE
Can't download file / Can't access site.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2458]
Can't access: https://uva.onlinejudge.org

I filed this bug originally to illustrate that files in https://uhunt.onlinejudge.org/id/9947 can't be downloaded, (click 108 in tried but not solved, for example.) However, I just noticed that the whole site is not shown.

**Comment by chianger** [comment]
user-agent compat issue, and it's not always reproducible.

**Comment by chianger** [comment]
not actionable from engineering side atm.
WON"T FIX
