### ISSUE TITLE
When testing error codes using https://httpstat.us, for 4XX and 5XX codes, only error code#407 shows the default error page, all other pages show string-based error message.

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2460]
Prerequisite:
N/A

STR:

1. Launch Rocket
2. Go to test website (eg. https://httpstat.us)
3. check the behavior of 4xx and 5xx error web page

Expected result:
Tapping on the error link to show the default error page

Actual result:
Only 407 shows default error page, all others show error strings only

Reproduce Rate: 100%

Device: Samsung Galaxy J7 Prime
Rocket Ver.: 3.0.0(6354)
Android Ver.: 7.0
WebView: 68.0.3440.91

Screenshots:
![8_1](https://user-images.githubusercontent.com/746727/44461265-bd5f6c80-a642-11e8-9059-3c01698cb512.png)
![8_2](https://user-images.githubusercontent.com/746727/44461267-bdf80300-a642-11e8-9587-01d82e03434d.png)

**Comment by chianger** [comment]
We intended not to manipulate those 4xx, 5xx errors so that users can see the actual messages.
WON"T FIX
