### ISSUE TITLE
When visiting a page with revoked ssl (https://revoked.badssl.com), mini url still shows green lock.

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2462]
Prerequisite:
N/A

STR:

1. Launch Rocket
2. Visit a website w/o valid SSL certificated (https://revoked.badssl.com)

Expected result:
No green lock is shown on URL bar 

Actual result:
URL bar shows green lock

Reproduce Rate: 100%

Device: Samsung Galaxy J7 Prime
Rocket Ver.: 3.0.0(6354)
Android Ver.: 7.0
WebView: 68.0.3440.91

Screenshot:
![29_bad_ssl](https://user-images.githubusercontent.com/746727/44461759-ac175f80-a644-11e8-8632-572079038ea9.png)

**Comment by chianger** [comment]
Firefox Focus does the same.

**Comment by chianger** [comment]
Same as Focus so INVALID this one,
