### ISSUE TITLE
Contextual hint to introduce feature when user doing android screenshot

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#247]
UX Spec v1.8, page37 has the details

**Comment by chianger** [comment]
Labeled UX/VD to request visual design

**Comment by harly21** [comment]
Carol released the visual spec here: https://drive.google.com/drive/folders/0B-9PIePlQZRlYlZTdDlLNXRwUFU

**Comment by dakaizou** [comment]
Screenshot onboarding doesn't show up until granting storage permission

Build: 1486
DuT: Samsung

**Comment by dakaizou** [comment]
verified in build 1512
