### ISSUE TITLE
Kompas recognized as Others

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2475]
https://drive.google.com/file/d/1wGaf6zGwDH0nPXjHDEUCMyOHdvsbs7iT/view?usp=sharing

**Comment by joechengla** [comment]
https://drive.google.com/file/d/1Op2awU_9Qc9L0kCcXb_-ZMQp631k_qFt/view?usp=sharing

**Comment by chianger** [comment]
covered by #2481

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel 2
Android 8.1.0
Rocket 3.1.0(6550)
WebView 68.0.3440.91
