### ISSUE TITLE
User cannot set rocket as default browser directly via settings

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2504]
Prerequisite:
1. No default browser is chosen
2. Reset the Rocket app in system settings

STR:

1. Launch the app
2. Enter settings twice
3. Close rocket and tap the 'make rocket default browser' notification
4. Return to rocket browser 
5. Tap 'make default browser' and choose rocket as always open
6. Go to Gmail, open a link

Expected result
Rocket should be opened after tapping the link in Gmail

Actual result:
System prompts user to choose default app after opening link from Gmail

Reproduce Rate: 100%

Device: Advan i5C
Rocket Ver.: 3.1.0(6550)
Android Ver.: 5.1
WebView: 66.0.3359.158

Clip:
https://drive.google.com/open?id=1JyvjfaG5R2y-hsuvF4anANZbMJ0Mz4Br

**Comment by cynthiatang** [comment]
dup: #2031
