### ISSUE TITLE
No page reload was observed when unblocking images

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2508]
Prerequisite:
N/A

STR:

1. Launch Rocket
2. Visit a web page
3. Open menu, tap Block Images
4. Tap Block Images again to unblock the images

Expected result:
There should be a page reload after blocking and unblocking images

Actual result:
No page reload was observed when unblocking images on a web page

Reproduce Rate: 100%

Device: Advan i5c
Rocket Ver.: 3.1.0(6550)
Android Ver.: 5.1
WebView: 66.0.3359.158

Clip:
https://drive.google.com/open?id=1UWw2qJpz0pOT-5rKYApv2gFmE1_Cpp11

**Comment by Jacklin-ux** [comment]
If the photos in the webpage are shown and right (when unblock images), I think current behavior is fine.

**Comment by cynthiatang** [comment]
Hi @Jacklin-ux , thanks for your answer.

Hi @mlwang32 , I'd like to close this issue. Could you please modify this test case? Thanks

**Comment by mlwang32** [comment]
@cynthiatang , test case will be modified, thanks!
