### ISSUE TITLE
Update Firefox icon in notifications

### ISSUE THREAD

**Issue by initrd** [mozilla-tw/Rocket#2528]
The Firefox icon in notifications is pre-Quantum and should be updated.

![screenshot_20180901-115239](https://user-images.githubusercontent.com/1941695/44949027-f7b4d080-addd-11e8-933c-31f660a10008.png)

**Comment by chianger** [comment]
https://raw.githubusercontent.com/mozilla-tw/Rocket/master/app/src/main/res/drawable-hdpi/ic_notification.png  so the small app logo isn't really quantum or rocket style. that's the issue

**Comment by initrd** [comment]
FWIW focus-android has the right style - https://github.com/mozilla-mobile/focus-android/blob/master/app/src/main/res/drawable-hdpi/ic_notification.png

**Comment by chianger** [comment]
QAWanted to check if this is still a valid bug since we've rebranded.

**Comment by cnevinc** [comment]
@Jacklin-ux please advise!

**Comment by TLHuang** [comment]
The notification icon is updated, I also create a SVG file in case it's needed.
https://drive.google.com/open?id=1Hb2urBBcCD_Vyx48l1hvZUZ5VJggnJ5Y

**Comment by mTwTm** [comment]
Developer's note: since we've switched from png to xml, qa might wanted to check if there's a crash when Make default browser? and Firebase Notifications.

**Comment by Daisy-pliu** [comment]
Verify with 2 device:  ✅
**Device :**
1. Redmi 7.1.0 : [notification screen shot ](https://drive.google.com/file/d/1YXETSAVsok8bH7nCZwldgMTOpNyidDA_/view?usp=sharing)
2. Samsung Galaxy S7 Edge (8.0.0) : [notification screen shot ](https://drive.google.com/file/d/1F6X6-X9PA_jXRVQ9CJmaaS2A4Bfr1RLq/view?usp=sharing)
Please help check if the small icon @initrd  @TLHuang look as expected. Thanks

**Comment by initrd** [comment]
Looks great, thanks!

**Comment by TLHuang** [comment]
It looks good to me! Thanks!
