### ISSUE TITLE
new Private Browsing tab from menu

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2533]

**Comment by chianger** [comment]
relevant to #2546

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1KINi5uEAPf6NgAow0y3cO2-vbWxVm2kH/view?usp=sharing

**Comment by chianger** [comment]
maybe @rxu can take this

**Comment by chianger** [comment]
break down too #2679 so size:S

**Comment by elin-moco** [comment]
Hi,

My suggestion in method/object/value format:
Click on the "Private Mode" menu item: click/menu/private_mode

Although I guess it could become a toggle in the future (like turbo mode)
I think it's fine to go with "click" for now.

**Comment by Jacklin-ux** [comment]
Updated icon's string from "Private mode" to "Private browsing"
https://drive.google.com/file/d/1e3AUkmfr4sgqnPzQ8CrmfymG394QA14c/view?usp=sharing
