### ISSUE TITLE
It should not erase private browsing data (user unintended)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2555]
1. Kill Rocket from Task manager 
2. Launch Rocket 
3. Switch to Private browsing mode
4. Visit a website
5. Tap system Home Key
6. Open system settings

Expected Result:
 - Don't erase private browsing data

Actual Result:
 - Erase private browsing data
 - https://drive.google.com/open?id=1MbebrchUCq5RuRyj7sWOJZ6iWGmDWVXp

Reproduce rate 10/10

Rocket 3.1.0(6747).nightly
WebView version 68.0.3440.91
Pixel2 
Android 8.1.0

**Comment by chianger** [comment]
Is this a regression? I couldn't reproduce with Nightly (6747) or the production 3.1

**Comment by chianger** [comment]
#2615 #2629 have more similar but different STRs. Merging to this same bug.

**Comment by cnevinc** [comment]
I can reproduce it with 9.0 Pixel.
But I can't reproduce it with 8.1 Emulator.
This behaviour may be different among device/API level combination.
More testing is needed for e.g 7.0, 6.0 devices

**Comment by cynthiatang** [comment]
This issue could not be reproduced on devices with Android 6 or Android 7

@cnevinc 
The test result is Pass.  

Pixel2
Android 8.1.0
Rocket 3.3.0(7206).debug.bitrise
