### ISSUE TITLE
Rocket display problems with display cut-outs 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2560]
1. turn on display cutouts in developer options with Android 9
2. Open rocket https://drive.google.com/file/d/1owr4bz4hWkmoOKXdEf-PpLxhMX3noARC/view?usp=sharing

2.1 At the top, URL will get covered by notch (though the screenshot doesn't show) and the clock is very close to the URL
2.2 bottom tool bar becomes transparent

**Comment by chianger** [comment]
looks to me a low priority if developer option is required.

**Comment by chianger** [comment]
QAWanted to see if the latest nightly has it fixed.

**Comment by cynthiatang** [comment]
Verified: Fixed

https://drive.google.com/open?id=103iro4J-bLkMGEMEM18d7ZmkoQ23q6Q8

Rocket 3.3.0(7295).nightly
Webview: 69.0.3497.100
Pixel2
Android 9
