### ISSUE TITLE
After updating Rocket, app appears to automatically load second record on the history list as opposed to the first record.

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2577]
Prerequisite:
N/A

STR:

1. Launch Rocket
2. Visit a few pages, then check history, remember order of history 
3. Update to a new Rocket version 
4. Check history

Expected result:
The order of history should remain the same

Actual result:
First and second records are switched due to second record being loaded by the app after update

Reproduce Rate: 100%

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket versions: updating from 2.2.0(4869) to 3.2.0(6852)

Before update:
![rocket1](https://user-images.githubusercontent.com/746727/45357740-d03ddf00-b5f9-11e8-96a1-e9deb0f9a351.png)
After update:
![rocket2](https://user-images.githubusercontent.com/746727/45357753-db910a80-b5f9-11e8-8db5-266baaa69ab2.png)

**Comment by mTwTm** [comment]
If Kapalngi is still in tabs, I think it is opened and loaded again when you open the App.

**Comment by chianger** [comment]
QAWanted per above comment. If that's the case, we can close this as INVALID.

**Comment by mlwang32** [comment]
Clearing the tabs and closing the app before update will result in the right history order, issue closed
