### ISSUE TITLE
Twitter and Reddit favicon shows black background on history list

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2583]
Preconddition:
N/A

STR:
1. Launch Rocket
2. Visit twitter.com and reddit.com
3. Go to menu -> history 

Expected Result
 - Show Favicon as normal 

Actual Result
 - Favicon black background 

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket Version:
3.2.0(6852)

Screenshot:
![icon_issue](https://user-images.githubusercontent.com/746727/45401861-42a7d100-b685-11e8-9134-44b5ed562c98.png)

**Comment by mTwTm** [comment]
Fixed in #2579

**Comment by cynthiatang** [comment]
Verified: Fixed

Rocket 3.3(7295).nightly
webView 69.0.3497.100
Redmi 4A
Android 7.1.2
