### ISSUE TITLE
Twitter icon as top site on home page shows black background

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2586]
Precondition:
N/A

STR:
1. Launch Rocket
2. Remove one topsite on home page
3. Visit twitter.com 6 times 
4. Check twitter icon

Expected result:
Twitter icon should have blue backgroun

Actual result:
Twitter icon shows black background

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket Version:
3.2.0(6852)

Screenshot:
![homeicon](https://user-images.githubusercontent.com/746727/45402117-8e0eaf00-b686-11e8-9212-cedc9b89adc3.png)

**Comment by chianger** [comment]
reproducible on Pixel XL (android 8.1) looking at the favicon in history panel

**Comment by mTwTm** [comment]
Closed in #2579

**Comment by cynthiatang** [comment]
Verified: Fixed

Rocket 3.3(7295).nightly
webView 69.0.3497.100
Redmi 4A
Android 7.1.2
