### ISSUE TITLE
Opening popup windows will cause Rocket to crash

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2587]
Preconditions:
N/A

STR:
1. Launch Rocket
2. Visit http://popuptest.com
3. Tap Multi-PopUp Test #2 

Expected result:
Rocket will open new tabs for popups

Actual result:
Rocket will crash

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket version:
3.2.0(6852)

Clip
https://drive.google.com/open?id=14Ttkj-fX2fZbghxHrDed-DGUhIxblAPB

**Comment by chianger** [comment]
reproducible on Pixel XL (android 8.1)

**Comment by mTwTm** [comment]
Fixed in #2580

**Comment by cynthiatang** [comment]
Verified: Fixed

Pixel2 
Android 8.1.0
Rocket 3.2.0(6930).nightly
WebView 68.0.3440.91
