### ISSUE TITLE
Cookie policy keeps showing up

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2602]
Precondition:
N/A

STR:

1. Launch Rocket
2. Visit cnn.com
3. Tap search, visit cnn again

Expected result:
Cookie policy should show up only once

Actual result:
Cookie policy keeps showing up

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket:
3.1.1(6892)

Clip:
https://drive.google.com/open?id=1mcJFZYa97NU5rahAiV0WCfV1BL2rX90e

**Comment by cynthiatang** [comment]
Hi @mlwang32 ,
The expected result is wrong. If users don't tap x on the Cookie policy, it would keep showing up next time. Please refer the result in Chrome
