### ISSUE TITLE
Form history cannot be saved

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2604]
Precondition:
N/A

STR:

1. Launch Rocket
2. Go to linkedin website and log in, then log out
3. Tap on the username field

Expected result:
Rocket should display previously used username

Actual result:
Used username not shown

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket:
3.1.1(6892)

Clip:
https://drive.google.com/open?id=1mXXFmR3ouJne3vTzsL5nIY6wv6cMu3BN

**Comment by cynthiatang** [comment]
This issue can be reproduced in Pixel 2 with Android 8.1.0

Rocket 3.1.0(6550) and (6892)
Device: Pixel 2
Android 8.1.0
WebView: 68.0.3440.91

**Comment by cnevinc** [comment]
I'm confused. Did it previously work?  I think this feature is not controlled by us. Which spec you are looking at?

**Comment by mTwTm** [comment]
I suppose it was controlled by Webview and on newer Android versions it's controlled by Autofill, so probably not a regression, though.

**Comment by cynthiatang** [comment]
It works on devices with Android 5, 6 or 7. But It doesn't work on devices with Android 8 even if users use Rocket 1.0.

**Comment by chianger** [comment]
Autofill is not in current Rocket scope, so it is what it is depending on webview and android system behavior. WONTFIX
