### ISSUE TITLE
No snack bar message for opening image and link in new tab

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2605]
Precondition:
N/A

STR:

1. Launch Rocket
2. Visit a web page with images and links 
3. Long tap on a link/image, choose open link/image in new tab

Expected result:
A snack bar should show up indicating a new tab is opened

Actual result:
No snack bar is displayed

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket:
3.1.1(6892)

Clip:
https://drive.google.com/open?id=12h8LHtbFby9P1VuMrMOidkYyQoQ5zg-C

**Comment by cynthiatang** [comment]
This issue cannot be reproduced in Pixel 2 with Android 8.1.0

Rocket 3.1.1(6892)
WebView: 68.0.3440.91

**Comment by mlwang32** [comment]
This issue disappears after fixing the system menu to the bottom.

**Comment by chianger** [comment]
@mlwang32 is this still reproducible?

**Comment by mlwang32** [comment]
Verified fixed.

Device: Samsung Galaxy S8
Android 8
WebView: 69.0.3497.100
Rocket v. 3.3.0(7295)
