### ISSUE TITLE
Screen bottom is overlaid by bottom menu bar

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2606]
Precondition:
N/A

STR:

1. Launch Rocket
2. Visit google.com
3. Scroll to the bottom of page

Expected result:
Bottom of page should not be blocked by the bottom menu

Actual result:
Bottom menu overlaid on top of the page bottom

Device:
Samsung Galaxy S8
OS: Android 8.0.0
WebView: 68.0.3440.91

Rocket:
3.1.1(6892)

Screenshot:
https://drive.google.com/open?id=1fvHahaMLAwiLloWf7kZWFTQxy6iNlc1r

**Comment by cynthiatang** [comment]
Samsung Galaxy S8 --> Resolution | 1440 x 2960 pixels, 18.5:9 ratio (~570 ppi density)

This issue cannot be reproduced in Pixel2 with Android 8.0.0
Rocke 3.1.1(6892)
WebView: 68.0.3440.91

**Comment by mlwang32** [comment]
This issue can be resolved by fixing the native navigation bar at the bottom via a switch (a dot on the left side)

Screenshot:
https://drive.google.com/open?id=1nkMYm7rguoQ-FwIrvh5VNW2ARiEH0XBL

**Comment by chianger** [comment]
QAWanted to @mlwang32 to see if this still reproducible.

**Comment by mlwang32** [comment]
Verified fixed.

Device: Samsung Galaxy S8
Android 8
WebView: 69.0.3497.100
Rocket v. 3.3.0(7295)
