### ISSUE TITLE
Erase Rocket's private data after tapping whatsapp button in Chrome (pixel2 only)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2615]
* Default apps- Browser app: None
* Install WhatsApp 
* WhatsApp doesn't stay in TaskManager 

1. Launch Rocket
2. Visit a website in private mode
3. Switch to Chrome
4. Visit this webpage in Chrome 
    https://goo.gl/YZhEFJ
5. Tap WhatsApp icon 

Expected Result
 - Don't erase Rocket's private data

Actual Result
 - Erase Pocket's Private data
 -https://drive.google.com/open?id=1F8ucXs93hsClkzId_e-6A-l2LwJ9IaTG

Reproduce Rata: 5/5

Rocket 3.2.0(6930).nightly
WebView 68.0.3440.91
Pixel 2
Android 8.1.0

This issue cannot be reproduced in Samsung J7 and VIVO 1606

**Comment by chianger** [comment]
dup to #2555
