### ISSUE TITLE
User can still view images downloaded with rocket after turning off storage permission

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2619]
Precondition:
Reset rocket via system settings

STR:
1. Launch Rocket 
2. Visit a website with images or files to download 
3. Long press on an image 
4. Press "Save image" from context menu 
5. Check from Gallery or File manager 
6. Disable storage access permission from System Settings 
7. Check from Gallery or File manager

Expected result:
Image is not viewable and the storage access permission message will pop up

Actual result:
Image is still viewable

Device and Rocket version:
Rocket 3.1.1(6892)
Device: Samsung Galaxy S8
WebView: 68.0.3440.91
Android: 8.0.0

Clip:
https://drive.google.com/open?id=16o02Gbdq3AQL10E4R9fQS0l3XLmvNUbJ

**Comment by chianger** [comment]
Looks like the actual result is expected? @Jacklin-ux

**Comment by cnevinc** [comment]
This not a bug. Why do think the user shouldn't see the images? @mlwang32

**Comment by chianger** [comment]
INVALID bug.

**Comment by cynthiatang** [comment]
@mlwang32 Please modify test cases. Thanks

**Comment by mlwang32** [comment]
Test cases modified. Thanks.
