### ISSUE TITLE
Website's location permission dialogue disappears after switching to other app via task manager

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2623]
Precondition:
Allow location permission

STR:

1. Launch Rocket
2. Visit mapquest.com --> show the dialog "Don't ask again for this site until exit"
3. Tap task manager and choose another app (i.e. app store)
4. Tap task manager again to switch back to rocket
5. Visit mapquest.com again
6. Tap menu, then exit rocket
7. Relaunch rocket and visit mapquest.com

Expected result:
4. Location permission dialogue should remain
5. Location permission dialogue should appear
7. Location permission dialogue should appear

Actual result:
Location permission dialogue ceases to appear after step 4

Device:
Redmi 4X
OS: Android 7.1.2
WebView: 68.0.3440.91

Rocket:
3.2.0(6992)

**Comment by chianger** [comment]
https://github.com/chromium/permission.site is a more stable reference site.

**Comment by chianger** [comment]
QAWanted to verify if this is fixed

**Comment by mlwang32** [comment]
Retested Pass

Clip:
https://drive.google.com/open?id=16zFWu2_6RmI8M055NUQMMo9k2iYJfqwi

Rocket 3.4.0(7421)
Device: Nexus 5
WebView: 69.0.3497.100
Android: 6.0.1
