### ISSUE TITLE
Website's location permission dialogue won't appear after opening a link from another app

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2627]
Precondition:
Allow location permission

STR:

Launch Rocket
1. Visit mapquest.com --> show the dialog "Don't ask again for this site until exit"
2. Open a link via third party app --> dialogue disappears
3. Tap menu and exit the rocket
4. Relaunch rocket and visit mapquest.com

Expected result:
4. Location permission dialogue should appear

Actual result:
Location permission dialogue does not appear

Device:
Nexus 5
OS: Android 6.0.1
WebView: 68.0.3440.91

Rocket:
3.2.0(6992)

**Comment by cynthiatang** [comment]
This can be reproduced in Rocket 3.0.

**Comment by chianger** [comment]
QAWanted to verify if this is fixed

**Comment by mlwang32** [comment]
Retested Pass

Clip:
https://drive.google.com/open?id=1anK7NOHjmumjmKVI1oxmZ4NHOnrRJCue

Rocket 3.4.0(7421)
Device: Nexus 5
WebView: 69.0.3497.100
Android: 6.0.1
