### ISSUE TITLE
Further enhance #2610 (top site flashes)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2628]
STR:
1. open rocket
2. switch to other apps. launch more apps to drain the system memory
3. come back to rocket and see topsite page

Actual result:
topsite favicons flash

**Comment by mTwTm** [comment]
https://docs.google.com/spreadsheets/d/1DvW-Vs8lnsuMoX8JQ1TwDWoZzA3k5TNvIX6h_flAZdU/edit#gid=370641402 Done some benchmark on this, we have regressions in both DB query time and Decode time.
