### ISSUE TITLE
It would erase the private data when users tried to open other apps (Only Pixel2 with android 8.1.0)

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2629]
1. Kill all apps from the task manager
2. Launch Rocket 
3. Switch to private browsing mode
4. Visit a website
5. Tap system Home 
6. Launch any app (ex.: Play store, gmail...)

Expected Result
 - Don't erase the private data

Actual Result:
 - It would erase the private data
 - Video: https://drive.google.com/open?id=1Rl4eeWZoz56GlZ_SWu3BeMUuuyrIv4-P

Pixel2
Android 8.1.0
Rocket 3.2.0(7027)
WebView 68.0.3440.91

Note: This issue cannot be reproduced in Oppo, Redmi 4A, Vivo

**Comment by chianger** [comment]
dup to #2555
