### ISSUE TITLE
Youtube video will exit fullscreen mode when switching from landscape fullscreen to portrait (could be device or OS specific issue)

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2638]
STR:

1. Launch Rocket
2. Visit youtube and play a video in fullscreen
3. Rotate to landscape
4. Rotate back to portrait

Expected result:
On step 3 and 4, video should stay in fullscreen mode

Actual result:
Video exits fullscreen when switching from landscape to portrait

Device and Rocket version:
Rocket 3.2.0(7057)
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

Clip:
https://drive.google.com/open?id=19AgTGP0H7Qfasju6WMM9EqHOyhcJuV88

**Comment by cynthiatang** [comment]
@mlwang32 could you use Firefox Focus to test it again? Thanks

**Comment by mlwang32** [comment]
@cynthiatangt tested on Firefox Focus 7.0.4 (Build 322601626) using Nexus 5, youtube stay in fullscreen mode when rotating the device from landscape to portrait.

**Comment by cynthiatang** [comment]
I just checked Myron's test results again

Data: 09/13
Test result: Pass 
Rocket 3.1.1(6892)
Device: Samsung Galaxy S8
WebView: 68.0.3440.91
Android: 8.0.0

Data: 09/03
Test result: Pass 
Rocket 3.1.0(6668)
Device: Advan i5C
WebView: 68.0.3440.91
Android: 5.1

**Comment by cynthiatang** [comment]
@mlwang32 Could you please test it on Advan i5C with Rocket 3.1.0(6668) again?

**Comment by chianger** [comment]
with above information that means it's not a regression from Rocket software.

**Comment by chianger** [comment]
decision: we won't handle this issue for because probably  nothing we can do and most importantly we can accept this from UX viewpoint. 
WON'TFIX

**Comment by cynthiatang** [comment]
@mlwang32 please modify this test case. Thanks.

**Comment by mlwang32** [comment]
@cynthiatang test case modified accordingly, thanks!
