### ISSUE TITLE
It should show what number/ total number of findings

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2639]
1. Launch Rocket 
2. Visit a website
3. Go to Menu -> Find in page
4. Enter a word

Expected Result:
 - Show what number/ total number of findings
<img width="336" alt="screen shot 2018-09-19 at 10 59 45" src="https://user-images.githubusercontent.com/12458450/45728642-6629c900-bbfb-11e8-952a-b298ab1cb9a3.png">

Actual Result:
 - no number information
![screenshot_20180919-105700](https://user-images.githubusercontent.com/12458450/45728673-9a04ee80-bbfb-11e8-845c-6ab116a5a529.png)

Pixel2 
Android 8
Rocket 3.2.0(7075)
WebView: 69.0.3497.100

**Comment by mlwang32** [comment]
Observed this issue on the following devices:

1. Redmi 4X
WebView: 68.0.3440.91
Android: 7.1.2

2. Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

3. Advan i5C
WebView: 68.0.3440.91
Android: 5.1

**Comment by cynthiatang** [comment]
Verified: Fixed

Rocket 3.3(7295).nightly
webView 69.0.3497.100
Redmi 4A
Android 7.1.2
