### ISSUE TITLE
Find in page - Users could not see the finding sometimes when the keyboard is open

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2646]
1. Launch Rocket 
2. Visit a webpage
3. Tap Menu -> Find in page
4. Tap search field and enter a word
5. Tap V button to find next finding 

Expected Result:
 - Move the finding to the center of the display area (if possible)

Actual Result:
 - Users could not see the finding sometimes.
 - https://drive.google.com/open?id=1AYKWQ_NOQKVC5l293iT9hh5hsjD5Fz9I

Reproduce Rate 10/10

Pixel2
Android 8.1.0
Rocket 3.2.0(7075).nightly
WebView 69.0.3497

**Comment by chianger** [comment]
If trying other browsers like Focus, or Chrome would that be different result?

**Comment by chianger** [comment]
per discussion, expected result will be:
once user taps on the up/down button, hide the keyboard .

**Comment by mlwang32** [comment]
Observed this issue on the following devices:

1. Redmi 4X
WebView: 68.0.3440.91
Android: 7.1.2

2. Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

3. Advan i5C
WebView: 68.0.3440.91
Android: 5.1
