### ISSUE TITLE
(InProduct promotion) Provide user feedback 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#265]
p1.5
(Positive to Google Play, Negative to input.mozilla.org)

**Comment by chianger** [comment]
@joechengla what URL should we use for input.mozilla.org?

**Comment by carol-mozilla** [comment]
visual spec : https://drive.google.com/open?id=0B1V1eo-I8g3dc0E2MktGa2xSaWs

**Comment by chianger** [comment]
Here's the URL.
https://qsurvey.mozilla.com/s3/Firefox-Rocket-Input

**Comment by dakaizou** [comment]
verified in build 1512
