### ISSUE TITLE
Cannot watch Facebook full screen landscape video

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2661]
Screen will turn black. YouTube works fine

**Comment by cynthiatang** [comment]
Seems an issue when users use Rocket with new Webview 69.x.xxxx.xx.xx

**Comment by mlwang32** [comment]
Retest result (Play video on Youtube and Facebook on fullscreen landscape mode)
Rocket v. 3.2.0(7119).nightly

FB Fail, Youtube Pass
Device: Redmi 4X
WebView: 69.0.3497.100
Android: 7.1.2

FB Fail, Youtube Pass 
Device: Nexus 5
WebView: 69.0.3497.100
Android: 6.0.1

FB Fail, Youtube Pass
Device: Advan i5C
WebView: 69.0.3497.100
Android: 5.1

**Comment by mlwang32** [comment]
Retest result (Play video on Facebook on fullscreen landscape mode)
Rocket v. 3.2.0(7119).nightly

Pass
Device: Nexus 5
WebView: 68.0.3440.91
Android: 6.0.1

Pass
Device: Advan i5C
WebView: 68.0.3440.91
Android: 5.1

**Comment by chianger** [comment]
Some more testing result
[Mozilla Report_Rocket_VideoTesting_20180921.pdf](https://github.com/mozilla-tw/Rocket/files/2404384/Mozilla.Report_Rocket_VideoTesting_20180921.pdf)
basically only it happens only on webview69 , and regardless of Rocket 3.1 or 3.2.

**Comment by chianger** [comment]
WONTFIX SINCE IT'S not actionable
