### ISSUE TITLE
Handling Permissions Denials

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2692]
Please only show the app settings button only after the user has set “Don’t ask again”. If the user has not set the permission to “Don’t ask again”, instead of taking the user to the settings, have the button request the permission again.

**Comment by Jacklin-ux** [comment]
Proposal: https://files.slack.com/files-pri/T027LFU12-FD2AY91GQ/image.png

**Comment by mTwTm** [comment]
Fixed in #2692
