### ISSUE TITLE
Rocket feedback survey page automatically turns when user picks an answer

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2694]
STR
1. Launch rocket
2. Tap menu > settings > give feedback
3. Tap No, send feedback
4. Answer the multiple choice questions

Expected result:
On every page, user can pick an answer and tap right arrow to switch to the next question.

Actual result
On the fourth question, user picks an answer, then automatically gets sent to the next page without having to tap right arrow.

Device Info
Nexus 5
Android 6.0.1
WebView: 69.0.3497.100

Rocket version:
3.3.0(7202)

Reproduce Rate
100%

Clip:
https://drive.google.com/open?id=1FHUoHp2PqdByC3zNNu-TxZ4n9btCTNGY

**Comment by chianger** [comment]
this is on the website's end, let's ask @elin-moco

**Comment by elin-moco** [comment]
@chianger expected result.
the 'next' button is for multiple choices and when user don't require an answer.

**Comment by chianger** [comment]
thank you @elin-moco for clarifying and thank you @mlwang32 for filing the issue. 
It's clear now so I'm closing this as invalid.
