### ISSUE TITLE
[Find in page] wrong number / total numbers

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2707]
1. Launch Rocket
2. Go to goo.gl/hbYHJM
3. Open Find in page
4. Enter moz
5. Tap back key twice (via the visual keyboard)

Expected Result
 - It should show 1/51

Actual Result
 - it shows 3/51. This issue can be reproduced in Focus and Fennec
 - https://drive.google.com/open?id=1C55q2ug06_h_0EwRWuG8yTPecGcMswDv

Reproduce Rate 10/10

Rocket 3.3.0(7295).nightly
Webview 69.0.3497.100
All devices

**Comment by chianger** [comment]
Same behavior as other browsers: Chrome, Fennec, Focus so won't fix.
