### ISSUE TITLE
[Find in page] Incorrect number of findings and blocked finding

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2708]
STR:
1. Launch rocket
2. Visit https://en.m.wikipedia.org/wiki/Tasuku_Honjo
3. Tap menu -> find in page
4. Enter 'the' into search field
5. Tap down arrow next to the search field and check the findings

Expected result:
Orange highlight should go from the first finding to the last

Actual result:
1. First finding is not shown, possibly due to incorrect number of findings being displayed
2. Some of the findings were blocked

Clip:
https://drive.google.com/open?id=1gvfs1XzX0nmBgAyTtiWR8Khx3uDDWc3N

Device: Advan i5C
WebView: 69.0.3497.100
Android v.5.1
Rocket v.3.3.0(7295).nightly

Device: Samsung Galaxy S8
WebView: 69.0.3497.100
Android v.8
Rocket v.3.3.0(7295).nightly

**Comment by mlwang32** [comment]
Unable to reproduce blocked finding on the following device due to content change, but number of findings issue was also observed

Device: Redmi 4X
WebView: 69.0.3497.100
Android v.7
Rocket v.3.3.0(7295).nightly

**Comment by chianger** [comment]
relevant to #2707

**Comment by chianger** [comment]
compare with Chrome the behavior seems the same. 
QAWanted:  can retest and  compare with  Chrome please

**Comment by ivantw08** [comment]
Rocket 3.5(7759).nightly
Device: Advan i5C
WebView 69.0.3497.100
Android: 5.1
work now 
-------------------
compare to google chrome. 
Orange highlight should go from the first finding to the last
