### ISSUE TITLE
Another way for dominant color

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#2722]
**Why/User Benefit/User Problem**
Top-sites needs UI refresh. One requirement is to make the dominant color more close to the icon itself.
Currently, we can get the appropriate color. But for Facebook the result is not good enough.
We might need to find a better algorithm to find the "best" color.

**User story**
@Jacklin-ux  Please help with this

**Acceptance Criteria (how do I know when I’m done?)** 
@Jacklin-ux  Please help with this
1. 
2.
3.

**Additional context**

**Comment by cnevinc** [comment]
we are using HSV namespace to get the dominant color. See https://www.lifewire.com/what-is-hsv-in-design-1078068 for HSV

**Comment by Jacklin-ux** [comment]
The criteria is the color looks almost the same as the icon itself. 
If can't do what we expect, use current design.  
So I think we need to discuss when is the deadline to stop studying then make a decision.

**Comment by chianger** [comment]
part of #2299

**Comment by mTwTm** [comment]
Invalid
