### ISSUE TITLE
User cannot choose file to upload

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2724]
Description
User cannot upload file

STR
1. Launch Rocket
2. Visit a website (i.e. encodable.com/uploaddemo) that can test file upload
3. Upload a file

Expected result
User can upload files

Actual result
User cannot choose file to upload

Clip
https://drive.google.com/open?id=1BQpEAwIfijvLbVW08IW4nQDT-qUzG8ax

Device and Rocket Info
Rocket 3.4.0(7421)
Device: Nexus 5
WebView: 69.0.3497.100
Android: 6.0.1

Working version: Rocket 3.3.0 (7339)
Clip
https://drive.google.com/open?id=1iU2DKQ9wksWUcUlHInIiFmjr1yb0Whwj

Device: Nexus 5
WebView: 69.0.3497.100
Android: 6.0.1

**Comment by chianger** [comment]
I can reproduce with PixelXL (android 8.1) using v3.4. 
Tried FB and failed to upload photo/video, but I wonder if that was also supposed to work. 
QAWanted to look for regression window, and validate if FB also works back at some point.

**Comment by mlwang32** [comment]
Retest pass on encodable.com/uploaddemo

Rocket 3.4.1(7492)
Device: Redmi 4A
WebView: 69.0.3497.100
Android: 7.1.2

**Comment by chianger** [comment]
I think #2738 closes this.

**Comment by chianger** [comment]
This issue can be reproduced again. v1.0.1(8154)
