### ISSUE TITLE
Strange black block on the banner

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/Rocket#2726]
1. Launch Rocket

Expected Result:
 - No strange black block on the banner

Actual Result:
 - Video: https://drive.google.com/open?id=155KUN41U_laqdAJ_WPdkO40UPYmXryoe
 - ![screenshot_2018-10-05-21-02-09-231_gro allizom zelda beta](https://user-images.githubusercontent.com/12458450/46537641-6527b580-c8e4-11e8-84fc-32f0a896fb69.png)

Rocket 3.3.0(7404).nightly
WebView: 69.0.3497.100
Redmi Note 4X
Android 7.0

**Comment by chianger** [comment]
heard this was likely fixed. QAWanted to verify.

**Comment by cynthiatang** [comment]
It works for me.
