### ISSUE TITLE
Turn on night mode when watching video at the first time, video is paused due to adjust brightness dialog is popup.

### ISSUE THREAD

**Issue by josephyu1110** [mozilla-tw/Rocket#2748]
**Describe the bug**
Turn on night mode when watching video at the first time, video is paused due to adjust brightness dialog is popup.

**Steps To Reproduce**
1. Clear app data
2. Go to browser and watch video on youtube
3. Open menu and turn on night mode

**Expected behavior**
Video will not be paused when adjust screen brightness

**Actual behavior**
Video will be paused when adjust screen brightness

**Screenshots/videos**

**Device info (please complete the following information):**
 

**Reproduce rate**
100 %

**Additional context**

**Comment by chianger** [comment]
per discussion with @Jacklin-ux this is expected :)
