### ISSUE TITLE
(Night mode) Strange brightness when drag the thumb to the end of left side

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#2750]
Enable night mode then drag the thumb on the slider. When drag the thumb to the end of the left side, the brightness will be using system brightness instead of the darkest brightness
![screenshot oct 15 2018 10_34_53 am](https://user-images.githubusercontent.com/22672569/46927061-3c32bd80-d066-11e8-825e-e8482a3aff75.png)

**Comment by weslyhuang** [comment]
Joseph can't repro it. Can QA help on it? tks

**Comment by vanceyen** [comment]
Seems like this bug only happens on Google native Android phone(e.g. Pixel 2), also @mxlius is working on this one already ?

**Comment by mxlius** [comment]
Fixed in #2752
