### ISSUE TITLE
(Night mode) Http urls's earth icon color 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2757]
**Describe the bug**
Http urls's earth icon's color  should be white.

**Steps To Reproduce**
1. Launch Rocket
2. Menu -> night mode
3. Go to bbc.com website page.
4. See the top left corner. 

**Expected behavior**
Earth icon should be white
**Actual behavior**
Earth icon is black

**Screenshots/videos**
This is screenshot in night mode.
[https://drive.google.com/file/d/18jArEMrGmg_Fl3okyFiODMXdR1LO120l/view?usp=sharing
](https://drive.google.com/file/d/18jArEMrGmg_Fl3okyFiODMXdR1LO120l/view?usp=sharing
)This is screenshot in private mode.
https://drive.google.com/file/d/1YsA-B0wP-0FoOWfQfk7Y2SemVLom6sbE/view?usp=sharing

**Device info (please complete the following information):**

Device:Advan i5C, Nexus 5 
OS: Android: 6.0.1, Android: 5.1 
Webview 69.0.3497.100
Version 3.4.1(7597)
( Redmi 4X doesn't have this problem)

**Comment by cnevinc** [comment]
tint won't work in Android 23-. Needs more time for this. We'll need to change the implementation of how to change image
