### ISSUE TITLE
VPN Recommender

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2770]
**Why/User Benefit/User Problem**
To make something easier ...etc

**User story**
As a ..., I would like ...

**Acceptance Criteria (how do I know when I’m done?)** 
1.
2.
3.

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1M4OaLAjzSg98G6IRjxerte-QTXLGs3aW/view?usp=sharing

**Comment by weslyhuang** [comment]
need to get a logo from partner (BD).

**Comment by chianger** [comment]
joseph is taking this task. adding this to sprint H, though not yet sure about the effort estimation.

**Comment by elin-moco** [comment]
@chianger @josephyu1110  
My suggested event structure would be (in method/object/value format):
Show VPN Button: show/home/vpn  (extra: {vpn_installed: true|false})
Click on VPN Button: click/home/vpn (extra: {vpn_installed: true|false})
"Yes" on VPN Doorhanger: click/vpn_doorhanger/positive
"No" on VPN Doorhanger: click/vpn_doorhanger/negative
Dismissed VPN Doorhanger: click/vpn_doorhanger/dismiss

**Comment by Pekochen** [comment]
visual spec:
https://drive.google.com/drive/u/1/folders/1RvevfiOYn7jYJTf_jDwZ1rwlc0zjdz4O?ogsrc=32
logo assets:https://drive.google.com/open?id=1AAl1Ui45Vc7D9vwG5cTI6JOtFsQmcirA
