### ISSUE TITLE
Screenshot has alignment issues when the pages comes with fixed header and footer.

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2772]
**Describe the bug**
Screenshot has alignment issues when the pages come with fixed header and footer.

**Steps To Reproduce**

1. Go to a website with fixed header or footer.(example page: https://goo.gl/kHu277 )
2. Swipe up to middle of the page 
3. Click screenshot
4. Menu ->My shot -> click the image

**Expected behavior**
A full screen shot with header on the top and footer at the bottom. 

**Actual behavior**
Header and Footer alignment is not at position.

**Screenshots/videos**
https://drive.google.com/file/d/1tJWBLlnFOS596E3EH4Rn1_TyykoSAn97/view

**Device info (please complete the following information):**
- Device:Advan i5C, Nexus 5 , Redmi 4X
- OS: Android: 6.0.1, Android: 5.1 ,Android: 7.1.2
- Webview 69.0.3497.100
- Version 3.4.1(7597)

**Reproduce rate**
100%

**Comment by chianger** [comment]
Screenshot captures the full page on webview at that moment. Likely not much we can do w/o changing the architecture.

**Comment by chianger** [comment]
Limitation: WON't FIX.
