### ISSUE TITLE
(crash) App crashed when visit bukalapak.com

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2779]
**Describe the bug**
 App crashed when visit bukalapak.com

**Steps To Reproduce**
1. Launch Rocket 
2. Visit bukalapak.com

**Expected behavior**
open the page
**Actual behavior**
crash 

**Screenshots/videos**
https://drive.google.com/file/d/1o_v-l-bpH9vGEj8lpVyqp5sTThA4247D/view

**Device info (please complete the following information):**

- Device:Advan i5C, Nexus 5 , Redmi 4X
- OS: Android: 6.0.1, Android: 5.1 ,Android: 7.1.2
- Webview 69.0.3497.100
- Version 3.4.1(7685)

**Comment by chianger** [comment]
Tried using Pixel XL (android 8.1, webview 70) also crashed after visiting bukalapak.com

**Comment by chianger** [comment]
3.4.1 (7492) works fine on the same device. So it's a regression.
