### ISSUE TITLE
Change back Language to English doesn't work in Give Feedback area

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2794]
**Describe the bug**
Change back Language to English doesn't work in Give Feedback area

**Steps To Reproduce**
1. Launch Rocket
2. Tap on Menu and then Settings
3. Tap on Language and choose "Indonesian"
4.  Back to Settings, tap on Language and choose "English"
6. Tap on Give feedback

**Expected behavior**
Showed in English 
**Actual behavior**
Showed in Indonesia.
**Screenshots/videos**
https://drive.google.com/open?id=1WH1ezZy_2V2eb093jBpkEdcGBINGA1ov

**Device info (please complete the following information):**

-  Rocket 3.5(7759).nightly
- Device: Advan i5C
-  WebView 69.0.3497.100
-  Android: 5.1

**Comment by chianger** [comment]
Same as #2828  maybe? Firebase doesn't reset user group.

**Comment by chianger** [comment]
QAWanted to retest this since we've changed the firebase config.

**Comment by ivantw08** [comment]
@chianger  

There is another translate issue,but I think they are  same config issue. So i post here.

Step:
1.setting -> change language to Indonesian
2.click give back (kirimkan masukan)

result:
 show description in English .

**Comment by Daisy-pliu** [comment]
Would like to mention another translate issue, in private mode push notification.

**Step:**
1. fresh install
2. launch app
3. click [setting] and change languague to [indonesia]
3. click [private mode] icon on menu
4. search [firefox] in private mode
5 close app 
6. relauch app

**Actual:**
it shows notification "erase private browsing history" in English
**Result:**
it shows notification "erase private browsing history" in Indonesia

**Comment by Daisy-pliu** [comment]
Test Result: ✅
Device Build: 1.0.9 (9284).nightly
Device:  Redmi 4X (7.1.2)
Webview: 71.0.3578.99
