### ISSUE TITLE
menu layout is not right arrangement

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2797]
**Describe the bug**
Menu layout arrangement is not same as testcase's description.

**Steps To Reproduce**
Launch Rocket and tap on Menu button

**Expected behavior**
### description:
Menu should display in following order:
First row
  - Downloads
  - History
  - My shots
  - Turbo mode (with enabled by default)

Second row
  - Block image (with disabled by default)
  - Clear cache
  - Settings
  - Exit
Third row (bottom toolbar, icons only)

  - Next page
  - Refresh
  - Add to home screen
  - Share

**Actual behavior**
see the screenshot

**Screenshots/videos**
https://drive.google.com/open?id=1IOeiZA8wpMDYwG1q00wloshQBlHmLmsv

**Device info (please complete the following information):**
 all devices 

Notes: Is this the old version's testcase? Because the testcase doesn't include Private mode and Night mode. How is the right arrangement?

**Comment by chianger** [comment]
per discussion with @Jacklin-ux this is expected result. 
@ivantw08 please modify the test cases accordingly.
