### ISSUE TITLE
Turbo mode turn off/on without toast

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2798]
**Describe the bug**
Turbo mode turn off/on without banner notification 

**Steps To Reproduce**
1. Launch Rocket
2. Visit a website
3. Tap on Menu ->setting
4. Tap on Turbo mode
5. Tap on Menu ->setting 
6. Tap on Turbo mode

**Expected behavior**
4.Turbo mode is off, webpage is reloaded, and Menu is dismissed. A banner is shown to notify user

**Actual behavior**
No banner is shown to notify user. 

**Screenshots/videos**
https://drive.google.com/open?id=1gnHBnPH-ynMsdq1A6fzMjcqLmBiIXixJ

**Device info (please complete the following information):**

- Device:Advan i5C, Nexus 5 , Redmi 4X
- OS: Android: 6.0.1, Android: 5.1 ,Android: 7.1.2
- Webview 69.0.3497.100
- Version 3.5(7759)

**Comment by ivantw08** [comment]
3 different ways to turn on/off turbo mode :
1. turn off turbo mode in onboarding. 
It works, I turned off the turbo mode. Both menu's icon and menu->setting's turbo were turned off.
2.Menu->icon
It works, I turned off the turbo mode.   Menu->setting's turbo was  also turned off.
3. Menu->setting->turbo mode 
It's not work. I can switch the toggle button.There is no toast and  menu's turbo icon was still turn on.

**Comment by chianger** [comment]
dup of #2274?

**Comment by chianger** [comment]
since #2801 PR is for this.

**Comment by mTwTm** [comment]
If this bug is about 3. Menu->setting->turbo mode
It's not work. I can switch the toggle button.There is no toast and menu's turbo icon was still turn on. then it is fixed in #2801. But we don't show Turbo mode toast in settings though. Let's close this and if we need to show a toast let's file another bug.

**Comment by weslyhuang** [comment]
@Jacklin-ux would you help confirm if we expect a toast when turn off turbo mode via menu --> setting --> turbo switch? (there is a toast if we turn off turbo mode in menu --> turbo mode icon). I didn't find the answer in [UX Spec 8.6: Turbo mode switch](https://drive.google.com/drive/folders/1JgiBs3_TcenMb-rSw47tnRq4pRDLYGmL) but per [test case 78](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit#gid=560240316) there should be a toast? (and it's test pass before)

**Comment by weslyhuang** [comment]
anyway I don't see as a blocker even if that's a regression. just to clarify and see if we need a follow-up bug to fix it in the future.

**Comment by Jacklin-ux** [comment]
3 different ways to turn on/off turbo mode :

1. turn off turbo mode in onboarding.
No toast (because users can see the status of the switch)
2. Menu->icon
*Show toast (after pressing turbo mode icon, users can't see the status of the switch, so show a toast to remind users)
3. Menu->setting->turbo mode
No toast (because users can see the status of the switch)

**Comment by weslyhuang** [comment]
1. so the toast behavior is expected and the problem mentioned in the title is actually invalid.
2. I still met turbo mode on/off status not sync issue with v3.4.1 (build 7492), though. Will add video in #2274.

**Comment by ivantw08** [comment]
Device:nexus 5
OS: Android: 6.0.1
WebView: 69.0.3497.100
Firefox Lite: 1.0.0(7855)

**Comment by mxlius** [comment]
@ivantw08 What's the reason to reopen this issue?
I thought Jack has confirmed current behavior matches expectation, should we follow up update the test case or UX Spec?

> 3 different ways to turn on/off turbo mode :
> 
>     1. turn off turbo mode in onboarding.
>        No toast (because users can see the status of the switch)
> 
>     2. Menu->icon
>        *Show toast (after pressing turbo mode icon, users can't see the status of the switch, so show a toast to remind users)
> 
>     3. Menu->setting->turbo mode
>        No toast (because users can see the status of the switch)
> 
> 
> Current behavior is expected.

**Comment by ivantw08** [comment]
Sorry is my mistake. I should be another new issue #2838
