### ISSUE TITLE
Shortcut function is not work

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2799]
**Describe the bug**
Shortcut function is not work

**Steps To Reproduce**
1. Launch Rocket and visit a website
2. Menu->shortcut icon

**Expected behavior**
Create desktop shortcuts for web pages

**Actual behavior**
Nothing happened 

**Screenshots/videos**
https://drive.google.com/open?id=1n1EEY2q1aP5LYzjyKt5x56i9nYn5O4Jb

**Device info (please complete the following information):**
- Device:Advan i5C, 
- OS: Android: Android: 5.1 
- Webview 69.0.3497.100
- Version 3.5(7759)

(nexus and Redmi work)

**Comment by chianger** [comment]
dup of #2714
