### ISSUE TITLE
Youtube's  icon not appear in history list

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2800]
**Describe the bug**
I am not sure if it is a bug. Most website showed the icon in history list. But Youtube's icon didn't show up.

**Steps To Reproduce**
1. Visit Youtube
2. Menu -> history

**Expected behavior**
Show all Histroy.

**Actual behavior**
Youtube icon didn't show up .

**Screenshots/videos**
https://drive.google.com/open?id=1ikw8XPEDX4tzwipxyXckFz-5WOaAluzl

**Device info (please complete the following information):**

- Device:Advan i5C, Nexus 5 , Redmi 4X
- OS: Android: 6.0.1, Android: 5.1 ,Android: 7.1.2
- Webview 69.0.3497.100
- Version 3.5(7759)

**Comment by chianger** [comment]
this is by design

**Comment by mTwTm** [comment]
Youtube's icon is too blurry (by spec, below 25 x 25), so we replaced it with a letter.
