### ISSUE TITLE
unable to make default page

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2802]
**Describe the bug**
1. unable to make default browser,

**Steps To Reproduce**
1. Launch Firefox
2. Menu ->setting
3. click make default browser

**Expected behavior**
Show a notification "Changing setttings...It may take a while"
Show "Changing settings" under "Make default browser" in settings 

**Actual behavior**
open a web page.

**Screenshots/videos**
https://drive.google.com/file/d/1dm6NN_6CYuumFuWZuXKT1W1yBSEFZ2kI/view

**Device info (please complete the following information):**

-  Rocket 3.5(7759).nightly
- Device: Advan i5C
-  WebView 69.0.3497.100
-  Android: 5.1

**Comment by chianger** [comment]
Likely an invalid bug per discussion offline. @ivantw08 please revisit this and act accordingly.

**Comment by ivantw08** [comment]
yup you are right. Close the issue.

**Comment by ivantw08** [comment]
Rocket 3.5(7759).nightly
Device: Advan i5C
WebView 69.0.3497.100
Android: 5.1

This is not a bug. Is different reaction in android 5.

**Comment by ivantw08** [comment]
fix the test case. test case number 58.
