### ISSUE TITLE
Context menu in private mode doesn't show up

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2804]
**Steps To Reproduce**
1. Go to private mode
2. visit Youtube or any site
3. Long press a link or image 

**Expected behavior**
Show context menu for sharing 
 
**Actual behavior**
nothing happened 

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
https://drive.google.com/open?id=17iL6tecO4sSMJhUkboIU7Npzhqg1FRtI

**Device info (please complete the following information):**

- Rocket 3.5(7759).nightly
- Device: Advan i5C
- WebView 69.0.3497.100
- Android: 5.1

**Comment by chianger** [comment]
QAWanted to check if it's regression. I had seen it work on 3.4.1 with z3c (android 5).

**Comment by ivantw08** [comment]
@chianger  3.4.1 work as expected.

**Comment by ivantw08** [comment]
version 7545,7587 not work 
version 7492,7518, work
