### ISSUE TITLE
website's icon don't showed in bookmark

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2805]
**Steps To Reproduce**
1. Launch Rocket
2. Menu -> bookmark

**Expected behavior**
showed the earth icon

**Actual behavior**
show the website's icon (Favicon?)

**Screenshots/videos**
this is bookmark's images 
https://drive.google.com/open?id=1HctPW10IxChHFBf-ML7P5Mj6u7_qmBU9

this is history's image
https://drive.google.com/open?id=1isYx21_TBMT3Dg_iY1Xs_5Kg_v59bupe

I think bookmark's layout should have same layout as  history's layout

**Device info (please complete the following information):**
all devices

**Comment by chianger** [comment]
this is a known UX enhancement. label as feature.

**Comment by mTwTm** [comment]
Duplicate of #2121
