### ISSUE TITLE
Spike for content portal (news): efforts estimation and break down

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2808]
For #2712

**Comment by mTwTm** [comment]
Identified item to study:
@cnevinc : Bottom Drawer behavior (touch from bottom), Navigation flow, Dynamic peek height (No half page when no content)
@mTwTm : Persistent layer, 3 sec no touch behavior, Worker Manager (Background) [P2]

**Comment by mxlius** [comment]
@mTwTm Here's my prototype branch
https://github.com/mozilla-tw/Rocket/tree/max/exp/india_content_portal

I user this to create pojo parser
http://www.jsonschema2pojo.org/

**Comment by chianger** [comment]
per discussion during feature grooming. 
#2712 is XL.
