### ISSUE TITLE
Bookmark's url must contain "https://" or "http://"

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2809]
**Steps To Reproduce**
1. Launch Rocket and open a website
2. Click menu and click the star 
3. Menu->bookmark
4. Tap : next to a bookmark
5. Tap "Edit" to open edit bookmark page
6. Change location (yahoo.com)
7. Save 
8. Tap the bookmark

**Expected behavior**
open the website

**Actual behavior**
blank page 

**Screenshots/videos**
https://drive.google.com/file/d/13iDXOVrp3ylygs05Go_hjUxSD7zHprhI/view

**Device info (please complete the following information):**

- Rocket 3.5(7759).nightly
- Device: Advan i5C
- WebView 69.0.3497.100
- Android: 5.1

**Comment by chianger** [comment]
more like a feature request?

**Comment by chianger** [comment]
dup of #2102
