### ISSUE TITLE
Verify Rocket events to amplitude

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2810]
follow up #2711

**Comment by elin-moco** [comment]
Just went through 1st round of verification with Nevin:
https://docs.google.com/spreadsheets/d/1gQ-RRr9DNaN1qWT40ldfhnl6PL4j-sY885nIeFhgQpA/edit#gid=428866153
There are some discrepancy found.

Nevin will update the script, having Frank load data from a different date,
and we'll verify a gain.

**Comment by chianger** [comment]
up and running on production.
