### ISSUE TITLE
Dialog's text is not match

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2826]
**Steps To Reproduce**
1. Launch Rocket and navigate through the app with the wizard steps (1st time) 
2. Make sure the "Send usage data" is disabled from rocket setting.
3. Force Stop Rocket app and launch repeatly for 5 times

**Expected behavior**
"Yes, rate 5 star","No, send feedback"
**Actual behavior**
https://drive.google.com/open?id=1Uq0zs8-yOSS7dFLgYa8agZgGrfzYaGFj

**Device info:**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by mTwTm** [comment]
That's a text change made in this sprint.

**Comment by chianger** [comment]
@ivantw08 we made this change #2693 on purpose. 
Please update test cases.
