### ISSUE TITLE
Rating card's dialog language doesn't tanslated

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2828]
**Steps To Reproduce**
1. change language to indonesia
2. disable send data
3. relaunch app 5 times

**Expected behavior**
Rating card dialog should change language to indonesia.
**Actual behavior**
A clear and concise description of what you actually discovered.

**Screenshots/videos**
https://drive.google.com/open?id=12yVbulsqn1gCeqwJ4glNUwsyojjBoUVn

**Device info (please complete the following information):**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by weslyhuang** [comment]
same with my S8+, Android 8. Unsure if this is by design? @Jacklin-ux would you help confirm? Tks.

**Comment by Jacklin-ux** [comment]
The description should be translated into Indonesian. It's a bug.

**Comment by mTwTm** [comment]
1. Firebase only changes it's bucketing to users when a user changes the system language. Changing language via our in-app locale switcher will not move the user from one bucket to another.
2. Even if a user switches her system language, I'm not sure how long does it take for Firebase to update the bucket. It takes at least an hour until I gave up last time when I tried this. It is possible that a user never moves from one locale bucket to another. Given these observations, it is recommended to uninstall an app and switch to another locale before testing Firebase related strings.
See also: https://github.com/mozilla-tw/Rocket/issues/2276

**Comment by chianger** [comment]
We can retest again since we removed these configs on firebase. It should fall back to in-product strings and should be following user config locale.

**Comment by chianger** [comment]
looks like it's happening again.

**Comment by witsmo** [comment]
Verify on Firefox lite 1.0.7(9086)
Device: Redmi 4A
OS: Android 7.1.2
