### ISSUE TITLE
Cannot dismiss the context menu in private mode

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2832]
**Describe the bug**
1. After  long press the image/link, cannot dismiss the context menu by press blank area/ back.
2. Have to click multiple times "copy clink address"

**Steps To Reproduce**
1. Launch Rocket
2. Switch to private browsing mode
3. Visit a webpage, e.g, kompas.com
4. Long press a link 
5. click back or blank area. 

**Expected behavior**
dismiss context menu

**Actual behavior**
have to do multiple times

**Screenshots/videos**
https://drive.google.com/open?id=1XNHZXXWtyEOpmNa0S5sPWt_o5NpZx2VP

**Device info (please complete the following information):**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by mTwTm** [comment]
Every time Rocket is put to background, the times that you need to click to dismiss a context menu +1.

**Comment by vanceyen** [comment]
Verified fixed with version 1.0.0(7916)
