### ISSUE TITLE
Found "Firefox Rocket"

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2835]
**Steps To Reproduce**
1. Go to Setting 
2. Click give feedback 

**Screenshots/videos**
https://drive.google.com/open?id=1BdAHSgiYlMS1bzoM5C5Lw7gEgepXPfdZ
https://drive.google.com/open?id=1UvtYjPR7lsS-F9gu-8KNSRp4J76eaVxX

**Device info (please complete the following information):**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by weslyhuang** [comment]
both "qsurvey" and "give feddback" can be config by marketing so should be fine? @elin-moco ?

**Comment by mTwTm** [comment]
Love Firefox Rocket removed in data meeting. Survey content pending.

**Comment by chianger** [comment]
survey content updated.
