### ISSUE TITLE
Hard to find the open button in private mode 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2836]
**Describe the bug**
It was difficult for me to find the open button in notification at the first time. The button is not easy to see. 

**Screenshots/videos**
https://drive.google.com/open?id=1EQ_wPivV-fJsOmH5jaNjjr_vE5sK9if2

**Device info (please complete the following information):**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by mTwTm** [comment]
It is Android Notification's default behavior to only unfold the actions of the first Notification. (The second Notification actions will be folded.) Propose invalid bug.

**Comment by chianger** [comment]
yes let's invalid this.

**Comment by ivantw08** [comment]
Is it a better to change the ui which have 2 different notification bar ? I didn't know have this feature without seeing the test case. Hard for me to see the open button for the first time.
