### ISSUE TITLE
Turbo mode not working via "Menu --> Settings -> Turbo mode switch"

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2838]
**Steps To Reproduce**
1. Launch Firefox
2. Go to a site with ads
3. Menu -> settings 
4. Disable/enable turbo mode

**Actual behavior**
disable/enable turbo mode is not working. 

**Screenshots/videos**
https://drive.google.com/open?id=1D0aZS6JyGhvSoTBZ4d83N8l6GsUYg7yh

**Device info (please complete the following information):**

-  Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

notes:
Both disable and enable are not working.

**Comment by weslyhuang** [comment]
Link used for test: https://nba.udn.com/nba/story/6780/3422644

Seems the top Ads can be blocked by turbo mode via "menu --> turbo mode button", but not via "menu --> settings -> turbo mode switch"

**Comment by mTwTm** [comment]
To me, I think the configuration does update when testing with https://www.aloodo.org/test/

**Comment by chianger** [comment]
interesting, I can still reproduce. using menu > settings  to switch of Turbo mode, but  https://www.aloodo.org/test/ still says Third party tracking not detected.

**Comment by ivantw08** [comment]
Detailed reproduce steps:
1. go to page  https://nba.udn.com/nba/story/6780/3422644
2. disable via  menu -> turbo mode
3. reload the page (you will see ads)
4. enable via menu->settings->turbo mode
5. reload the page again (still show ads)

**Comment by mTwTm** [comment]
@chianger Did you refresh or re-do the test? If you simply refresh you might see the cached result.

Also, we only reload the page automatically if it is on -> off.

**Comment by chianger** [comment]
I did re-run the test. My steps as below:
1. default value (the turbo mode is on), run  https://www.aloodo.org/test/  see no tracker detected  [expected]
2. clear cookies, form history, cache
3. menu >turbo mode toggle off and run  https://www.aloodo.org/test/ see tracker detected  [expected]
4. clear cookies, form history, cache
5. menu > setting> turbo mode switch on and run  https://www.aloodo.org/test/ see tracker detected  [UNEXPECTED]

**Comment by chianger** [comment]
Let's not block on this. Leave QAWANTED as a future action item to set up a stablel testing environment for us to verify and look into.
