### ISSUE TITLE
Redirect to website's home page in private page 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2847]
**Steps To Reproduce**
1. Launch Rocket
2. Switch to Private mode
3. Visit youtube.com and play a video
4. Switch to normal mode
5. Tap Open private browsing history in the notifcation

**Expected behavior**
back to video's page

**Actual behavior**
redirect to youtube's home page 

**Screenshots/videos**
https://drive.google.com/open?id=1AJhc0DWK2miNTBuyvqOgZvobHpWLB-9i

**Device info (please complete the following information):**

- Lite 1.0.0(7916)
- Device: Redmi 4A
- WebView: 69.0.3497.100
- Android: 7.1.2

------------
**note**
Same issue happened in yahoo's website 

**Steps To Reproduce**
1. Launch Rocket
2. Switch to Private mode
3. Visit yahoo and click a news
4. Switch to normal mode
5. Tap Open private browsing history in the notification

**actual behavior**
redirect to yahoo home page

**Comment by Jacklin-ux** [comment]
Expect: should back to video's page, so users no need to search the video again.

**Comment by chianger** [comment]
blocker for v1.0.1

**Comment by mTwTm** [comment]
Confirmed regression: Not happening on 3.0 (Private & Normal), Reproducing in 3.4.1 (Private)

**Comment by mTwTm** [comment]
Move blocker tag to #2930 @cnevinc believes the resuming is a separate bug.

**Comment by chianger** [comment]
this has been existing for multiple releases so it's not critical blocker. let's get it fixed in next release.

**Comment by chianger** [comment]
let's block this on K2 then.

**Comment by cnevinc** [comment]
This is fixed here 
https://github.com/mozilla-tw/Rocket/pull/2995

**Comment by Daisy-pliu** [comment]
**Test Scenario 1 result :** ✅
[Test Step]
1. Launch Rocket
2. Switch to Private mode
3. Visit Youtube.com and play a video
4. Switch to normal mode
5. Tap Open private browsing history in the notification
[Actual behavior]
navigate to Youtube video's page

**Test Scenario 2 result :** ✅
[Test Step]
 1. Launch Rocket
 2. Switch to Private mode
 3. Visit yahoo.com and click a news
 4. Switch to normal mode
 5. Tap Open private browsing history in the notification
[Actual behavior]
navigate to Yahoo new's page

[Test Device] 
SamSung S7 Edge (8.0.0)
[Test Build]
1.0.5 NIghtly (8905)

**Comment by Daisy-pliu** [comment]
verify above two scenarios : ✅
**Test device:** Redmi  (7.1.2)
**Test build:** 1.0.7 (9086)
