### ISSUE TITLE
Only allow one shortcut on the desktop.

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2857]
**Steps To Reproduce**
1. Launch Rocket
2. Go to a website (youtube)
3. Menu->shortcut
4. Go to another website (Wiki)
5. Menu->shortcut

**Expected behavior**
Have two shortcuts on the desktop 

**Actual behavior**
Only First shortcut is on the desktop.

**Screenshots/videos**
https://drive.google.com/file/d/1lncFXzAD-_ONcfPRXBnYc__tVdghOI7c/view

**Device info (please complete the following information):**

- Rocket 3.1.0(6747)
- WebView: 69.0.3497.100
- Advan i5C (Android 5.1)

**Comment by mxlius** [comment]
dup with #1980
