### ISSUE TITLE
Shortcut delete automatically  when rocket delete. 

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2858]
**Steps To Reproduce**
1. Launch Rocket
2. Go to a webstie (youtube)
3. Menu->shortcut
4. Delete Rocket app

**Expected behavior**
Rocket deleted and shortcut is still in the desktop .

**Actual behavior**
Both app and shortcut deleted.

**Screenshots/videos**
https://drive.google.com/open?id=1J0zL8XW777hWh5URnP4MU2yzXnvTYZxu

**Device info (please complete the following information):**

- Rocket 3.1.0(6747)
- WebView: 69.0.3497.100
- Advan i5C (Android 5.1)

**Note**
I tried other phone and all of them have this issue. I am not sure is bug or design? But so wired for me. I thought shortcut should still there.

**Comment by chianger** [comment]
low priority from my view. triage to make sure.

**Comment by mxlius** [comment]
@ivantw08  Do we have a spec somewhere said the shortcut should keep even after the app is uninstalled?

This is by android system launcher app design, NOT a bug or issue.
