### ISSUE TITLE
Provide side-by-side screenshots per locale for l10n comunity verification

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2871]
Firefox Lite 1.0 also came with a visual refresh so let's make a full list of screenshots.
Steps to complete such task
1. @josephyu1110 has the automated script to generate part of the screenshots
2. manual screenshots
3. put together 1 and 2

**Comment by josephyu1110** [comment]
Please provide the locale list for auto screenshot. Thanks.

**Comment by chianger** [comment]
English, Indonesian, Sundanese, Javanese, Hindi, Tagalog, Thai

**Comment by chianger** [comment]
depends on #1940

**Comment by josephyu1110** [comment]
[v 1.0.1 auto screenshots(Rocket 2.4 feature).](https://drive.google.com/file/d/1U0k040bA17zDrhRz5fD3z3Zv-H0ncqO5/view?usp=sharing)

**Comment by chianger** [comment]
https://drive.google.com/drive/u/0/folders/1O6HgB5gs0ks1EWQUgwdCSFzVNMu6A6af
v1.0.3 consolidated by  @Daisy-pliu
