### ISSUE TITLE
New tab is inserted at the top when open from external

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2904]
**Steps To Reproduce**
1. Search in Firefox Lite or open external link in Firefox Lite

**Expected behavior**
2. A new tab should be inserted at the bottom of the tab list

**Actual behavior**
2. A new tab is inserted at the top of tab list

**Device info (please complete the following information):**
Reproduced on multiple devices.

**Reproduce rate**
Always

**Comment by chianger** [comment]
I can reproduce only once out of my 10 tries.

**Comment by chianger** [comment]
I tried a few more times and it's roughly 3/18 reproducible.

**Comment by chianger** [comment]
QAWanted to check reproduce rate from QA.

**Comment by ivantw08** [comment]
When Firefox Lite is closed (cannot see in task manager). new tab will at the top of list.
When Firefox Lite at the background (can see  in task manager). new tab will at the bottom of list.

Reproduce rate 100%
Device info :
Device: Nexus 5
OS: Android 6.0.1
Webview 69.0.3497.100
Version 1.0.1(8154)

**reproduce step**
1.Launch Firefox Lite make  tab's number is 1.
2.Tap task manager and close Firefox Lite
3.Launch Chrome and select text to search in Firefox Lite.

Result
New tab is at the top of tab list

**Comment by chianger** [comment]
Oh yes. Per above steps i'm seeing same result.

**Comment by chianger** [comment]
QAWanted to further check if it's a regression.

**Comment by chianger** [comment]
plan is to check v1.0 and 3.4.1
https://github.com/mozilla-tw/Rocket/releases/download/v1.0.0/Firefox-Lite-7916.apk
https://github.com/mozilla-tw/Rocket/releases/tag/3.4.1

**Comment by ivantw08** [comment]
FirefoxLite(7916) doesn't have this problem 

@chianger  I downloaded FirefoxLite(7492). It showed App not installed. How do i install it ?

https://github.com/mozilla-tw/Rocket/releases/tag/3.4.1

**Comment by ivantw08** [comment]
@chianger  Both two version don't have this version
