### ISSUE TITLE
Tabs can't be resumed after Rocket have gone to background but not killed

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#2909]
**Describe the bug**
Not always reproducible. The existing tabs become blank and reload doesn't help.

**Steps To Reproduce**
1. Launch Firefox Lite and open a few tabs.
2. Launch another app. For instance Chrome, and select text to search in firefox lite
3. Firefox Lite is then brought up to the front. 
4. Tap on tab list view and select any tab other than the newly created one

**Expected behavior**
The page display correctly

**Actual behavior**
The page is all blank, though the URL bar seems fine. 
Reload doesn't help.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: PixelXL
 - OS: Android 8.1.0
 - Webview 70.0.3538.80
 - Version 1.0.1(8154)

**Reproduce rate**
2/6

Relevant to #2904

**Comment by chianger** [comment]
QAWanted to check reproduce rate from QA.

**Comment by ivantw08** [comment]
This issue relevant to #2904. 

reproduced video
https://drive.google.com/open?id=1BiKf-ADeXXB-SuBbmfS5zs4zv2qHtwyj

**Comment by chianger** [comment]
Per ivan's testing, keeps on the steps 1~3 can reproduce that bug.

**Comment by chianger** [comment]
QAWanted: want to know if it works on v1.0.0 and v3.4.1

**Comment by ivantw08** [comment]
Both 2 version cannot reproduced by steps:
1.open a tab via external app with Lite at the background
2.open a tab via external app without Lite at the background
3.open a tab via external app with Lite at the background

Keep trying in different way.

**Comment by ivantw08** [comment]
Cannot reproduced by v1.0.0 and v3.4.1.

**Comment by mTwTm** [comment]
STR can be simplified as:

1. cold start Lite (or, start Lite when it's not in background)
2. switch to another App
3. hot start Lite (or, resume Lite form background)
4. switch to any other tabs

Expected: tabs will be resumed

Actual: tabs won't be resumed until you manually refresh.
