### ISSUE TITLE
Cannot open deep link from [search or enter address] field

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/Rocket#2910]
**Description**
can not open deep link from [search or enter address] field

**Steps To Reproduce**
1. open Mozilla LTE app
2. click [+]
3.  enter [ fb://profile/14856729724 ]  in [ search or enter address ] field

**Expected behavior**
User is directed to see certain in-app FB page

**Actual behavior**
User see [the address wasn't understood]  page

**Screenshots/videos**
https://drive.google.com/open?id=1_Pixhj4NzT2N3fYbNhOnF_Ku61dbia3J

**Device info (please complete the following information):**
 - Device: Pixel2
 - OS: Android 9 
 - Webview : 70.0.3538.80
 - Version  : 1.0.0 (7916) RC build
Note : Simulator with Android 8 on Pixel 2 device also has this issue 

**Reproduce rate**
3/3

**Additional context**
However,  if user goes through below steps , user can see certain in-app Twitter page
1. click [search icon] on bottom bar
2. enter [fb://profile/14856729724]

**Risk analysis**
If user search deep link via [ search or enter address ] field,  they see [ the address wasn't understood ] page. 
But if they search deep link via [ search icon ] they can see deep link opened in app. The outcome for same search purpose is inconsistent.

**Comment by chianger** [comment]
seems to working fine with latest build v1.0.1 (8249)

**Comment by Daisy-pliu** [comment]
Should we close issue?

**Comment by Daisy-pliu** [comment]
Works good on v1.0 (8254)RC build
