### ISSUE TITLE
"Facebook comment plugin" will not load after, Turbo Mode is enabled

### ISSUE THREAD

**Issue by edentw** [mozilla-tw/Rocket#2914]
@mTwTm @josephyu1110 
Report a problem "Facebook comment plugin" will not load after, 
Turbo Mode is enabled. Simply put, the function is hidden.
Can you fix the problem? Thank you!

https://developers.facebook.com/docs/plugins/comments/

**Comment by chianger** [comment]
expected behavior: turbo mode has tracing protection on.

**Comment by mTwTm** [comment]
I think that's something we won't change recently given it's something we'd like to block. I've filed a bug #2945 as a possible followup. For now, please manually turn off Tracking protection to resolve the web compat issue.
