### ISSUE TITLE
Error page doesn't record in history

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2916]
**Steps To Reproduce**
1. Launch Firefox Lite 
2. Tab Search field and search a.b.c
3. Showed error page 

**Actual behavior**
Not recorded in the history

Should it be record ? 

**Device info (please complete the following information):**

- Lite 1.0.1(8254)
- Device: Nexus 5
- WebView: 69.0.3497.100
- Android: 6.0.1

**Comment by chianger** [comment]
QAWanted to check v3.4.1 and v1.0.0 on the same website.

**Comment by chianger** [comment]
if it's error page, by design we don't want the record. otherwise it's overwhelming.

**Comment by mTwTm** [comment]
Have history sounds like a 1.0.1rc1 regression to me, expect no history on both 1.0 and 1.0.1rc2
