### ISSUE TITLE
Use feedback: My phone heats uo when i use firefox lite

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2920]
My phone heats uo when i use firefox lite. And in video mode there should be some facilities like volume ,brightness incresing system. There should be some systen to forward video by 10 seconds like that.

**Comment by chianger** [comment]
there are two parts of this post: 1. the device heats up (this is tricky. QAWanted to check if we can reproduce. 2. dup as #2921

**Comment by witsmo** [comment]
Not able to reproduce with Samsung S8 Android 8
Firefox Lite 1.0.5(8905).nightly
WebView version:71.0.3578.99

**Comment by chianger** [comment]
not actionable as we're not able to reproduce
