### ISSUE TITLE
Tab history is discarded

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2951]
**Describe the bug**
Tab history is discarded

**Steps To Reproduce**
1. Open a tab
2. browse pages, go to next page, and so on.
3. Kill Lite
4. Open lite
5. Press back

**Expected behavior**
The last page visited is opened.

**Actual behavior**
Home is opened because the history is discarded.

Only on 1.0.1

**Comment by Daisy-pliu** [comment]
verify on 1.0.2(8433). it works good.

**Comment by ivantw08** [comment]
verified 
1.0.2(8433)
