### ISSUE TITLE
Make default browser - Press settings 2ed time Failed

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/Rocket#2955]
**Steps To Reproduce**
1. Launch Rocket 
2. Press settings 2ed time
3. Tap Make default browser notification
4. ReLaunch Rocket 
5. Press settings 2ed time

**Expected behavior**
 Show "Make default browser" notification

**Actual behavior**
nothing happened

**Screenshots/videos**
https://drive.google.com/file/d/1uzCL3pRk85lacwVyod0jse4QSBwajcsa/view

**Device info (please complete the following information):**

- Lite 1.0.2(8433)
- Device: Redmi 4A
- WebView: 69.0.3497.100
- Android: 7.1.2

**Comment by Daisy-pliu** [comment]
@ivantw08 no worries, will keep monitoring this issue in the candidate build.

**Comment by mTwTm** [comment]
The notification will not show if the device is already the default browser or Notification is disallowed.

**Comment by mTwTm** [comment]
Also, the threshold (2) is configurable.

**Comment by witsmo** [comment]
Did not have Android 9 device. Could not reproduce this issue.

**Comment by witsmo** [comment]
Verify Resolved: Firefox Lite
1.0.5(8905).nightly
WebView version:71.0.3578.99
Device: Samsung S8 Android 8
