### ISSUE TITLE
Indonesian notification goes to user's device which is set to Hindi

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#2958]
![gplus1544622735](https://user-images.githubusercontent.com/6755074/48989760-a1e68f00-f166-11e8-8d47-8f00ec64871a.jpg)

**Comment by chianger** [comment]
is this a user feedback or what you discovered ?

**Comment by mTwTm** [comment]
From the community.
Checked the setting and this message is set to only send to Indonesia.

**Comment by mTwTm** [comment]
The user is currently traveling in Indo, so kinda expected, I'll keep this bug open to decide if we will change the criteria for future notifications.

**Comment by chianger** [comment]
expected behavior so there's no action required. 
we'll let data meeting to determine whether we should consider "target audience".
