### ISSUE TITLE
Twitter links not opening properly

### ISSUE THREAD

**Issue by iamVP7** [mozilla-tw/Rocket#2977]
**Describe the bug**
Sometimes when I am clicking the twitter links from telegram to my default browser( Firefox Lite) it is not working properly.

**Steps To Reproduce**
1. Get some twitter link from friend in telegram
2. Click on that link
3. it should automatically get opened in Rocket

![screenshot_20181127-234539](https://user-images.githubusercontent.com/3106852/49143722-a60adc00-f321-11e8-9a1c-9917b2e3492d.png)

Then use Rocket reload tab button and then reload the page, it will work
![screenshot_20181127-234548](https://user-images.githubusercontent.com/3106852/49143772-bfac2380-f321-11e8-9b6e-1fd79bedb90a.png)

**Expected behavior**
On first click itself it should open the tweet properly

**Actual behavior**
Only on reload it works properly.

**Screenshots/videos**
Attached already

**Device info (please complete the following information):**
 - Device: Nexus 6p
 - OS: Android 8.1.0
 - Webview 70.0.3538.110
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
Have seen like this too many times. Tried to reproduce intentionally at that time not able to do it.

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
Need triage - Yes
S1/S2/S3 - s1

**Comment by chianger** [comment]
QAWanted to confirm we can reproduce generally.

**Comment by Daisy-pliu** [comment]
After testing on Pixel XL (8.1.0) we could not reproduce it so we attach the [testing video](https://drive.google.com/file/d/1aBVBcpPrnwECZaa8_5qcPIX13vlzsbLx/view?usp=sharing) and advise any detail steps. 
we also refer [Twitter document regarding rate limits](https://help.twitter.com/en/using-twitter/twitter-rate-limit) concern please take a look and hopefully which will answer your question.

**Comment by chianger** [comment]
It's more likely the website host's defined behavior. We do not have actionable items for this.
