### ISSUE TITLE
User feedback: every time i save an image from website, it always fails.

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2985]
1 star because every time i save an image from website, it always fails. even though the sdcard space is still enough. Please fix it.

**Comment by chianger** [comment]
QAWanted to look for the STR so that we are able to define actions.

**Comment by witsmo** [comment]
Verify resolved: Firefox Lite
1.0.5(8905).nightly
WebView version:71.0.3578.99
Device: Samsung S8 Android 8
