### ISSUE TITLE
Regression: can't open page from added to home shortcut

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2987]
1 Add to homepage a site 
2 Then goto other sites
3 Goto Android home
4 Tap the short cut that was added
5 Site isn't launched

**Comment by joechengla** [comment]
v1.0.3 (8516)

**Comment by joechengla** [comment]
https://drive.google.com/file/d/16PFLM_Y5FJOdLlXCT5pdWLjg3CMAQaaP/view?usp=sharing

**Comment by joechengla** [comment]
pressing back and pressing home on Firefox Lite seems to give inconsistent behaviors

**Comment by cnevinc** [comment]
Can't reproduce it on Android 9, Pixel Webview 71, 1.0.3(8635)

**Comment by chianger** [comment]
QAWanted to look into this. If it's regression we would want a regression window for sure.

**Comment by witsmo** [comment]
Verify resolved: Firefox Lite
1.0.5(8905).nightly
WebView version:71.0.3578.99
Device: Samsung S8 Android 8
