### ISSUE TITLE
Regression: Need to repeatedly login to instagram

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#2988]

**Comment by joechengla** [comment]
https://drive.google.com/file/d/1kY3DNGtg6qs4MCGyo2OA6PjkVpBN2i57/view?usp=sharing

**Comment by mTwTm** [comment]
Not reproducing on my Android 8 Nokia 5.1 plus Webview 70. (Joe's is 71)

**Comment by chianger** [comment]
QAWanted to seek for STR.

**Comment by mTwTm** [comment]
I can reproduce now I'm on Webview 71

**Comment by witsmo** [comment]
Verify resolved: Firefox Lite 
1.0.5 (8905). nightly 
WebView version 71.0.3578.99
Device: Samsung S8 Android 8
