### ISSUE TITLE
Switch search code to new Google code

### ISSUE THREAD

**Issue by mkaply** [mozilla-tw/Rocket#2997]
We'll be using a new search code for Google going forward. This issue is to us that new code.

For our mobile products, we should switch to:

firefox-b-1-m for the US and firefox-b-m for rest of world.

**Comment by mTwTm** [comment]
An initial fix to this is to simply change from firefox-b to firefox-b-m in #3002.
I'm not sure if we actually would want to also do firefox-b-1 when U.S. sim cards / IPs are detected. Let's file another bug if that is needed.

**Comment by cnevinc** [comment]
According to Mike's comment:
> Since rocket is only outside the US, you don’t need to do code checks. I’ll review.
> Testing it should just be doing a google search and making sure it uses the new code.

**Comment by Daisy-pliu** [comment]
**Verify :** ✅
**Build version:**
1.0.7 (9086) 
**Test Device:**
Redmi 5 Plus (7.1.2)
**Test result:**  
It shows correct --> client = firefox-b-m
