### ISSUE TITLE
Spike for e-commerce portal #1999

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#3034]
feasibility for UX spec in #1999

**Comment by cnevinc** [comment]
Last discussion with @Jacklin-ux 
1. Currently, we only have the csv file for item category. 
2. It's hard to support the item discovery scenario with tag/keyword. coz:
 a. There's no API support for Items update for certain keyword
 b. Bukalapak API has "keyword" parameter, but it's not official and may change in the future.
3. Suggested action items:
 a. Talk to Bukalapak dev team and find out more API support so we can design better UX.
 b. Re-design our UX using just csv fille.
 c. If we can come up with a general purpose content/portal design, maybe we can start design/impl first (e.g. a slide up but customizable panel)

**Comment by cnevinc** [comment]
finally decision:
1. We only have CSV. It's not useful for users coz:
 a. It's not real time.
 b. The size of one category is huge( 8.5MB) 
 c. It lacks paging sport
2. We have HTTP links for promotion, category, search. We'll use category for content-portal, and use search keywords for quick-search engine bar.
