### ISSUE TITLE
Default search engine not set to Google in ID

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/Rocket#3067]
STR:
1. Set the default search engine to Google
2. Switching locale to ID 
3. Do a search using a keyword.

Expected:
The search engine should stay the same.

Actual
Default search engine for Google is missing. It becomes Yahoo.

**Comment by Daisy-pliu** [comment]
Test Result: ✅
Test device : Redmi 4X (7.1.2)
Version: 1.0.9(9367).nightly 
Webview: 71.0.3578.99
Test step:
1. change system language to indonesia
2. launch app (clear app data)
3. go to [search engine] in [settings]
Test result:
User can see Google, Yahoo, DuckDuckGo search engines
