### ISSUE TITLE
[Smoke Test] Twitter screenshots contains considerable amount of blank space

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#321]
as title

Build: 417
DuT: Lenovo Vibe A
![screenshot 1](https://lh3.googleusercontent.com/-ZoVi0hg7Fgs/WZZGRe5RyQI/AAAAAAAAAJA/apQ0cDa_HNECybkU4s3jZwOD_eVeV9fjgCL0BGAYYCw/h11781/8219912906218300026%253Faccount_id%253D1)

**Comment by harly21** [comment]
Happens on Instagram as well!!

**Comment by chianger** [comment]
non-actionable for now.

**Comment by weslyhuang** [comment]
suggest updating new information to the newer one #1379 directly (and close this one).

**Comment by NashTung** [comment]
This issue can be reproduced and updated information on #1379 directly.
