### ISSUE TITLE
improved set default browser

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#346]
Improve the guidance to end users after prompting user to set Zerda as default browser.

**Comment by chianger** [comment]
we would want to do this if there's no significant risk.

**Comment by weslyhuang** [comment]
next step in UX design proposal.

**Comment by weslyhuang** [comment]
IN for May 12.

has new strings.

**Comment by mTwTm** [comment]
Do we really need new string for this? I'm not involved in this but I don't see any string spec here.

**Comment by walkingice** [comment]
Per Max's implementation, it seems we will add one string to notification
https://github.com/mozilla-tw/Rocket/commit/d2ab36d386b8dffccfe5322b0c86c0733675d230#diff-a7ca4f9ecc233fc28adfd9cc8d54f96eR154

**Comment by weslyhuang** [comment]
@walkingice  just to be sure, are we still lacking strings and spec for this issue? or we can remove the "UX&VD Wanted" and "String Wanted" labels now? thanks.
