### ISSUE TITLE
404 page title in History

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#401]
When 404 (or no internet connection or server not found) , the titles of history items will become %pageTitle%, and if the **_Try Again_** button is tapped, part of the headers will appear in history,

![screenshot](https://lh3.googleusercontent.com/-QdLiwlWE4Uo/WZ5uKQ7H6KI/AAAAAAAAANg/DIbxMH5vkKULRE5dkfZOSYk8PnUwRza6gCL0BGAYYCw/h1920/2329462438644562333%253Faccount_id%253D3)

If coming from other website (200), the 404 page will take its favicon, 

![screenshot](https://lh3.googleusercontent.com/-7RWmjwsb2RY/WZ5wXJUXp8I/AAAAAAAAAOI/co1_CLJTGcwUXAMJicMZAb0s9nQNfP9bACL0BGAYYCw/h1920/5376382403326975673%253Faccount_id%253D3)

If coming from other website ([403](Weevah2.top) or [400](eltrack.pro)), the 404 page will take its title, 

![screenshot](https://lh3.googleusercontent.com/-WsMMIfEwaSw/WZ5yeLggLvI/AAAAAAAAAOs/ZYXmPT9Q8pw0L93QQ8JmtgqXdGAlrDOxgCL0BGAYYCw/h1920/2222789299555796241%253Faccount_id%253D3)

Build: 492
DuT: Samsung J7 Prime

**Comment by mTwTm** [comment]
Sounds like a P2 to me if this still applies.

**Comment by NashTung** [comment]
Work for me.
1. When 404 page, the titles of history items will become %pageTitle%:
Video: https://drive.google.com/open?id=1vGTDT-sUEDrMXxOk4rwdtAjjhCSqy7Pq
2. When 404 (or no internet connection or server not found) , the titles of history items will become %pageTitle%
Video: https://drive.google.com/open?id=1TcbAPB33cH4DQyleSV6AQiY9g9MFNG6y
3. If coming from other website (200), the 404 page will take its favicon
Video: https://drive.google.com/open?id=1csR-rRuz-jUW2kjZLKK59xC5KMZ1dH-6
4. If coming from other website (403 or 400), the 404 page will take its title
Video: https://drive.google.com/open?id=11F0eyz8LtI0jZFATxBBUCtKjCqbM5ng6

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
