### ISSUE TITLE
[WebCompat] Unable to take the survey on test pilot

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#523]
I was failed to take the survey of send.firefox.com

[survey](https://qsurvey.mozilla.com/s3/txp-firefox-send)

**Comment by NashTung** [comment]
It works on me
Video: https://drive.google.com/open?id=19KQPDzihBcZH6PZ75S8QhCL6pYj6137i

Device: Redmi 4A
Rocket: 2.1.1(4587)
Android: 7.1.2
Android Webview: 66.0.3359.158
