### ISSUE TITLE
Can't respond to a system language change until reopening Zerda

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Rocket#581]
Happens when Zerda's language is System Default.
**Build:** 724

**Comment by idiotmax** [comment]
Please provide more detailed STR(step to reproduce)

**Comment by Conjuror** [comment]
Prerequistie:
System default language as English

STR:
1. Launch Zerda
2. Change default language to Indonesia from System Settings
3. Back to Zerda by switch between App
4. Re-launch Zerda

Expected Result:

3. Zerda is displayed in Indonesian
4. Zerda is displayed in Indonesian

Actual Result:

3. Zerda is displayed in English

**Comment by chianger** [comment]
In what case does Rocket display as per system language? reboot whole system?

**Comment by NashTung** [comment]
It work on me
Video: https://drive.google.com/open?id=1TEg93lY0tIGy0752Ngz36PTtdjQq5Wct

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158

**Comment by ivantw08** [comment]
work well 

Device:

Device:nexus 5
OS: Android: 6.0.1
WebView: 69.0.3497.100
Firefox Lite: 1.0.0(7855)
