### ISSUE TITLE
[dogfooding] 18MB cleared, is this the upper limit?

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#591]
18MB cleared, is this the upper limit?

**Comment by chianger** [comment]
let's investigate if it;s really a bug

**Comment by chianger** [comment]
Looking inside WebView and realized it is the accurate number. INVALID this one.

**Comment by walkingice** [comment]
ref: https://bugs.chromium.org/p/chromium/issues/detail?id=323871

**Comment by dakaizou** [comment]
verified as invalid
