### ISSUE TITLE
Form History won't work on some websites.

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#651]
For examples:
* Login Facebook
STR:

1. Login Facebook
2. Logout Facebook
3. Clear Cache/Browsing History/Cookies
4. Go to Facebook login page
5. Tap on Account

Expected Result:

5. Previous login account is shown

Actual Result:

5. Nothing happens

Google will have the same issue

**Comment by chianger** [comment]
action item: QAWANTED test with other website and see if the form history function works.

**Comment by cynthiatang** [comment]
After user clear Cache/Browsing History/Cookies and reload the FB login page, there is no previous login account. It makes sense.

**Comment by weslyhuang** [comment]
works now, close.
