### ISSUE TITLE
[Smoke Test] Screenshots of some websites are wider than the device width

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#674]
![screenshot](https://lh3.googleusercontent.com/-erqx7ClkQwc/WbH--h3jIoI/AAAAAAAAAfE/il8V-tN9Q5g0b41cBvTOaBSr5hgySRyFQCL0BGAYYCw/h1920/470941731237767330%253Faccount_id%253D3)

Build: 855
DuT: Samsung, Advan

**Comment by mTwTm** [comment]
Sounds like this is for the case when item height is smaller then device. We should fit with width only on screenshot viewer.

**Comment by chianger** [comment]
P2 for now but for next version we would come back to see the overall usability.

**Comment by dakaizou** [comment]
verified in build 1593
