### ISSUE TITLE
Image downloaded from google image search result becomes image.bin

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#677]
STR:
1. Search image with google (e.g. [https://www.google.com.tw/search?q=mozilla&tbm=isch](https://www.google.com.tw/search?q=mozilla&tbm=isch))
2. Long tap the images which can be downloaded (7th and 8th should be downloadable)
3. Save image
4. Check Downloads panel

Build: 855
DuT: Advan, Samsung

**Comment by chianger** [comment]
the filename is strange but it can still be opened and viewed.

**Comment by dakaizou** [comment]
@chianger It depends on the device. (e.g. Samsung's Gallery can't view or open the file, and can't even rename the file with My Files)

**Comment by chianger** [comment]
current limitation if using system downloader.
this will be tracked as known issue. remains p2.

**Comment by chianger** [comment]
Lightning browser and Focus currently have the same behavior

**Comment by WeiWW** [comment]
We can't get any information, such as MIME type or file extension from link, to decide what the file should me.

**Comment by mTwTm** [comment]
Fixed in #1154

**Comment by dakaizou** [comment]
verified in build 1626
