### ISSUE TITLE
String "Add to home screen" is too long and cannot be displayed

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#72]
This can get better but more possibly worse after translation. We need to figure out what we want to do with this kind of problems.

**Comment by Conjuror** [comment]
This is a P2 feature now. Put it to correct category

**Comment by Conjuror** [comment]
This is a P2 feature now. Put it to correct category :D

**Comment by chianger** [comment]
We don't have "Add to homescreen" now
