### ISSUE TITLE
[Smoke Test] Canceling download shouldn't remove the item from the list

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#724]
STR:
1. Download a large file
2. Tap on menu
3. Tap on downloads
4. Tap on item menu
5. Tap cancel while it's downloading

Expected result:

6. Item still exists with "canceled" at the bottom

Actual result:

6. Item removed

Build: 950
DuT: Samsung

**Comment by mTwTm** [comment]
This is the result after discussed with UX @FlyTori can you confirm?

**Comment by FlyTori** [comment]
Yes. For this version, remove the file from list is fine.

**Comment by joechengla** [comment]
i think remove from list is the expected behavior. @FlyTori if you agree, let's close it

**Comment by NashTung** [comment]
This issue can be reproduced
Video: https://drive.google.com/open?id=16JTsE2-Og4unMEOPfKM_82w5EIEnnxKM

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126

**Comment by mTwTm** [comment]
@Jacklin-ux can we close this?

**Comment by Jacklin-ux** [comment]
@mTwTm Yes, please close this issue.
