### ISSUE TITLE
[Smoke Test] Privacy notice links to 404 (Release)

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#769]
STR:
1. Tap on Menu
2. Tap on Settings
3. Tap on About
4. Tap on Privacy Notice

Build: 1019
DuT: Oppo, Samsung

**Comment by Ben-YPLai** [comment]
“Privacy Notice” open “https://www.mozilla.org/privacy/firefox-rocket/”.
The web is not ready?

**Comment by chianger** [comment]
@eleemoz do you have eta for this?

**Comment by chianger** [comment]
It requires to uplift only when we have the privacy notice (final) in position

**Comment by chianger** [comment]
currently we're using data reviewed wiki page.
Before nov7 release we should link it back to the correct privacy page.

**Comment by chianger** [comment]
Fixed from both server side and in-product link
