### ISSUE TITLE
Text context menu is too large

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Rocket#793]
Set Zerda language to Indonesian ->

![outofscreen](https://user-images.githubusercontent.com/8446577/30464826-6ce035b2-9a06-11e7-8828-5c37c23ebb23.png)

**DuT:** Samsung
**Build:** 1050

**Comment by cssjh** [comment]
This screenshot is taken with system language set to English and Zerda set to Indonesian:
![10-1](https://user-images.githubusercontent.com/8446577/30469867-0ccc403e-9a25-11e7-98f3-5bb1275dde10.png)

**Comment by flodolo** [comment]
It doesn't seem to happen in https://conjuror.github.io/Zerda-Screenshots/id/10-1.png

Positioning problem?

**Comment by Conjuror** [comment]
It happens only if you are in Indonesian Language and set the Zerda app language to Indonesian.

**Comment by cynthiatang** [comment]
This cannot be reproduced in Rocket 2.0.
