### ISSUE TITLE
Facebook.com total blank after login occasionally

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#796]
as title

Build: 1033, 1050
DuT: Samsung, Advan

**Comment by chianger** [comment]
Need continuous monitoring this

**Comment by mTwTm** [comment]
I believe I've still seen this. The STR is some sort of like: a page does not loads after clicking on the top site or entering a address.

**Comment by chianger** [comment]
Non-blocking so downgrade to P2 for future tracking

**Comment by cynthiatang** [comment]
This issue cannot be reproduced in Rocket 2.0
