### ISSUE TITLE
[dogfooding] Zerda goes back to top site page sometimes after switching to other app then switching back

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#835]
Zerda goes back to top site page sometimes after switching to other app then switching back.

as title

**Comment by chianger** [comment]
IIRC, tori's phone can reproduce it but neither can AL or myself can reproduce it for a week.

**Comment by cynthiatang** [comment]
This issue cannot be reproduced in Redmi Note4 with Rocket2.0
