### ISSUE TITLE
[dogfooding] Press delete key on keyboard didn't remove autocomplete

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#837]
When searching, after inputing some words then press delete key on keyboard, the word will be displayed abnormally

**Comment by dakaizou** [comment]
Possible related to #610

**Comment by chianger** [comment]
QAWanted to have clearer STR so that we can have Fable support.

**Comment by dakaizou** [comment]
STR:
1. Tap on search bar
2. Type in "moz"
3. Tap on device delete (the autocompleted text has been deleted, only user-typed text left)
4. Tap on "m" (now the "z" is replaced with "m")

Note: This only happens on devices using buffered input method (notice the underscore in the recording)

DuT: Oppo

**Comment by Conjuror** [comment]
Note that this can be reproduce if you are typing with input method. For an example, use 注音 or 無蝦米, typing a word and tap on delete key. The buffered alphabet is still on the input field, until you type in another word/alphabet to replace it.

Suggest to P2 and put as low priority

**Comment by Conjuror** [comment]
Remove QAwanted as STR is clear.

**Comment by chianger** [comment]
Removing P2 items from sprint8.

**Comment by mTwTm** [comment]
I'll take this one, thanks for your study @joseph-yar !

**Comment by mTwTm** [comment]
Fixed in #1187
