### ISSUE TITLE
[dogfooding] YouTube fullscreen video lags

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#839]
YouTube fullscreen video lags

STR:

1. Launch Zerda
2. Visit youtube and play a video
3. Tap the full screen icon on the bottom-right
4. Rotate the device between horizon and landscape

Expected:

4. No lag and sound plays without jerky

**Comment by Conjuror** [comment]
QAwanted for performance measurement

**Comment by dakaizou** [comment]
See [result](https://docs.google.com/spreadsheets/d/10rr25AnsvCsock9Msv4fGGdbHDG-EXQaI8JD98nBcq4/edit#gid=484507712&range=J4:M6) and [recording](https://drive.google.com/drive/folders/0B-hmv-8fniTNUUtwVFBBVS1OLVU)

remove QAwanted

**Comment by Conjuror** [comment]
Tested locally with low end devices with Chrome and UC browser, the behavior is acceptable for me. No sure if we want to have more progress on it before shipping. Suggest to put as performance issue and P2.

**Comment by Conjuror** [comment]
[Triage] We decide to put resource to it and study what we can improve the video playing part.

**Comment by chianger** [comment]
Still reproducible on Z3c, but at this moment from front-end we have not much to do.

**Comment by chianger** [comment]
QAWanted to investigate if we can still reproduce, and what HW spec can.

**Comment by cynthiatang** [comment]
It works for me now. Thanks. :)

Device: Redmi Note4
Rocket nightly: 1.0.4 (2910). nightly
Android version: 7.0
WebView version 65.0.3325.109
