### ISSUE TITLE
Can't open keyboard after entering & leaving full screen on YouTube

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Rocket#842]
**STR**
_for Android 7.0+_
1. Open a YouTube video
2. Enter full screen
3. Leave full screen
4. Tap on YouTube search button -> keyboard won't appear

**DuT**: Pixel, Zenfone 3
**Build**: 1105

**Comment by Conjuror** [comment]
This happens on Android 8.0 as well. We'll need to take a look after release as soon as possible.

**Comment by chianger** [comment]
P2: only for 7.0+;  opera mini and focus have the same issue

**Comment by Ben-YPLai** [comment]
I found the view might lose focus after exit Fullscreen for Android 7+.
Add an EditText to request focus after exit Fullscreen will fix it.
