### ISSUE TITLE
Progress bar now repeating as sliding down timeline

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#863]
Happens on [instagram.com](https://www.instagram.com) and [facebook.com](https://www.facebook.com). Twitter works fine.

Build: 1124
DuT: Samsung, advan

**Comment by mTwTm** [comment]
Webview sending:

10
10
20
21
48
69
87
88
94
95
96
96
100
100
10
100
100
10
100
100
10
100
100
10
100
100
10
100
100
10
100
100
10
100
100
10
100
100
10
100
100

The 10 100 100 are the one sent when progressive loading, makes sense to me but on Fennec and Chrome there are no such loading indicators. not sure if we should ignore these.

**Comment by chianger** [comment]
more like an enhancement we can look at it later.

**Comment by dakaizou** [comment]
Progress bar appears every time hit the menu on kompas.com
[recording](https://drive.google.com/file/d/0B0uVZlaHN366emh1X2NUVUNvVU0/view?usp=sharing) of build 1178

**Comment by Conjuror** [comment]
the same on yahoo.com

**Comment by dakaizou** [comment]
verified in build 1593
