### ISSUE TITLE
Visit an unavailable website and screenshot it will cause hang issue

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#872]
STR:

1. visit http://wesley.huang
2. Tap Menu
3. Tap Screenshot

Expected Result:

3. Screenshot is taken

Actual Result:

3. Screen is hang

**Comment by Conjuror** [comment]
btw, while connecting to wesley.huang, sometimes it's a blank page. Somtimes, it's a error page.

**Comment by chianger** [comment]
Hard to reproduce at this moment.
Leave to decision pending but let's keep tracking this.

**Comment by chianger** [comment]
Downgrade to P2 since this is more like edge case.
We would like to revisit it soon after Oct9.

**Comment by chianger** [comment]
If we cannot reproduce it anymore, we can close it.
Keep P3 for tracking and leave QAWanted to try more times.

**Comment by cynthiatang** [comment]
Verified: this issue cannot be reproduced. Thanks. :)

Device: Pixel 2
Rocket nightly: 1.0.4 (2910). nightly
Android version: 8.1.0
WebView version 65.0.3325.109

**Comment by NashTung** [comment]
This issue cannot be reproduced
Video: https://drive.google.com/open?id=1zZGxkNdUgIxnlcj8Nro0asoPGJDzp8x2

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
