### ISSUE TITLE
[Smoke Test] Search suggestions don't support some of the unicode characters

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Rocket#884]
![screenshot](https://lh3.googleusercontent.com/-yaf6HRnEUdY/WcMdt-sf2JI/AAAAAAAAA6I/vJIxk3lQZcI2T_e5tj_COkiFbB9I8QNggCL0BGAYYCw/h1920/7770671835303190839%253Faccount_id%253D3)

Build: 1158
DuT: Samsung, Advan

**Comment by walkingice** [comment]
I can reproduce by just typing 'mozs', on Pixel
![wrong_decoding](https://user-images.githubusercontent.com/54793/31924254-8019419e-b8b2-11e7-8d00-2be50bf7bc76.png)

**Comment by walkingice** [comment]
In UrlInputPresenter, we hard-coded charset to 'utf-8'. According to response header, it says

```
Content-Type: text/javascript; charset=ISO-8859-1
```

If we hard-coded charset to 'ISO-8859-1', then we got result
![correct_decoding](https://user-images.githubusercontent.com/54793/31924321-e32d7b06-b8b2-11e7-83d2-624fe3dd3b9c.png)

We might need to find a way to specify charset when sending request

**Comment by chianger** [comment]
degree C can reproduce.

**Comment by chianger** [comment]
query using Rocket through  DudkDuckGo is fine.
using Chrome through Google search is fine.

**Comment by mTwTm** [comment]
Beta no longer reproduce while degree C still reproduce.

**Comment by mTwTm** [comment]
Yet another useragent problem, try:

> tyu-40227:Rocket tyu$ curl 'https://www.google.com/complete/search?client=firefox&q=%E2%84%83'
> ["\u2103",["?c","?c-ute","?c ?f","?c \u82F1\u6587","?c ?f\u63DB\u7B97","?c/w","?c unicode","?c-ute ptt","?c\u003d?f","?ccomplete single collection"]]

> tyu-40227:Rocket tyu$ curl -A "Mozilla/5.0 (Linux; Android 7.1.2; rv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Rocket/1.0.debug.tyu Chrome/62.0.3202.84 Mobile Safari/537.36" 'https://www.google.com/complete/search?client=firefox&q=%E2%84%83'
> ["℃",["°c","°c-ute","°c °f","°c 英文","°c °f換算","°c/w","°c unicode","°c-ute ptt","°c\u003d°f","°ccomplete single collection"]]

I've tried "Mozilla" "UserAgent" too, no luck, but "Mozilla/5.0" works. I'll begin with using Rocket UA.

Well this is a bit weird and might need some clarifications.
