### ISSUE TITLE
Go to Yahoo and tap email show error page but can not go back to Yahoo by pressing back button

### ISSUE THREAD

**Issue by harly21** [mozilla-tw/Rocket#889]
As title

**Comment by Conjuror** [comment]
not sure if we can improve it. Suggest to P1 by severity

**Comment by chianger** [comment]
Focus has the same issue.

**Comment by chianger** [comment]
QAWanted to confirm this. It's supposedly fixed already.

**Comment by dakaizou** [comment]
It doesn't reproduce on any of Samsung J7, Advan, Oppo or Andromax. They all back to yahoo.com after tapping back key as it should be. But the url will sometimes stay "ymail://.." for a little while.
See [recording](https://drive.google.com/file/d/0B0uVZlaHN366M1otR3Z3ZktJa1U/view?usp=sharing)

**Comment by chianger** [comment]
removing from sprint8 since we downgrade this to P2.

**Comment by chianger** [comment]
dup #1218
