### ISSUE TITLE
Duplicate top sites

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Rocket#915]
**STR**
1. Visit a default top site (m.facebook.com and m.tribunnews.com for example)
2. Refresh 3+ times ->
![duplicatetopsites](https://user-images.githubusercontent.com/8446577/30797267-e89a4860-a207-11e7-85cf-99c6de575ea2.png)

**Build**: 1158

**Comment by mTwTm** [comment]
Could be due to trailing `/`

**Comment by dakaizou** [comment]
verified in build 1641
