### ISSUE TITLE
[Logo] Change the font style of "Firefox Rocket" in the home page

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/Rocket#949]

**Comment by chianger** [comment]
need Carol to provide the new logo.

**Comment by carol-mozilla** [comment]
Hi @WeiWW here's the assets: https://drive.google.com/open?id=0B-9PIePlQZRlNUlFTnB5MTRkLXM
Please tint logo #363959 on About page! thanks!

**Comment by dakaizou** [comment]
verified in build 1512
