### ISSUE TITLE
[dogfooding] can not view normal amazon pages

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#983]
can not view normal amazon pages (Amazon: either the browser version is too old or the browser doesn't support cookie)

**Comment by chianger** [comment]
It seems working correctly both on amazon.com and amazon.co.jp. 
P2 to keep monitoring.

**Comment by joechengla** [comment]
wfm. why don't we close it. please reopen if you believe we should keep tracking this.
